### ISSUE TITLE
[Категория] ID 1 - Тестовый репорт

### ISSUE THREAD

**Issue by ForesterDev** [VirginTeam/VirginCore#1]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Скриншоты демонстрирующие проблему, выделение проблемных мест с помощью графических редакторов приветствуются. Для описания ошибок, возникающих только в движении, снимите видео **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проект или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Тестовый репорт

**Что работает не так?**

Откатило ШМ помогите

**Как должно работать?**

ШМ не должно откатывать

**Шаги для воспроизведения ошибки:**

1. Шаг один - проснитесь
2. Шаг два - зайдите в игру
3. Шаг три - ШМ откатило

**Текущее обновление ядра:**
любое
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой

**Comment by Kodekc** [comment]
У меня тоже ШМ откатило, подтверждаю, надо чинить

**Comment by Devinette** [comment]
Ачивка есть, а ШМа нет!

**Comment by Riazarre** [comment]
У меня в сумке было 3 ШМа, прошу превратить их в Тори'Дал!

**Comment by ForesterDev** [comment]
Кароч, задонатил новый ШМ, можно закрывать

**Comment by Riazarre** [comment]
reop?
