### ISSUE TITLE
[Заклинание] ID 691 - Призыв охотника Скверны

### ISSUE THREAD

**Issue by nimpik** [VirginTeam/VirginCore#10]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Скриншоты демонстрирующие проблему, выделение проблемных мест с помощью графических редакторов приветствуются. Для описания ошибок, возникающих только в движении, снимите видео **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Когда садишься на маунта с фул хповым петом, а потом слазишь то у пета остается 20% хп. Естественно его почти сразу убивают.
**Что работает не так?**
Хп пета не должно так изменяться.
Фактический результат — тот, который вы наблюдаете
https://youtu.be/Gsv2i7FAicQ

*Текущее обновление ядра:**

151 2017-04-03 15:25:08 +0400

**Comment by ForesterDev** [comment]
В ближайшем обновлении будет исправлено
