### ISSUE TITLE
[задание] ID 1093/6000 Супердровосек 6000

### ISSUE THREAD

**Issue by Stlor** [VirginTeam/VirginCore#105]
Не падает квест итем ID 5734/6000. По описаню на вовхеде шанс его дропа 31%, с 15 мобов не упал ни разу.

**Comment by Stlor** [comment]
Не падает квест итем ID 5734/6000. По описаню на вовхеде шанс его дропа 31%, с 15 мобов не упал ни разу.

**Comment by Riazarre** [comment]
Оформите репорт, или он будет закрыт.

**Comment by Riazarre** [comment]
Закрыто.
