### ISSUE TITLE
[Задание] ID 11690 - Верни их живыми!

### ISSUE THREAD

**Issue by sega693** [VirginTeam/VirginCore#107]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

OFFTOP: зачем вообще этот пункт? И в шапку добавьте шаблон "[Категория] ID № - Название" для удобства, если можно.

http://wowroad.info/?quest=11690

**Что работает не так?**

Скидывает с [Зараженный кодо](http://wowroad.info/?npc=25596), и он убегает на место. При этом вешается бой на пол секунды. Невозможно доехать то места назначения. Адекватно доставить получается только ближайшего кодо.

**Как должно работать?**

Кодо должен без проблем доезжать до квестгивера.

**Шаги для воспроизведения ошибки:**

1. Сесть на кодо
2. Ничего не делать / а если повезет, то сделать пару шагов или вступить в бой

**Текущее обновление ядра:**

Build 153 2017-04-13 14:06:16 +0400
Live Server

**Comment by Nattpyre** [comment]
Опытным путем выяснилось, что скидывает, когда моб агрится. Если весь путь следования зачистить, то в принципе квест выполним (по крайней мере я его смог сделать). Плюс еще по прибытию желательно кнопку сдачи кодо спамить, иначе если слишком близко к НПС подойти, то тоже скидывает.

**Comment by sega693** [comment]
Некоторые кодо вроде бы далеко от мобов, но моментально скидывает, как только садишься. И так же комбат на пол секунды появляется.. В любом случае исправить не помешает.

**Comment by Luchass** [comment]
> OFFTOP: зачем вообще этот пункт? 
У тебя нет ссылки на задание.

**Comment by sega693** [comment]
а для чего айди в шапке писать тогда?

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
