### ISSUE TITLE
Квест Кролмир, Молот Бурь.

### ISSUE THREAD

**Issue by Dagi101** [VirginTeam/VirginCore#109]
Описание
http://wowroad.info/?quest=13010
Что работает не так?
После разговора с Королем Йокумма вы садитесь на него и больше не можете не как слезть. 
Как должно работать?
https://www.youtube.com/watch?v=dyudqwxb4GY
Шаги для воспроизведения ошибки:
1. Взять квест.
2. Поговорить с Королем Йокумма.
3. Сесть на короля и застрять на нём...

**Comment by ForesterDev** [comment]
Исправлено, проверяйте после установки обновления
