### ISSUE TITLE
[Группа заданий] Крепость песни войны

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#11]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Скриншоты демонстрирующие проблему, выделение проблемных мест с помощью графических редакторов приветствуются. Для описания ошибок, возникающих только в движении, снимите видео **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Задания цепей Орды Нордскола начинающиеся с 
Бдение Адского Крика http://ru.wowhead.com/quest=11586  
Оборона крепости Песни Войны http://ru.wowhead.com/quest=11595 
Невысказанные истины http://ru.wowhead.com/quest=11614
может и раньше.
Примеры забаганных игроков: х1 лич Буйтур,

**Что работает не так?**

Суть в том, что после прихода НЕКОТОРЫХ игроков (забагивание выборочное у разных расс) в Нордскол отсутствуют цепочки задания в крепости песни войны, в последующем и отсутствуют зависимые цепи по всему Нордсколу и других локациях.
Требуется переботка последовательностей заданий возможно проблема кроется в задания подобного рода:
http://ru.wowhead.com/quest=11595
http://ru.wowhead.com/quest=11596
http://ru.wowhead.com/quest=11597

**Как должно работать?**

Такого быть не должно.

**Шаги для воспроизведения ошибки:**

Воспроизвести наврятли получится, через раз багается. Надо смотреть по забаганным игрокам.

**Текущее обновление ядра:**

PTR Build 20 2017-04-03 15:25:08 +0400

**Comment by Riazarre** [comment]
Возможно, что баг связан со сменой фракции персонажа.
Так же, есть мнение, что персонаж мог быть созданным в то время, когда еще не были заскриптованы цепочки квестов, и можно было брать любой квест из цепочки.

**Comment by Nattpyre** [comment]
У меня один из таких персонажей. Эльф крови, маг, 70 уровень. Ник Nathyrra. Фракцию у персонажа не менял, создан он относительно недавно (в прошлом месяце).

**Comment by Kusakabe2310** [comment]
Подробно, что именно не можешь сделать, какое задание не доступно или на каком остановился...

**Comment by Nattpyre** [comment]
Не могу взять квест "Оборона крепости Песни Войны". По идее их три штуки одинаковых, просто с разными текстовками в зависимости от прошлых достижений персонажа. Пререквизит в виде "Бдение Адского Крика" выполнил, но по какой-то причине не одно из условий для этих трех одинаковых квестов не выполняется и Саурфанг квеста не дает.

**Comment by Kusakabe2310** [comment]
персонаж делал задания 
http://ru.wowhead.com/quest=7784
или
http://ru.wowhead.com/quest=8743
?

**Comment by Nattpyre** [comment]
Нет.

**Comment by Nattpyre** [comment]
Возможно я знаю, в чем может быть дело. Есть две версии квеста "Бдение Адского Крика", а именно http://ru.wowhead.com/quest=11585 и http://ru.wowhead.com/quest=11586. Первая версия для игроков, которые не делали цепочку квестов с Великой Матерью в Награнде, а вторая соответственно для тех, кто делал. Цепочка довольно муторная и подозреваю, что подавляющее большинство игроков до конца ее не делали, поэтому у них берется первый вариант квеста и дальше все нормально проходит. Я же до конца ее сделал и у меня берется второй вариант квеста и скорее всего из-за этого все забагивается. Проверьте этот вариант пожалуйста.

**Comment by ForesterDev** [comment]
Внес корректировки, после обновления проверьте и отпишите результат

**Comment by Nattpyre** [comment]
К сожалению, по-прежнему не могу взять квест. Может просто выдадите мне квест и все?

**Comment by Nattpyre** [comment]
Я конечно понимаю, что все любят красивые зелененькие таблички лепить, но баг по прежнему не исправлен.

**Comment by ForesterDev** [comment]
@Nattpyre, проверьте после рестарта сервера. Внёс дополнительные правки

**Comment by Nattpyre** [comment]
Наконец-то исправлено! Спасибо! 👍

**Comment by odino4estvo** [comment]
Добрый вечер. У меня такая же ситуация, первоначальные вышеупомянутые квесты различные НПС в Крепости Песни Войны мне не выдают. Смены фракции я не делал. Задание "Бей в Гонг" так же не делал, но "Владыку Черной Горы" я выполнял. Помогите пожалуйста. 
Скрины прикладываю, они показывают что над данными НПС квесты отсутствуют... 

![1](https://user-images.githubusercontent.com/27158518/31320741-7382b35c-ac82-11e7-8257-7ce609a0e2ab.jpg)
![2](https://user-images.githubusercontent.com/27158518/31320742-73836824-ac82-11e7-83e2-09d555ac4330.jpg)

Эльф Крофи, 79 уровень. Ник "Честность" 

"Не могу взять квест "Оборона крепости Песни Войны". По идее их три штуки одинаковых, просто с разными текстовками в зависимости от прошлых достижений персонажа. Пререквизит в виде "Бдение Адского Крика" выполнил, но по какой-то причине не одно из условий для этих трех одинаковых квестов не выполняется и Саурфанг квеста не дает."

Я кстати тоже преквест "Бдение Адского Крика" выполнил. А дальше пусто...
