### ISSUE TITLE
Задание Куда запропастился Хеминг Эрнестуэй?

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/VirginCore#110]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

[Куда запропастился Хеминг Эрнестуэй?](http://wowroad.info/?quest=12521)
Не правильно работает задание.
После взятия нужно поговорить с дающим квест и на вертолете улететь
в низину шолозар.

**Что работает не так?**

После разговора происходит анимация посадки на вертолет, но тут же с него сбрасывает.
Никакого полета не осуществляется.

**Как должно работать?**

Работало правильно раньше. Когда сломалось не знаю.
Садишься на вертолет, подлетаешь к определенной точке на площадке даларана
и портуешься в низину. там на тебя нападают ты с парашютом падаешь,
в общем красиво должно быть :)

**Шаги для воспроизведения ошибки:**

1. Взять квест
2. Поговорить с Верховный маг Пентарус
3. Убедиться что на вертолете полететь нельзя.

**Текущее обновление ядра:**

Build 153 2017-04-13 14:06:16

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
