### ISSUE TITLE
[Предмет] - Оскверненный Испепелитель

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#112]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://wowroad.info/?item=22691 и http://wowroad.info/?faction=56
При входе в монастырь алого ордена нпс должны преклонять колено, а при подходе к моргрейну вообще не воспроизводится эвент

**Что работает не так?**

http://forum.wowcircle.com/attachment.php?attachmentid=385372&d=1476633265&thumb=1
http://forum.wowcircle.com/attachment.php?attachmentid=385371&d=1476633238&thumb=1

**Как должно работать?**

ы заходим в Монастырь алого ордена и, проходя мимо мобов, эти холопы кланяются нам, проходим до босса Командира Могрейна(сына Верховного лорда Могрейна) в соборе и видим через некоторое время, как дух Верховного лорда Могрейна проходит до босса и начинается диалог... ну а дальше ясно по пруфам с оффа:
https://youtu.be/q2P87aikdoc

**Текущее обновление ядра:**

Последнее обновление ядра: Build 153 2017-04-13 14:06:16 +0400

**Comment by ForesterDev** [comment]
Исправлено, тестируйте после обновления

**Comment by Scoren** [comment]
исправлен
