### ISSUE TITLE
[Задание] ID 12538 - Шептуны не стануть слушать

### ISSUE THREAD

**Issue by Nattpyre** [VirginTeam/VirginCore#113]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Невозможно атаковать горлоков (Оракулы) в Низине Шолазар.

**Что работает не так?**

При выполнении задания столкнулся с проблемой, что невозможно атаковать мобов, необходимых для выполнения задания. Причем изначально фракция была отмечена как противник и при наведении на них была иконка меча, но атаковать я их все равно не мог, даже АОЕ. Потом я решил релогнуться и теперь их фракцию вообще нельзя даже как противника отметить.

**Как должно работать?**

Мобы должны быть доступны для убийства.

**Шаги для воспроизведения ошибки:**

1. Взять квест
2. Попытаться атаковать мобов

**Текущее обновление ядра:**

Build 153 2017-04-13 14:06:16 +0400

**Comment by Kusakabe2310** [comment]
Это общая проблема с волками и оракулами
Вот была старая тема http://forum.wowcircle.com/showthread.php?t=444441
Причина забагивания точно не известна

**Comment by Nattpyre** [comment]
Да, я читал ее. В принципе, в той теме есть подсказки в какую сторону копать, да и мой персонаж может стать подопытным для исследования причин, если нужно.

Думаю баг довольно важный, т.к. он по сути блочит огромную (10-15) цепочку квестов в Низине, а так же делает недоступным прокачку репутации с Горлоками/Волчарами.

**Comment by ForesterDev** [comment]
Напишите ник вашего персонажа, а также в репортах добавляйте ссылки на проблемных существ - это ускорит процесс обработки репортов

**Comment by Nattpyre** [comment]
Ник персонажа - Nathyrra. Собственно проблема не с какими-то конкретными мобами, а с целыми двумя фракциями - [Племя Бешенного Сердца](http://ru.wowhead.com/faction=1104#members) и [Оракулы](http://ru.wowhead.com/faction=1105#members).

Сейчас кстати глянул на вовхеде, многие даже на оффе на подобный баг после релога жаловались. Могу предположить, что после взятия/выполнения некоторых квестов срабатывает какой-то скрипт, который делает мобов атакуемыми, но после релога и/или попадания на бг/пп он перестает действовать и мобов снова нельзя атаковать. В теме на форуме пишут, что при выполнении дейлика http://ru.wowhead.com/quest=12704 мобы становятся атакуемыми, так что возможно тут как раз отрабатывает этот скрипт, но к сожалению я это проверить не могу, т.к. для получения этого квеста нужно закончить цепочку квестов, а она забагалась. По хорошему бы выполнение этого скрипта сделать при взятии этого квеста про шептунов.

**Comment by ForesterDev** [comment]
Проверьте после обновления, проблема должна быть устранена. Если что переоткроете репорт

**Comment by Scoren** [comment]
исправлен

**Comment by Nattpyre** [comment]
Подтверждаю, заработало.
