### ISSUE TITLE
[Задание] ID 8519 - Давно забытые воспоминания

### ISSUE THREAD

**Issue by Tatiann** [VirginTeam/VirginCore#115]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://wowroad.info/?quest=8519
 Нельзя выполнить квест

**Что работает не так?**

Квест заканчивает Анахронос http://wowroad.info/?quest=8303 но когда проходишь квест,его не засчитывает как выполненный 

**Как должно работать?**

Начинает хрустальная слеза  http://wowroad.info/?object=180633 и наблюдаем за мини экшеном, где нпс рассказывают историю древней войны, после чего квест должен автоматом засчитаться 
 
**Шаги для воспроизведения ошибки:**

1. Берем кв у Хрустальной слезы http://wowroad.info/?object=180633
2. Просматриваем ними экшен
3. квест должензасчитаться

**Текущее обновление ядра:**
Build 153 2017-04-13 14:06:16 +0400 wotlk logon 3 x1 pve

**Comment by ForesterDev** [comment]
Проверил, квест работает и в конце постановки засчитывается его выполнение. Возможно вы делали его в рейдовой группе, что вам не засчиталось
