### ISSUE TITLE
[Задание] ID 12910 - Найти преступника

### ISSUE THREAD

**Issue by sega693** [VirginTeam/VirginCore#116]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://wowroad.info/?quest=12910
http://ru.wowhead.com/quest=12910

**Что работает не так?**

Нельзя сесть на кошку http://wowroad.info/?npc=29857

**Как должно работать?**

Садишься на кошку и едешь к пещере
https://www.youtube.com/watch?v=0RxjPFMEG-g&feature=youtu.be

**Шаги для воспроизведения ошибки:**

1. Взять кв

**Текущее обновление ядра:**
Build 153 2017-04-13 14:06:16 +0400 
Live

**Comment by Nattpyre** [comment]
Квест блочит довольно большую цепочку, а без нее невозможно выполнить ачив.

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления

**Comment by Nattpyre** [comment]
На кошку теперь сесть можно, но квест все равно не рабочий. При высаживании с кошки в пещере не засчитывает условие "След прослежен до источника", плюс кошка не исчезает, а начинает атаковать игрока, причем отвязаться от нее очень сложно. Из-за этого вся локация заспамлена этими кошками.

Ну и еще несколько замечаний по квесту, не столь важные, но которые тоже неплохо было бы сделать.

1) Метка квеста почему-то показывает на Заброшенный лагерь, хотя туда в ордынском варианте квеста идти не нужно, это только для Альянса.
2) Не показываются следы там, где должны. Они есть только вокруг Машины Творцов, хотя должны вести до самой пещеры.
3) Абилки у кошки работают без кд, хотя кд на них есть.

В целом, работу квеста можно просмотреть в этом видео: https://www.youtube.com/watch?v=0RxjPFMEG-g

**Comment by ForesterDev** [comment]
Обновления еще не было

**Comment by Nattpyre** [comment]
После технического рестарта в субботу на кошку стало возможно сесть, поэтому я подумал, что обновление применили. Ок, жду применения.
