### ISSUE TITLE
[Арена] ID 34709 - Сумеречное зрение

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/VirginCore#117]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 34709 - Сумеречное зрение

**Что работает не так?**

а) На данный момент является бафом.
б) расположено в неверном месте на арене даларана.

**Как должно работать?**

а) Должно быть дебафом который снимается Плащ Теней(ID 31224) и подобными эффектами.
б) Должен находиться примерно в этом месте и симметрично с противоположной стороны арены.
http://www.fotohost.by/image/20ua

**Доказательства**

https://www.youtube.com/watch?v=coFWXl8WWZg - 13:33 и дальше рог берет глаз, затем жмет кош и глаз исчезает.

Это видео с официального турнирного сервера, чтобы это понять достаточно увидеть как двигаются петы, наличие задержки на дополнительные эффекты от спелов или анимацию установки портала лока.

**Текущее обновление ядра:**

18.04.2017. 153 билд

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=632925

**Comment by ForesterDev** [comment]
Исправлено, проверяйте после обновления

**Comment by Gooldark** [comment]
Работает
