### ISSUE TITLE
[Подземелье] Нижетопь (ID 18105 Газ'ан)

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#12]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Скриншоты демонстрирующие проблему, выделение проблемных мест с помощью графических редакторов приветствуются. Для описания ошибок, возникающих только в движении, снимите видео **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Газ'ан http://ru.wowhead.com/npc=18105
Кислотное дыхание - http://ru.wowhead.com/spell=34268

**Что работает не так?**

Заклинание "Кислотное дыхание" дамажит всех вокруг босса.

**Как должно работать?**

Заклинание должно бить так, как написано в описании (в конусе перед боссом).

**Текущее обновление ядра:**

PTR Build 20 2017-04-03 15:25:08 +0400

**Comment by Kodekc** [comment]
- [x] Добавлен базовый маршрут движения.
- [x] Исправлен выбор цели для применения заклинания Кислотное дыхание (ID 34268)
- [x] Откорректировано срабатывание Взбучка (ID 3391), добавлена недостающая аура Взбучка (ID 12787) для босса Газ'ан.
