### ISSUE TITLE
"Верховный Совет Бездны"

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/VirginCore#121]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
Призвать с помощью сумеречного одеяния с кольцом и медальоном верховного лорда совета.

**Что работает не так?**
При вызове одного из четырех "Верховного Совета Бездны" НИП багается, он появляется, но при этом нельзя его никак сагрить, по истечении 10 минут он исчезает... Было проверено на всех трех Великих Камнях Ветрах в Силитусе... 

**Как должно работать?**
Все просто, вызывается НИП, уже сагреный на НАС, и побеждаем его, залутав из него "Скипетр Бездны" 

**Шаги для воспроизведения ошибки:**

1. Фулл сет надет
2. Вызываем босса
3. Босс застряет на месте

**Текущее обновление ядра:**

Build 154 2017-04-20 12:48:41 +0400
![wowscrnshot_042017_182044]
![wowscrnshot_042017_182044](https://cloud.githubusercontent.com/assets/27158518/25239051/a8c40190-25f7-11e7-9d7d-100c3d14356c.jpg)

**Comment by odino4estvo** [comment]
Прошу прощение если что-то не внятно объяснил и по правилам оформил баг-репорт, на гитхабе впервые...

**Comment by Riazarre** [comment]
Добавьте ссылки в описание.
Оформите шапку согласно шаблона [Категория] ID 123 - Название репорта

**Comment by ForesterDev** [comment]
Проверите после обновления, должно быть исправлено

**Comment by zdqp** [comment]
Абсолютно такая же проблема! 

build 198 2018-04-24
