### ISSUE TITLE
[Задание] ID 13271 - Голос во тьме

### ISSUE THREAD

**Issue by Nattpyre** [VirginTeam/VirginCore#126]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Отсутствует NPC для сдачи квеста.

**Что работает не так?**

Отсутствует NPC [Матиас Нетлер](http://ru.wowhead.com/npc=31237).

**Как должно работать?**

NPC должен стоять возле портала на поверхность.

**Шаги для воспроизведения ошибки:**

1. Взять квест
2. Увидеть, что NPC нет.

**Текущее обновление ядра:**

Build 155 2017-04-20 14:36:20 +0400

**Comment by Nattpyre** [comment]
Ник Nathyrra.

**Comment by ForesterDev** [comment]
Исправлено

**Comment by Nattpyre** [comment]
Там он появился, но к сожалению теперь он не хочет появлятся после квеста [Ремонт в полевых условиях](http://ru.wowhead.com/quest=13304) и давать цепочку начинающуюся с [Все к худшему](http://ru.wowhead.com/quest=13305). Насколько я мог узнать он еще в некоторых местах появляется. Багается кстати не у меня одного, нашел еще людей, которые тоже уже довольно давно этого NPC ищут. Но видел и людей, у которых вроде все норм отрабатывало, так что сложно сказать, после чего багается, так как я почти все квесты сделал в Ледяной Короне.

**Comment by Kodekc** [comment]
https://github.com/VirginTeam/WotlkCore/issues/255
