### ISSUE TITLE
[Задание] ID 12029 - Пылающая Плеть

### ISSUE THREAD

**Issue by holicel** [VirginTeam/VirginCore#127]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Этот нпс http://wowroad.info/?npc=26604 должен дать квест http://wowroad.info/?quest=12029, но когда к нему обращаешься он не даёт, там пусто

**Что работает не так?**
Не дает квест

Фактический результат — тот, который вы наблюдаете
Пусто, квеста нет

**Как должно работать?**
Должен дать квест http://wowroad.info/?quest=12029

**Шаги для воспроизведения ошибки:**

1. Подойти
2. Попытаться взять квест
3. :(

**Текущее обновление ядра:**

Build 155 2017-04-20

**Comment by ForesterDev** [comment]
Квест доступен после сдачи http://ru.wowhead.com/quest=12484
