### ISSUE TITLE
[Предмет] ID 18649 - Схема: голубая ракета

### ISSUE THREAD

**Issue by sega693** [VirginTeam/VirginCore#129]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
http://wowroad.info/?item=18649
http://ru.wowhead.com/item=18649#english-comments

Скорее всего аналогичная проблема с http://wowroad.info/?item=18647

**Что работает не так?**
http://wowroad.info/?item=18649 привязана к фракции. при клике пишет "вы никогда не сможете использовать этот предмет"

**Как должно работать?**

Не должна быть привязана
> Kaylin 2010-07-01 (Обновление 3.3.5)
> Just was prompted to confirm this today when I saw this comment and I learned all 3 colors of schematics (blue, green, red) today, buying the horde color off the neutral auction house. You did something incorrectly, it's completely possible to get them. 
> DrakkonDarkspell 2010-07-17 (Обновление 3.3.5)
> It appears that you need to already know your factions color in order to learn to other faction's firework. Alliance need to know blue and Horde need to know red before they can learn the other. Every time I've seen this work right, the person learning it already knew the other fireworks. Blizzard may attempt to correct this in the future... 

з.ы. играю за орду, красная изучена

**Шаги для воспроизведения ошибки:**

1. приобрести схему
2. попытаться выучить 

**Текущее обновление ядра:**
Последнее обновление ядра: Build 155 2017-04-20 14:36:20 +0400 
Live

**Comment by ForesterDev** [comment]
Не достаточно доказательств.

http://www.wowhead.com/item=18647/schematic-red-firework#comments
Здесь в комментариях люди пишут, что у них после покупки на аукционе итем заменяется на другой, который подходит фракции, несмотря на то что он у них изучен.

**Comment by sega693** [comment]
> итем заменяется на другой, который подходит фракции, несмотря на то что он у них изучен.
я один обратное вижу?

http://www.wowhead.com/item=18647/schematic-red-firework#comments:id=890368:reply=133584
> Had **no problems** with learning the red firework today on my Alliance engineer. I **already knew the blue** firework if that makes a difference. 

http://ru.wowhead.com/item=18649#comments:id=1068816:reply=173468 тут 6 лайков к слову..
> It appears that you **need to already know your factions color** in order to learn to other faction's firework. Alliance need to know blue and Horde need to know red before they can learn the other. Every time I've seen this work right, the person learning it already knew the other fireworks. Blizzard may attempt to correct this in the future... 

патчи актуальные нашему, а с каты и это видимо пофиксили. Да и в любом случае проблема была в его получении, а не в изучении. Взять коммент с прекаты даже http://www.wowhead.com/item=18647/schematic-red-firework#comments:id=1177983

Ну окей.. тогда почините эту заменяемость рецепта, Или добавьте надпись как на БоЕ вещах с ИК. Я не представляю где достаточно доставерные пруфы можно найти спустя 7 лет, если эти комменты не устраивают.

**Comment by ForesterDev** [comment]
Будет добавлена фракционная привязка в следующем обновлении
