### ISSUE TITLE
[NPC] ID 2080 - Деналан

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#130]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

НПС летает по текстурам

**Что работает не так?**

Периодично сваливает со своего места позиционирования и летает по текстурам возможно после выполнения какого-то скрипта

**Как должно работать?**

НПС всегда должен возвращаться на свое местоположение

**Текущее обновление ядра:**
Последнее обновление ядра: Build 155 2017-04-20 14:36:20 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверяйте после обновления
