### ISSUE TITLE
Верхом на красной ракете

### ISSUE THREAD

**Issue by Pavlov718** [VirginTeam/VirginCore#141]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Верхом на красной ракете http://ru.wowhead.com/quest=12437
Командир Хоузер с маяка Бухты торговцев поручил вам уничтожить грузовой корабль Орды.
Командира Хоузера можно застать только тогда, когда маяк находится под контролем Альянса.

Добыть немного топлива с гоблинского корабля, который пришвартован на севере, и направить одну из торпед прямо на их грузовоз!
**Что работает не так?**

При посадке в ракету она не плывет.

**Как должно работать?**

При посадке в ракету она должна плыть. А игрок должен направить ее во вражеский корабль. После чего квест должен быть выполнен. 

**Шаги для воспроизведения ошибки:**

1. Шаг один : берем кв у этого НПС http://ru.wowhead.com/npc=27759
2. Шаг два : далее летим берем этот итем http://ru.wowhead.com/item=37664/115
3. Шаг три : держим путь к ракете, садимся в нее и ничего не происходит.

**Текущее обновление ядра:**

Build 22 2017-04-19 18:21:10 +0400
Тестовый сервер

**Comment by ForesterDev** [comment]
Исправлено, проверяйте после обновления
