### ISSUE TITLE
[Задание] ID 11314 - Падшие сестры

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#142]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

После выполнения задания кем то из игроков нпс http://ru.wowhead.com/npc=23678 не восстанавливают свой изначальный пул

**Что работает не так?**

После выполнения задания кем то из игроков нпс http://ru.wowhead.com/npc=23678 не восстанавливают свой изначальный пул

**Как должно работать?**

После выполнения задания нпс должны через некоторое время восстанавливать свой изначальный пул

**Текущее обновление ядра:**

 Build 155 2017-04-20 14:36:20 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
