### ISSUE TITLE
[Задание] ID 11653 - Ха! Не такой уж ты и большой теперь!

### ISSUE THREAD

**Issue by Niggadiay** [VirginTeam/VirginCore#143]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

При использовании квестового айтема должен вешаться дебаф "Сжатие", при убийстве НПС с этим дебафом, моб должен засчитаться в квест (+1 из 5). 

**Что работает не так?**

Квест засчитывается на +1 только при убийстве "Магмот-сокрушитель", так же дебаф появляется не с первого раза, иногда требуется использовать квестовый айтем 2-3 раза.

**Как должно работать?**

Дебаф должен появляться с первого раза, так же квест должен засчитываться на +1 при убийстве "Жена Магмотрегара", а не только при убийстве "Магмот-сокрушитель" 

**Текущее обновление ядра:**

Build 155 2017-04-20 14:36:20 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
