### ISSUE TITLE
[Задание] ID 12107 - Конец цепочки

### ISSUE THREAD

**Issue by websix1** [VirginTeam/VirginCore#146]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Невозможно убить [The End of the Line Ley Line Focus Kill Credit Bunny](http://wowroad.info/?npc=26887) для выполнения задания [Конец цепочки](http://wowroad.info/?quest=12107).

**Что работает не так?**

[The End of the Line Ley Line Focus Kill Credit Bunny](http://wowroad.info/?npc=26887) является дружественной целью. Следовательно его невозможно атаковать для выполнения задания [Конец цепочки](http://wowroad.info/?quest=12107)

**Как должно работать?**

После атаки [The End of the Line Ley Line Focus Kill Credit Bunny](http://wowroad.info/?npc=26887) должно засчитывать выполнение первой части задания [Конец цепочки](http://wowroad.info/?quest=12107)

**Шаги для воспроизведения ошибки:**

1. Берем задание [Конец цепочки](http://wowroad.info/?quest=12107) у [Маг-командир Холодная Звезда](http://wowroad.info/?npc=26873)
2. Убиваем [The End of the Line Ley Line Focus Kill Credit Bunny](http://wowroad.info/?npc=26887) под водой на координатах 40.0 67.5

**Текущее обновление ядра:**

Live server Build 155 2017-04-20 14:36:20 +0400

**Comment by Ewropa** [comment]
дубль https://github.com/VirginTeam/VirginCore/issues/155
