### ISSUE TITLE
[Заклинание] ID 48066 - Слово силы: Щит; ID 58597 - Священный щит

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/VirginCore#148]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Репорт касается только этих двух спелов

ID 48066 - Слово силы: Щит; ID 58597 - Священный щит

**Что работает не так?**

В зонах, где нет среза хила на аренах, отсутствует невидимый модификатор который увеличивает количество абсорба на 30%.

**Как должно работать?**

В зонах, где нет среза хила на аренах, должен быть невидимый модификатор который увеличивает количество абсорба для этих спелов на 30%.

Данный модификатор заменяется на срез хила на аренах, и заменяет баф цлк при их наличии.

Таким образом вне арены( в любой локации или цлк) формула расчета абсорба для ID 48066 - Слово силы: Щит становиться:
( 2230 + спд * ( 0,807 + 0,4 )) * ( 1,15 + 0,05 ) * 1,05 * 1,04 * 1,3
где 0,4 - ID 52800 - Лишнее время; 1,15 - ID 14769 - Улучшенное слово силы: Щит; 0,05 - ID 70798 - Item - Priest T10 Healer 4P Bonus; 1,05 - ID 52803 - Двоевластие; 1,04 - ID 33190 - Средоточие силы; 1,3 - невидимый модификатор.
Для арены формула такая:
( 2230 + спд * ( 0,807 + 0,4 )) * ( 1,15 + 0,05 ) * 1,05 * 1,04 * 0,9
где 0,9 - срез хила на аренах.

Вне арены( в любой локации или цлк) формула расчета абсорба для ID 58597 - Священный щит становиться:
( 500 + спд * 0,75 ) * 1,2 * 1,3
где 1,2 - ID 53530 - Божественный страж; 1,3 - невидимый модификатор.
Для арены формула такая:
( 500 + спд * 0,75 ) * 1,2 * 0,9
где 0,9 - срез хила на аренах.

**Текущее обновление ядра:**

29.04.2017. 155 билд

**Доказательства**

http://forum.wowcircle.com/showthread.php?t=640591 - под спойлерами довольно много пруфов.

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления

**Comment by Gooldark** [comment]
Проверил это, есть ошибка.

Этот баф перестает действовать если вкачать талант ID 33190 - Средоточие силы. Хотя должен исчезать только при наличии бафа арены и бафа цлк. 
Насколько я понимаю сейчас этот баф исчезает если на присте появляется ауры модифицирующие исходящее исцеление, по идее на присте из таких аур может быть только ID 33190 - Средоточие силы(возможно овер в каст вара). Неплохо бы исправить этот момент.
