### ISSUE TITLE
[Задание] ID 4121 - Опасное положение

### ISSUE THREAD

**Issue by Napoliash** [VirginTeam/VirginCore#151]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

делал квест http://wowroad.info/?quest=4121 "Опасное положение" и так получилось что провалил, отменив квест и взяв по новой, понял что лишился итема http://ru.wowhead.com/item=11286 "Ториевые оковы".
Судя по информации на вовхед итем должен выдать нпс http://wowroad.info/?npc=9080 "Лекслорт"
но на моем 53 лвл у него только светится белый восклицательный знак и разговаривать он со мной напрочь отказывается!

**Что работает не так?**

невозможно получить "Ториевые оковы" повторно после потери или отмены квеста "Опасное положение"

**Как должно работать?**

при потери предмета можно взять в у Лекслорта через диалог если я все правильно понял

**Шаги для воспроизведения ошибки:**

1. победил Грарк Лоркруба
2. вывел из здания и умер, автоматически провалил задание
3. отмена задания, потеря предмета, как следствие не возможность выполнить квест

**Текущее обновление ядра:**
Build 155 2017-04-20 14:36:20 +0400

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by ForesterDev** [comment]
Исправлено, будет применено после ребута
