### ISSUE TITLE
[Задание] id 10857 - Телепортируй это!

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#152]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
http://ru.wowhead.com/quest=10857
Не срабатывает использование спелла http://ru.wowhead.com/spell=38920 подчиняемого нпс http://ru.wowhead.com/npc=20928

**Что работает не так?**

При использовании http://ru.wowhead.com/spell=38920 на портал легиона портал взрывается только визуально, фактически задание не засчитывает
**Как должно работать?**

Задание должно засчитываться при использовании http://ru.wowhead.com/spell=38920 на порталы легиона

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by ForesterDev** [comment]
Исправлено, будет применено после перезагрузки
