### ISSUE TITLE
[Задание] ID 10943 - Детская неделя

### ISSUE THREAD

**Issue by maxmc777** [VirginTeam/VirginCore#153]
Вот моя старая тема http://forum.wowcircle.com/showthread.php?t=558481

**Описание:**

Квест Детская неделя http://ru.wowhead.com/quest=10943 недоступен, если уже делал цепочку в прошлом году.

**Что работает не так?**

Попечительница сирот Мила http://ru.wowhead.com/npc=22819 не даёт квест.

**Как должно работать?**

Попечительница сирот Мила http://ru.wowhead.com/npc=22819 должна давать квест каждый год.

**Шаги для воспроизведения ошибки:**

1. Идёшь в Шатрат
2. Не видишь квеста
3. Сиротка тоже не даёт квест никакой

**Текущее обновление ядра:**

Build 155 2017-04-20, logon3 x1 pve, персонаж Эмсишка.

**Comment by ForesterDev** [comment]
Исправлено
