### ISSUE TITLE
[Игровая механика] Такси (Восточные Чумные Земли <--> Призрачные земли)

### ISSUE THREAD

**Issue by Napoliash** [VirginTeam/VirginCore#154]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Оплатив перелет до луносвета обнаружил, что долететь из пункта "а" в пункт "б" невозможно 

**Что работает не так?**

При перелете из транквиллиона в часовню последней надежды и обратно, при смене локации сбрасывает с птички
https://youtu.be/yja0MRcLb5E

**Как должно работать?**

перелететь через портал и ожидать приземления в месте назначения

**Шаги для воспроизведения ошибки:**

1. Оплатить перелет где угодно, но так чтоб путь лежал через портал смены локации чумные земли\леса вечной песни

**Текущее обновление ядра:**
Build 155 2017-04-20, logon3 x1

**Comment by Riazarre** [comment]
Подтверждаю

**Comment by ForesterDev** [comment]
Исправлено, будет применено при обновлении
