### ISSUE TITLE
[Задание] ID 12107/12110 - Конец цепочки

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#155]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)
**Описание**

Альянс - http://ru.wowhead.com/quest=12107
Орда - http://ru.wowhead.com/quest=12110

**Что работает не так?**

Не засчитывается использование квестового предмета в нужной точке. Каст проходит - квест не засчитывается.
Орда: https://youtu.be/7K8NozKfDMk
Альянс: https://youtu.be/RV_tM8TF848
update: http://wowroad.info/?npc=26887 стал видимым.

**Как должно работать?**

Должен работать правильно.
update: http://wowroad.info/?npc=26887 не должен быть виден игрокам.

**Текущее обновление ядра:**

PTR: Build 24 2017-05-01 18:08:06 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено после ребута сервера
