### ISSUE TITLE
[Задание] ID 12084/12083 - В лесах

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#156]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://ru.wowhead.com/quest=12084 - орда
http://ru.wowhead.com/quest=12083 - альянс

**Что работает не так?**

Не засчитывается использование квествого предмета http://ru.wowhead.com/item=36779 под аркой

**Как должно работать?**

После использования http://ru.wowhead.com/item=36779 под аркой задание должно засчитываться
https://youtu.be/_59taMErnSs

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено после перезагрузки сервера
