### ISSUE TITLE
[Задание] id 12721 - Буйство

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#157]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
http://ru.wowhead.com/quest=12721
Не запускается ивент. По всей видимости вообще нет сриптов. Задание не засчитывается.

**Что работает не так?**

После открытия всех четырех замков не запускается ивент с акали (оставшиеся не убитые игроком http://ru.wowhead.com/npc=28988) не атакуют акали после его освобождения. http://ru.wowhead.com/npc=28952 не атакует усмиритель акали в свою очередь.

**Как должно работать?**
После использования на последнем замке ключа, задание должно засчитываться, Усмирители акали должны на него нападать, он же в свою очередь должен нападать на усмирителей акали. Ну и после убийства всех должен восстанавливать свой пул.
https://youtu.be/cfKUxE8xFAw

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by Ewropa** [comment]
Задание работало, криво, но работало, что-то отвалилось по всей видимости...

**Comment by ForesterDev** [comment]
Исправлено, будет применено после перезагрузки сервера
