### ISSUE TITLE
[Предмет] ID 11815 - Рука правосудия

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#158]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Непонятен шанс прока с триньки

**Что работает не так?**

Подозрение на низкий шанс прока http://ru.wowhead.com/spell=15600
Подозрение, что спелл не повторяет способности атакующего.

**Как должно работать?**

Прок может сдублировать как автоатаку, так и атакующие способности, что подтверждается как комментариями на вовхед (скриншот рекаунта с оффа http://oi39.tinypic.com/2i8x568.jpg)
Шанс прока (по информации с английский комментариев вовхеда) следующий:

> Level 60 (& before): 2.00%
> Level 63: 1.80%
> Level 65: 1.67%
> Level 67: 1.54%
> Level 69: 1.40%
> Level 70: 1.33%
> Level 71: 1.27%
> Level 73: 1.13%
> Level 75: 1.00%
> Level 77: 0.87%
> Level 79: 0.73%
> Level 80: 0.67%

**Текущее обновление ядра:**

PTR: Build 24 2017-05-01 18:08:06 +0400

**Comment by Riazarre** [comment]
10 минут боя с быстрым оружием: http://joxi.ru/12MYXQEuM1dYe2
23 минуты боя с медленным оружием: http://joxi.ru/823x0j6IJ3QykA

**Comment by ForesterDev** [comment]
Исправлено, будет применено после перезагрузки сервера
