### ISSUE TITLE
[Группа заданий] Амфитеатр страданий

### ISSUE THREAD

**Issue by Napoliash** [VirginTeam/VirginCore#159]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

поступили жалобы от согильдийцев что не могут выполнить цепочку квестов "амфитеатр страданий" в зул драке, проверил на тест реалме, столкнулся с тем же на что жаловались!
проверки ради, перезашел в игру, без изменений...

**Что работает не так?**

невозможно получить следующий квест после завершения "амфитеатр страданий: иггдрас!"
https://youtu.be/CT5NiGtjmTU

**Как должно работать?**

по завершению квеста, продолжение цепочки

**Шаги для воспроизведения ошибки:**

1. просто начать делать цепочку

**Текущее обновление ядра:**

Build 24 2017-05-01 18:08:06
Public Test Realm

**Comment by Riazarre** [comment]
Подтверждаю, квест http://ru.wowhead.com/quest=12933 не выдается после завершения предыдущего квеста (http://ru.wowhead.com/quest=12932)

**Comment by ForesterDev** [comment]
Исправлено, будет применено при перезагрузке сервера
