### ISSUE TITLE
[Задание] ID 8966 - Левая часть амулета Лорда Вальтхалака

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#160]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

При использовании квеститема 22049 появляется НПЦ 16080. НПЦ не атакуется (ошибка Цель вне поля зрения), можно задеть его АоЕ.

**Как должно работать?**

НПЦ можно атаковать и убить.

**Текущее обновление ядра:**

PTR:  Build 24 2017-05-01 18:08:06 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено после ребута
