### ISSUE TITLE
[Задание] id 8196 - Экстракт манго

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#161]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Отсутствует задание http://wowroad.info/?quest=8196 у нпс http://wowroad.info/?npc=14921 при наличии нужной репутации

**Что работает не так?**

После выполнения задания http://wowroad.info/?quest=8243 следующий по цепочке квест http://wowroad.info/?quest=8196 не выдается НПС на любом уровне репутации
**Как должно работать?**

Задание http://wowroad.info/?quest=8196 должно быть следующим после http://wowroad.info/?quest=8243 и выдаваться при репутации племени сандалар (id 270) Почтение

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено после рестарта
