### ISSUE TITLE
[Заклинание] ID 54646 - Магическая концентрация

### ISSUE THREAD

**Issue by holicel** [VirginTeam/VirginCore#162]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
Я Друид в сете Наряд Малфуриона, 4 штуки, он дает некоторую вероятность того что моё заклинание омоложение кританёт. Так вот когда маг вешает на меня магическую концентрацию, и моё омоложение критует, то магу не прокает эффект от магической концентрации.

Добавьте описание проблемы здесь.

**Что работает не так?**
не прокает магическая концентрация магу

Фактический результат — тот, который вы наблюдаете
не прокает магическая концентрация магу

**Как должно работать?**

при моём крите омоложения должен вешаться крит магу от магической концентрации

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Друидом одеть сет "Наряд Малфуриона"
2. Магом кинуть магическую концентрацию на друида
3. Друидом кинуть омоложение, на себя
4. Ждать пока омоложение кританёт, и посмотреть что эффект магу не повесился

**Текущее обновление ядра:**

Build 157

**Comment by Riazarre** [comment]
бонус 4Т9 - http://wowroad.info/?spell=67128

**Comment by holicel** [comment]
А почему не должна прокать, там же не написано что не должна, точно так можно написать дайте пруф что не должна работать от дот, хот. Там же написано "Если его заклинание имеет критический эффект, вероятность критического эффекта ваших заклинаний также повышается на 3%"
Моё заклинание имеет крит - да, всё сходится

**Comment by Riazarre** [comment]
В WoW не все так прямо и логично, в качестве примера приводить тултип заклинания - некорректно.
