### ISSUE TITLE
[Задание] id 1530 - Зов воды

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#163]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Обрывается цепочка на тотем Воды у Тауренов

**Что работает не так?**

Отсутствует задание http://wowroad.info/?quest=1530 у http://wowroad.info/?npc=5901

**Как должно работать?**

После выполнения http://wowroad.info/?quest=1528 у нпс http://wowroad.info/?npc=5901 должен выдаваться квест http://wowroad.info/?quest=1530 В остальном цепочка исправна.

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
