### ISSUE TITLE
[Существа] ID 30190 - Рабочий Ток

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#165]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Летает в небе НПС http://ru.wowhead.com/npc=30190

**Что работает не так?**

Летает в небе по неведовым причинам

**Как должно работать?**

Должен стоять в зоне Мастерская мимира

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by Riazarre** [comment]
Кто-то его багом/читом загоняет туда.

**Comment by Devinette** [comment]
После того, как игрок сдаёт ему квест, запускается ивент, появляются фразы от него в чате и он благополучно улетает с ящиков через текстуры в небо

**Comment by Riazarre** [comment]
Задание 12980 из-за этого нельзя выполнить.

**Comment by Riazarre** [comment]
Исправлено, будет применено после обновления.

**Comment by Riazarre** [comment]
Не исправлено, проблема сохраняется. #540
