### ISSUE TITLE
[Заклинание] ID 66115 - Длань свободы

### ISSUE THREAD

**Issue by Stivven** [VirginTeam/VirginCore#166]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Добавьте описание проблемы здесь.
id 66115 - Длань свободы - Делает союзника невосприимчивым к затрудняющим передвижение эффектам на 10 sec. На персонажа единовременно может действовать только одно заклинание категории "Длань" от каждого паладина.

**Что работает не так?**

Длань свободы не юзается в сапе(разбойника)

**Как должно работать?**

Если паладину дают сап,он может в сапе юзать Длань свободы,то есть если палу дают сап,находясь в контроле он должен давать напарнику по команде Длань свободы,у нас его на данный момент нельзя нажимать.
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
https://www.youtube.com/watch?v=pS_1d7X2GHM&feature=youtu.be&t=309  видео,подтверждающее что Длань свободы юзается в сапе,начинать смотреть с 5:07 ,паладин в сапе,при этом даёт шаману длань свободы

**Шаги для воспроизведения ошибки:**

1.  id 6770 - ошеломление , паладину дают ошеломление
2. находясь в контроле юзнуть Длань свободы на напарника
3. Если же рога открылся на его напарнике,паладина,при любом стане он выходит с контроля(стана)и дальше двигается

**Comment by Riazarre** [comment]
Оформите как полагается, шаблон оформления у Вас перед глазами.

**Comment by Riazarre** [comment]
Нашел интересное видео, паладин дает на себя Длань, через ~секунду спадает сап.
https://youtu.be/efzGzctpjfQ?t=80

**Comment by ForesterDev** [comment]
Исправлено, проверите после обновления

**Comment by Gooldark** [comment]
Работает
