### ISSUE TITLE
Дуэль зона

### ISSUE THREAD

**Issue by Executorr** [VirginTeam/VirginCore#168]
Дуэль зона

Ку,когда вы уже исправите баг в кратере(дуэль зона) при отчете дуэли пропадает цель и фокус!играя за вара,чаржи в петов и тотемы  не найс делать(держу в цели к примеру шамана отчет 3,2,1  цель пропала ЧАРЖ в тотем!  сделайте сброс КД не после дуэли а при отчете!просто не удобно когда начинаешь дуэль с КД.

https://www.youtube.com/watch?v=fI0RcqtbFDI
https://www.youtube.com/watch?v=Nslab-ZeaH0

надеюсь вы это исправите!скок существует дуэль зона а до сих пор не исправили!

**Comment by ForesterDev** [comment]
Это баг-трекер проекта logon3 wotlk. У нас нет таких багов, что вы описали.
