### ISSUE TITLE
[Задание] id 12328 - Просьба Рууны

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#169]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://ru.wowhead.com/npc=27581 не выдает квест http://ru.wowhead.com/quest=12328
аналогично для орды

**Что работает не так?**

http://ru.wowhead.com/npc=27581 не выдает квест http://ru.wowhead.com/quest=12328
аналогично для орды при выполненном преквесте http://ru.wowhead.com/quest=12425 и альянса http://ru.wowhead.com/quest=12161

**Как должно работать?**

http://ru.wowhead.com/npc=27581 Должна выдавать задание http://ru.wowhead.com/quest=12328 при выполненном преквесте http://ru.wowhead.com/quest=12425 у орды и http://ru.wowhead.com/quest=12161 у альянса

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
