### ISSUE TITLE
[Рейд] Обсидиановое святилище (ID 31103 Twilight Egg (Cosmetic))

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#17]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Скриншоты демонстрирующие проблему, выделение проблемных мест с помощью графических редакторов приветствуются. Для описания ошибок, возникающих только в движении, снимите видео **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Twilight Egg (Cosmetic) - http://wowroad.info/?npc=31103
`[12:33:50] Player selected NPC`
`[12:33:50] DB GUID: 90228, current GUID: 3791660.`
`[12:33:50] Faction: 14.`
`[12:33:50] npcFlags: 0.`
`[12:33:50] Entry: 31103.`

**Что работает не так?**

Яйца агрятся и бьют игрока, вешают бой.
`4/5 12:30:00.596  SWING_DAMAGE,0xF13000797F39DB2C,"Twilight Egg (Cosmetic)",0xa48,0x0000000000452F2B,"Мертваядама",0x511,322,0,1,0,0,0,nil,nil,nil`
`14/5 12:30:00.596  SWING_MISSED,0xF13000797F39DB2B,"Twilight Egg (Cosmetic)",0xa48,0x0000000000452F2B,"Мертваядама",0x511,DODGE`
`4/5 12:30:00.596  SWING_DAMAGE,0xF13000797F39DB2A,"Twilight Egg (Cosmetic)",0xa48,0x0000000000452F2B,"Мертваядама",0x511,350,0,1,0,0,0,nil,nil,nil`

**Как должно работать?**

Яйца не должны агриться.

**Шаги для воспроизведения ошибки:**

Подойти к яйцу

**Текущее обновление ядра:**

`PTR Build 20 2017-04-03 15:25:08 +0400`

**Comment by Kodekc** [comment]
Будет исправлено в ближайшем обновлении
