### ISSUE TITLE
[Задание] id 1524 - Зов Огня

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#170]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

НПС не выдает задание Зов огня после выполнения преквеста

**Что работает не так?**

http://wowroad.info/?npc=5907 не выдает задание http://wowroad.info/?quest=1524 после выполнения одного из преквестов http://wowroad.info/?quest=2984 или http://wowroad.info/?quest=1523

**Как должно работать?**

http://wowroad.info/?npc=5907 должен выдавать задание http://wowroad.info/?quest=1524 после выполнения одного из преквестов http://wowroad.info/?quest=2984 или http://wowroad.info/?quest=1523

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено после ребута

**Comment by Riazarre** [comment]
На PTR не работает
Дополнение к репорту (из конфы) 
> квест 1523 доступен у нпц 3032, а квест 2984 - у нпц 3066
Сейчас оба квеста у нпц 3066

**Comment by ForesterDev** [comment]
Исправлено
