### ISSUE TITLE
[Предмет] ID 11828 - Схема: крошечная ходячая бомба

### ISSUE THREAD

**Issue by Draudem** [VirginTeam/VirginCore#171]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не падает схема с анжинера термоштепселя.

**Как должно работать?**

На вовхеде пишут, что схема падает с него инженеру с почти 100% вероятностью. На патче 3.1 рец уже падает. Я убил его уже раз 20.

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
