### ISSUE TITLE
[Заклинание] ID 25899 - Великое благословение неприкосновенности.

### ISSUE THREAD

**Issue by Draudem** [VirginTeam/VirginCore#177]
![wowscrnshot_050917_112700](https://cloud.githubusercontent.com/assets/28508335/25902962/7c0da562-35b4-11e7-87c1-2b9c885ec169.jpg)
![wowscrnshot_050917_112719](https://cloud.githubusercontent.com/assets/28508335/25902963/7c0e4350-35b4-11e7-9807-3e409911f684.jpg)

[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не дается мана от бафа, если носитель бафа не состоит в пати или рейде с тем, кто этот баф наложил. При этом при увороте/блоке/парировании в журнале боя пишется "Заклинание благословение неприкосновенности не достигает Draudem".

Как видно из скриншотов, мана не давалась, пока я не обновил чужой баф (а он был чужой, поверьте).

**Как должно работать?**

Баф должен давать ману при каждом увороте/блоке/парировании независимо от того, состоишь ты в пати с тем, кто наложил баф или нет.

**Шаги для воспроизведения ошибки:**

1. Вступить в пати с паладином.
2. Принять от него баф.
3. Выйти из пати.
4. Увидеть, что мана не восполняется.

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by Riazarre** [comment]
Проблема не в группе.
Пока наложивший заклинание находится на этом же континенте, что и получивший - мана восполняется. Стоит сменить континент, зайти в подземелье, или выйти из мира - восполнение маны прекращается с указанным в репорте сообщением.

**Comment by ForesterDev** [comment]
Не баг, подобное ограничение распространяется на все подобные спеллы
