### ISSUE TITLE
[Задание] id 6073  - Путь охотника

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#179]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Если ночной эльф возьмет задание http://wowroad.info/?quest=6073 в штормграде у нпс http://wowroad.info/?npc=5515 то он не сможет получить продолжение цепочки у нпс http://wowroad.info/?npc=3601 последующий квест http://wowroad.info/?quest=6063

**Что работает не так?**

Если ночной эльф возьмет задание http://wowroad.info/?quest=6073 в штормграде у нпс http://wowroad.info/?npc=5515 то он не сможет получить продолжение цепочки у нпс http://wowroad.info/?npc=3601 последующий квест http://wowroad.info/?quest=6063

**Как должно работать?**

Если ночной эльф возьмет задание http://wowroad.info/?quest=6073 в штормграде у нпс http://wowroad.info/?npc=5515 то он может получить продолжение цепочки у нпс http://wowroad.info/?npc=3601 последующий квест http://wowroad.info/?quest=6063

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено после обновления
