### ISSUE TITLE
[Задание] id 6076 - Путь охотника

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#180]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

если дворф охотник возьмет задание http://wowroad.info/?quest=6076 у http://wowroad.info/?npc=5515 то по пришествию к http://wowroad.info/?npc=1231  он не получит продолжения цепочки а именно http://wowroad.info/?quest=6064
**Что работает не так?**

если дворф охотник возьмет задание http://wowroad.info/?quest=6076 у http://wowroad.info/?npc=5515 то по пришествию к http://wowroad.info/?npc=1231  он не получит продолжения цепочки а именно http://wowroad.info/?quest=6064

**Как должно работать?**

После того как получен квест http://wowroad.info/?quest=6076 дворфом охотником у http://wowroad.info/?npc=5515 последующий квест должен быть у http://wowroad.info/?npc=1231 а именно http://wowroad.info/?quest=6064

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено после обновления
