### ISSUE TITLE
Вудуистские перья

### ISSUE THREAD

**Issue by murdalak** [VirginTeam/VirginCore#181]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не работают классовые квесты воина и паладина, в которых нужно собрать перья с боссов-троллей затонувшего храма, для воина квест называется "Вудуистские перья", для паладина "Создание камня силы"

**Что работает не так?**

С троллей не падают перья (квестовый итем)

**Как должно работать?**

С троллей должен падать лут не только в виде вещей, но и перья для квеста

**Шаги для воспроизведения ошибки:**

1. Заходим в подземелье Затонувший храм
2. Убиваем защитников Атал'ая (Ранокол, Лоро, Хукку, Золо, Миджан и Зул'Лор)
3. Лутаем каждого босса и не находим перьев

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by Riazarre** [comment]
Перья падают
http://joxi.ru/KAxoy5xTM6Z0J2
Работает верно, отклонено.

**Comment by 2dull2die** [comment]
Шанс дропа пера с любого из боссов - 25%, просто не повезло, я сам на эти перья репорт почти написал)
