### ISSUE TITLE
[Задание] id 12274 - Греховное падение

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#182]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

После использования колокола стражи около нпс http://ru.wowhead.com/npc=27245 уходят а сам нпс после диалога с ним не выходит из церкви и не следует по маршруту за монастырь где его мы должны убить.

**Что работает не так?**

После использования колокола стражи около нпс http://ru.wowhead.com/npc=27245 уходят а сам нпс после диалога с ним не выходит из церкви и не следует по маршруту за монастырь где его мы должны убить.

**Как должно работать?**

После использования колокола стражи около нпс http://ru.wowhead.com/npc=27245 уходят а сам нпс после диалога с ним не выходит из церкви и не следует по маршруту за монастырь где его мы должны убить.

После использования колокола стражи около нпс http://ru.wowhead.com/npc=27245 уходят а сам нпс после диалога с ним должен следовать на выход из монастыря и выходит за пределы крепости алого натиска, где мы после небольшого ивентика можем его убить
Квест сломался после последнего обновления

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
