### ISSUE TITLE
[Заклинание] ID 49206 - Призыв горгульи

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/VirginCore#183]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 49206 - Призыв горгульи
Горгулья атакует цель с воздуха и забрасывает противника бомбами, мощность которых зависит от силы атаки рыцаря смерти. Бомбы наносят урон от сил Природы. Время действия – 30 sec.

**Что работает не так?**

Горгулья кастует бомбы и передвигается одновременно

**Как должно работать?**

Когда горгулья кастует она не должна иметь возможность двигаться.

**Текущее обновление ядра:**

13.05.2017. 
Скорее всего баг появился после частичного фикса https://github.com/VirginTeam/VirginCore/issues/135

**Comment by ForesterDev** [comment]
Исправлено
