### ISSUE TITLE
[Группа заданий] id 8968/8991 - Левая часть амулета Лорда Вальтхалака/Правая часть амулета Лорда Вальтхалака

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#184]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не исправный ивент с призывом http://wowroad.info/?npc=16101http://wowroad.info/?npc=16102 нпс нельзя атаковать

**Что работает не так?**

Не исправный ивент с призывом http://wowroad.info/?npc=16101http://wowroad.info/?npc=16102 нпс нельзя атаковать. Просто стоят и все

**Как должно работать?**
НПС должны быть после призыва нейтральными, а не враждебными. Это первое
Второе, их можно атаковать
Третье, после смерти одного из них призываются такие же, но союзные нпс http://wowroad.info/?npc=16104 или же http://wowroad.info/?npc=16103 которые помогают в убийстве второго, второй тем временем впадает в берсерк http://www.wowhead.com/spell=27650

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Работает
