### ISSUE TITLE
[Объекты] id 194541 - Гарпунная пушка

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#185]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не корректное расположение пушек (не туда повернуты)

**Что работает не так?**
Не корректное расположение пушек (не туда повернуты)
https://pp.userapi.com/c637428/v637428153/6b2ba/jh9UEgSqed4.jpg

**Как должно работать?**

Пушки должны быть повернуты в сторону острокрылой
http://wow.zamimg.com/uploads/screenshots/normal/304714-гарпунная-пушка.jpg

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by Kodekc** [comment]
Объекты, после призыва, устанавливают таргер в зависимости от расположения босса.
