### ISSUE TITLE
[Задание] ID 11665 - Кроколиски в городе

### ISSUE THREAD

**Issue by Draudem** [VirginTeam/VirginCore#193]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

В награду не дают ведро со смердыхом.

**Что работает не так?**

Если верить данным о луте на вовхеде, шанс получить каждого пета примерно одинаков. С каждого дейлика обязательно падает какой-то пет. Значит получить какого-то определенного пета с одного дейлика равен 0,25, а шанс его не получить равен 0,75. Этот дейлик я точно делал минимум 20 раз (именно этот, другие дейлики от этого нпс я не считаю). Шанс того, что за 20 дейликов я не получу ведро со смердыхом равен 0,75^20=0,003. Меньше 1%. И тем не менее, я его еще не получил. Значит либо он у вас вообще не падает, либо его лутрейт неправилен.

**Как должно работать?**

Ведро со смердыхом должно падать с вероятностью 0,25.

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by Riazarre** [comment]
Во-первых: предполагаемая проблема не в задании, а в дропе с сумки http://ru.wowhead.com/item=35348
Во-вторых: отклонено, выпало с первого же раза:
http://joxi.ru/L21zMjQI8Wg6PA
Вам просто не повезло, вы могли получать пета все двадцать раз, либо не получить ни разу.

**Comment by Draudem** [comment]
Ну согласитесь, если у меня с 20 сумок не упал смердых (хотя вероятность этого, как я показал на основании **школьного** теорвера, минимальна), то это не "не повезло", а у меня с этим квестом что-то не так.
Мне так еще про цепочку квестов у зиморожденных скорен сказал, что она работает. Хотя у меня и у некоторых других людей она не бралась, несмотря на то, что бралась у всех остальных.

**Comment by Riazarre** [comment]
Хорошо, допустим, что вовхед - единственно верная база данных.

[Ведро Ворчуна](http://ru.wowhead.com/item=35349) - шанс дропа 11%
[Ведро Проглота](http://ru.wowhead.com/item=35350) - шанс дропа 11%
[Ведро с Зубастиком](http://ru.wowhead.com/item=33816) - шанс дропа 11%
[Ведро со смердыхом](http://ru.wowhead.com/item=33818) - шанс дропа 11%

А теперь посмотрим в базе Wowroad.info
[Ведро Ворчуна](http://wowroad.info/?item=35349) - шанс дропа 15%
[Ведро Проглота](http://wowroad.info/?item=35350) - шанс дропа 15%
[Ведро с Зубастиком](http://wowroad.info/?item=33816) - шанс дропа 15%
[Ведро со смердыхом](http://wowroad.info/?item=33818) - шанс дропа 15%

Проанализируем комментарии каждого пета на вовхед:
Ведро Ворчуна (правда 5.0.4, но человек тоже пишет о проблеме получения):
> От Montarum (3,257 – 3·10) 2012-08-29 (Обновление 5.0.4)		
> Полтора года уже делаю квесты на рыбалку в Аутлендах, три других крокодильчика давно уже выпали, а это все никак не дается, упрямый...
> Каждый раз когда у Старины Барло выпадает квест Кроколиски в городе - с надеждой вглядываюсь в лут с сумки. 
> Но рандом он такой рандом...

Ведро Проглота

> От RinSun (1,413 – 2·13) 2009-08-15 (Обновление 3.1.3)		
> Выпал примерно на 20м-30м дейлике(общая сумма всех 4х выполняемых) с дейлика *Кроколиски в городе*. Была приятно удивлена)
> [Някистоецуко - Король-Лич]

Ведро с Зубастиком

> От markoska (2,816 – 12·31) 2009-06-20 (Обновление 3.1.3)		
> Уже очень долго делаю эти дейлики. месяца 4 точно. за все время попались 3 пета и все одинаковые.... Смердыхи. Пришлось повыкидывать. Продолжаю надеяться)))

> От Tanitriel (558 – 7) 2009-05-06 (Обновление 3.1.1)		
> Симпатичный кродольчик, выловился из сумки через месяц каждодневных квестов для этого рыбака возле Шаттраха, пока делала эти квесты заметила тенденцию - оба крокодильчика (Зубастик и Смердых) из сумочки выпали мне после квестов на рыбалку в Награнде.

Ведро со смердыхом

> От DEMOnikRUS (6,393 – 1·21·62) 2010-05-04 (Обновление 3.3.3)		
> Я уже около пол года делаю этот делик каждый день, все кроколиски попадались, но он упорно не хочет дропаться. Причем другие Попались буквально в читаные дни, а этот не в какую.

Исходя из всего этого - у нас все работает корректно.

**Comment by ForesterDev** [comment]
Привожу выборку с шансом дропа предметов с сумки:

```
 Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment  
------  ------  ---------  ------  -------------  --------  -------  --------  --------  ---------
 35348   22578      22578     100              0         1        0         1         2  (NULL)   
 35348   33816          0      15              0         1        2         1         1  (NULL)   
 35348   33818          0      15              0         1        2         1         1  (NULL)   
 35348   34109          0       5              0         1        0         1         1  (NULL)   
 35348   35349          0      15              0         1        2         1         1  (NULL)   
 35348   35350          0      15              0         1        2         1         1  (NULL)   

```

Как видите, у всех ведер одинаковый шанс. Просто не везет. Отклонено
