### ISSUE TITLE
[Рейды] id 2947/2948 Вы оглушены и не можете этого сделать…

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#195]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

После срыва всех кастов достижение не засчитывается https://youtu.be/3QjANaVmpO4

**Что работает не так?**

После срыва всех кастов достижение не засчитывается https://youtu.be/3QjANaVmpO4
**Как должно работать?**

После срыва всех кастов достижение должно засчитываться https://youtu.be/hX5ieht0Vd8

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by Devinette** [comment]
Работает
