### ISSUE TITLE
[Задание] Id 1688 - Сурена Каледон

### ISSUE THREAD

**Issue by ZeVeRuS** [VirginTeam/VirginCore#198]
**Описание:**

Не работает цепочка классовых квестов за чернокнижника (гнома)

**Что работает не так?**

После сдачи квеста "Забитый Ягненок" http://ru.wowhead.com/quest=1715 Гакин Темнопряд, не выдает следующий квест в цепочке, в связи с чем, не возможно получить призыв демона бездны.

**Как должно работать?**

После сдачи квеста "Забитый Ягненок" http://ru.wowhead.com/quest=1715, Гакин Темнопряд, должен выдавать следующий квест в цепочке "Сурена Каледон" http://ru.wowhead.com/quest=1688

**Шаги для воспроизведения ошибки:**

1. Взять квест Таверна "Забитый ягненок" http://ru.wowhead.com/quest=1715 
2. Сдать его в Штормграде Гакину Темнопряду
3. У Гакина больше нет доступных заданий

**Текущее обновление ядра:**
Последнее обновление ядра: Build 157 2017-05-02 14:02:07 +0400
logon3 wowcircle.com Сервер wowcircle x1 pve virgin

**Comment by Riazarre** [comment]
Подтверждаю
http://joxi.ru/MAjoWMQT48xjdr

**Comment by ZeVeRuS** [comment]
Жду исправления

**Comment by Estatelol** [comment]
Присоединяюсь. Гейм мастер в игре  раза ответил про полную работоспособность квестов. Из-за этого товарища после каждого уровня в течении трех дней пробегаю трех НПС связанных с этой цепочкой. Исправьте пожалуйста.

**Comment by Scoren** [comment]
Пока можете сделать демона с цепочки в Златоземье http://mop.wowroad.info/?quest=1685

**Comment by ForesterDev** [comment]
Должно быть исправлено после обновления
