### ISSUE TITLE
[Задание] id 12692 - Возвращение охотника на личей

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#199]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

НПС http://wowroad.info/?npc=28668 не выдает задание http://wowroad.info/?quest=12692

**Что работает не так?**

НПС http://wowroad.info/?npc=28668 не выдает задание http://wowroad.info/?quest=12692 при выполненном условии получения задания http://wowroad.info/?quest=12582 и репутации уважение у http://wowroad.info/?faction=1104

**Как должно работать?**

НПС http://wowroad.info/?npc=28668 должен выдавать задание http://wowroad.info/?quest=12692 при выполненном условии получения задания http://wowroad.info/?quest=12582 и репутации уважение у http://wowroad.info/?faction=1104

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Нужно протестить после обновления
