### ISSUE TITLE
[Группа заданий] Подходящая маскировка

### ISSUE THREAD

**Issue by Devinette** [VirginTeam/VirginCore#2]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Скриншоты демонстрирующие проблему, выделение проблемных мест с помощью графических редакторов приветствуются. Для описания ошибок, возникающих только в движении, снимите видео **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Невозможно выполнить задание Подходящая маскировка(ID 24556 (орда), ID 20438(альянс))  для получения предмета Кель'Делар.

**Что работает не так?**

Отсутствует диалог с нпц Шанди Шикблеск.

**Как должно работать?**

При клике на НПЦ доступен диалог.

**Шаги для воспроизведения ошибки:**

1. Берем квест
2. Идем к НПЦ
3. Нажимаем на НПЦ

**Текущее обновление ядра:**

Билд 151

**Comment by Riazarre** [comment]
Забагивается, если не выполнить правильное действие вовремя.

**Comment by ForesterDev** [comment]
Не воспроизводится

**Comment by Kodekc** [comment]
Недочёты будут устранены в ближайшем обновлении
