### ISSUE TITLE
[Задание] ID 1221 - Корни Синелиста

### ISSUE THREAD

**Issue by murdalak** [VirginTeam/VirginCore#20]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не работает задание "Корни синелиста".

**Что работает не так?**

При попытке выпустить шмыгуноса находясь в нужном месте появляется ошибка "нужно находиться рядом с клубнем" В любой точке шмыгунос отказывается выходить.

**Как должно работать?**

В определённом месте, в середине подземелья, шмыгунос должен выходить и искать клубни синелиста, после чего они должны появится для возможности их последующего сбора игроком.

**Шаги для воспроизведения ошибки:**

1. Берём задание., берём все нужные для него предметы.
2. Идём в подземелье "Лабиринты иглошкурых".
3. Пытаемся выполнить задание нажатием на клетку с шмыгуносом.

**Текущее обновление ядра:**

Live Build 151 2017-04-03 15:25:08 +0400

**Comment by ForesterDev** [comment]
Будет исправлено после ближайшего рестарта
