### ISSUE TITLE
[Группа заданий] id 5404/5406/5508 - Камни осквернителей Плети

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#201]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Данные нпс не выдаются задания (каждый свое) id 5404/5406/5508
http://wowroad.info/?npc=10840 - 5404
http://wowroad.info/?npc=10839 - 5406
http://wowroad.info/?npc=10839 - 5508

**Что работает не так?**

Данные нпс не выдаются задания (каждый свое) id5404/5406/5508 при выполненных условиях заданий:
http://wowroad.info/?npc=10840 - 5404 - условие 6028
http://wowroad.info/?npc=10839 - 5406 - условие 6029
http://wowroad.info/?npc=10839 - 5508 - условие - 5503

**Как должно работать?**

Данные нпс должны выдавать задания (каждый свое) id 5404/5406/5508 при выполненных условиях заданий:
http://wowroad.info/?npc=10840 - 5404 - условие 6028
http://wowroad.info/?npc=10839 - 5406 - условие 6029
http://wowroad.info/?npc=10839 - 5508 - условие - 5503

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Будет исправлено после обновления
