### ISSUE TITLE
[Задание] ID 11920 - Сектанты среди нас

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#208]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Задание http://ru.wowhead.com/quest=11920 не доступно после выполнения  http://ru.wowhead.com/quest=11789

**Что работает не так?**
Задание http://ru.wowhead.com/quest=11920 доступно игроку, если у него АКТИВНО задание http://ru.wowhead.com/quest=11789, но если его уже выполнили, то задание http://ru.wowhead.com/quest=11920 взять не возможно

**Как должно работать?**

Задание http://ru.wowhead.com/quest=11920 должно быть доступно игроку как при активном http://ru.wowhead.com/quest=11789 так и при выполненном

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Проверить после обновления
