### ISSUE TITLE
[Задание] ID 6067 - Путь охотника

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#210]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Отсутствие продолжения цепочки квестов после выполнения задания http://wowroad.info/?quest=6067

**Что работает не так?**

Отсутствие продолжения цепочки квестов http://wowroad.info/?quest=6061 после выполнения задания http://wowroad.info/?quest=6067

**Как должно работать?**

Должно следовать продолжения цепочки квестов http://wowroad.info/?quest=6061 после выполнения задания http://wowroad.info/?quest=6067

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено после обновления
