### ISSUE TITLE
[Задание] ID 11079 - Бич Скверны для Гахка

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#211]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

НПС призывающиеся по квесту не поддаются атаке игрока

**Что работает не так?**

НПС призванные из объекта стоят в текстуре и не поддаются атаке:
http://ru.wowhead.com/npc=23355
ru.wowhead.com›npc=22281
ru.wowhead.com›npc=19755
ru.wowhead.com›npc=23353

**Как должно работать?**

НПС призванные из объекта Должны спавнится рядом с объектом https://youtu.be/_rG2iyZPxqk
http://ru.wowhead.com/npc=23355
ru.wowhead.com›npc=22281
ru.wowhead.com›npc=19755
ru.wowhead.com›npc=23353

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by Lexwood** [comment]
На 25.06.2017 все еще не работает. Build 160 2017-06-15 12:40:01 +0400

**Comment by burninglove** [comment]
Build 162 2017-07-03 14:02:08 +0400 не работает

**Comment by LothlorienElf** [comment]
Build 163 2017-07-25 11:59:12 +0400 всё ещё не работает

**Comment by odino4estvo** [comment]
Build 163 2017-07-25 11:59:12 +0400 
До сих пор не работает квест. Убедительная просьба исправить это в ближ.обновлении... 
Скрины прикладываю... [
![wowscrnshot_090317_111613](https://user-images.githubusercontent.com/27158518/30001550-14d8622e-909a-11e7-9975-ee5eab896e0b.jpg)
![wowscrnshot_090317_111637](https://user-images.githubusercontent.com/27158518/30001551-14d8b5d0-909a-11e7-93fa-66d6442ec84d.jpg)

**Comment by Riazarre** [comment]
Работает на тринити.

**Comment by LothlorienElf** [comment]
Билд 164 - всё ещё не работает

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении

**Comment by odino4estvo** [comment]
Большое спасибо за исправление!
