### ISSUE TITLE
[Задание] ID 7635 - Подходящая тетива

### ISSUE THREAD

**Issue by tukobak** [VirginTeam/VirginCore#213]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Классовый квест для охотника [Подходящая тетива] http://ru.wowhead.com/quest=7635, берется на 60 уровне, но выполнить его невозможно до 80-го.

**Что работает не так?**

Получить кв-итем http://ru.wowhead.com/item=18705 невозможно до 80-го. Так как рейд на ониксию на 80-м лвл.

**Как должно работать?**

Судя по комментариям на вовхед с патча 3.3.5, кв-итем можно получить с  Детёныша чёрного дракона или Дракона Жгучей Чешуи, но на логон3 х1 ничего не падает.

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Build 157 2017-05-02

**Comment by Riazarre** [comment]
По некоторой информации, итем падает с Нефариуса из ЛКТ.

**Comment by ForesterDev** [comment]
Исправлено, проверяйте после ребута сервера
