### ISSUE TITLE
[Группа заданий] ID 13809/11096/13682/13788/13812 - Атака с воздуха

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#214]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Проблема с НПС http://ru.wowhead.com/npc=33687 http://ru.wowhead.com/npc=33695 то оба проваливаются  текстуры, то убивая пасть, падают сектанты

**Что работает не так?**

Проблема с НПС http://ru.wowhead.com/npc=33687 http://ru.wowhead.com/npc=33695 то оба проваливаются  текстуры, то убивая пасть, падают сектанты

**Как должно работать?**

Не один из нпс не должен падать в текстуры. После убийства дракона сектанты должны падать на землю и атаковать игрока.
https://youtu.be/oNmAVkmNz6A

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Исправлено, тестируем после обновления

**Comment by MiceRus** [comment]
Можно опять открывать и править задание.
Сектанты после убийства пасти падают сразу мертвыми. Естественно - не засчитываются.
Иногда один из них спрыгивает в начале боя и исчезает спустя несколько секунд.
Часто приходится 2 раза убивать пасть ,потому что все 3 сектанта не успевают спрыгнуть с пасти до ее убийства
