### ISSUE TITLE
[Существа] ID 22423 - Друид Вечной рощи

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#215]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Некорректное заселение нпс и форма

**Что работает не так?**
некорректне заселение и форма
https://pp.userapi.com/c638022/v638022153/3960c/Im8JW9PHkJE.jpg

**Как должно работать?**

НПС Должны летать в небе с обликом ворона, после, при приближении к зоне их расположение, можно использовать http://ru.wowhead.com/item=31763 и они спускаются на землю и принимаю облик естественный тут видно механику работы https://www.youtube.com/watch?v=VkEIYeDYRCE

**Текущее обновление ядра:**

Build 157 2017-05-02 14:02:07 +0400

**Comment by ForesterDev** [comment]
Они так и должны быть. При использовании Сигнального огня становятся воронами и спускаются на землю. При разговоре превращаются в тауренов. Подкорректировал некоторые детали. Перепроверите после ребута
