### ISSUE TITLE
[Задание] ID 10835 - Аптекарь Антонивич

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#217]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

НПС 21279 не выдает задания 10835 после выполнения преквеста 10538

**Что работает не так?**

НПС 21279 не выдает задания 10835 после выполнения преквеста 10538
при любом уровне репутации с подгородом и траллмаром

**Как должно работать?**

НПС 21279 Должен выдавать задание 10835 после выполнения преквеста 10538

**Текущее обновление ядра:**

Build 158 2017-05-18 12:45:36 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено после ребута
