### ISSUE TITLE
[Существа] ID 467 - Предатель братства справедливости

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#218]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://wowroad.info/?npc=467 По не известным причинам забагивается на игровом мире х1 лич спавнится не в том смерти после смерти (в месте смерти). Воспроизвести на тесте не удалось, но на игровом проблема ежедневна

**Что работает не так?**

http://wowroad.info/?npc=467 По не известным причинам забагивается на игровом мире х1 лич спавнится не в том смерти после смерти (в месте смерти)
http://s41.radikal.ru/i094/1705/2d/a78ac5f63fe9.jpg

**Как должно работать?**

http://wowroad.info/?npc=467 Должен всегда спавнится в координатах в любых случаях, как выполнение задания, как смерти, так и просто исчезновения (если запустили квест который он выдает и за ним н последовали, он исчезает)
[11:57:02] Карта: 0 (Восточные королевства) Зона: 40 (Западный Край) Область: 108 (Сторожевой холм) Фаза: 4294967295
[11:57:02] X: -10504.531250 Y: 1076.193604 Z: 54.099232 Ориентация: 2.701886
[11:57:02] сетка[12,34]ячейка[2,0] ИНИнстанса: 0
[11:57:02]  XЗоны: 55.442089 YЗоны: 47.337059
[11:57:02] ZОснования: 54.099655 ZПола: 54.099655 имеете данные Высот (Карта: 1 КартаВ: 1)

**Текущее обновление ядра:**

Build 158 2017-05-18 12:45:36 +0400

**Comment by ForesterDev** [comment]
Не получается воспроизвести проблему, но внес некоторые правки, нужно будет после ребута проверить
