### ISSUE TITLE
[Существа] ID 16097 - Изалиен

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#219]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

После призыва НПС не возможно атаковать

**Что работает не так?**

http://www.wowhead.com/npc=1609 http://s002.radikal.ru/i198/1705/6e/44e9834fa7b4.jpg

**Как должно работать?**

НПС должен после призыва атаковать игрока

when summoned, she yells
In life, I focused my energies on healing others. Let us see in death how much pain I can cause!
and despite how furious she will thank you in her last words
My torture is ended and now I can join the Goddess. Thank you so very much!

**Текущее обновление ядра:**
Build 158 2017-05-18 12:45:36 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено после ребута
