### ISSUE TITLE
[Игровая механика] Баффы, ускоряющие персонажей и взаимодействие с транспортом

### ISSUE THREAD

**Issue by gmOverfire** [VirginTeam/VirginCore#22]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Проблема касается всех персонажей, получивших бафф на скорость передвижения, и взаимодействующих с транспортом (Машинки на ОЛО, полях боя, в Ульдуаре, в ИЧ).

**Что работает не так?**

https://youtu.be/EExkgbVSH8I
По видео видно, что после истечения срока действия баффа персонаж сохранил добавленную скорость, и античит реагировал на это.

**Как должно работать?**

Бафф не должен действовать после истечения срока действия.

**Шаги для воспроизведения ошибки:**

1. Получаем бафф на скорость передвижения
2. Садимся в транспорт
3. Ждем окончания баффа
4. Слезаем с транспорта

**Текущее обновление ядра:**

PTR Build 20 2017-04-05 12:06:47 +0400

**Comment by Riazarre** [comment]
Test

**Comment by gmKroshka** [comment]
Updates BotBOT - В прошлую пятницу в 11:24
Исправлено забагивание скорости игрока при посадке на транспорт с аурами, изменяющими скорость передвижения
