### ISSUE TITLE
[NPC] ID 20159 - Магистр Аледис

### ISSUE THREAD

**Issue by Luchass** [VirginTeam/VirginCore#220]
**Описание:**

http://ru.wowhead.com/npc=20159/magister-aledis
http://wowroad.info/?npc=20159

**Что работает не так?**

У NPC кривой маршрут. Время от времени проваливается.

**Как должно работать?**

Должен корректно ездить на птице.

**Текущее обновление ядра:**

Build 158 2017-05-18 12:45:36 +0400

**Comment by Kodekc** [comment]
Переписал маршрут движения NPC. Изменения будут применены в ближайшем обновлении
