### ISSUE TITLE
баг с заданием предательство 

### ISSUE THREAD

**Issue by denchik2287** [VirginTeam/VirginCore#221]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** исправте баг с квестом невозможно пройти**)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Добавьте описание проблемы здесь.

**Что работает не так?**

Фактический результат — тот, который вы наблюдаете

**Как должно работать?**

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось 
 тестирование

**Comment by denchik2287** [comment]
исправте баг с квестом невозможно пройти

**Comment by Riazarre** [comment]
Переоформляем по шаблону, либо закрываю.
Шаблон перед глазами. Заголовок подсмотреть можно по уже созданным репортам.

**Comment by Riazarre** [comment]
Отклонено, закрыто.
