### ISSUE TITLE
[Заклинание] ID 50041 - Вечная мерзлота 

### ISSUE THREAD

**Issue by duressq** [VirginTeam/VirginCore#222]
**Описание**

Жертвы "Озноба" окоченевают, и их скорость передвежения снижается на 15% на 10 сек.

**Что работает не так?**

При рассеивании болезни должен спадать дебаф от таланта
Дебаф остается даже без болезни

**Как должно работать?**

При рассеивании болезни должен спадать дебаф от таланта
Дебаф должен моментально заканчиваться если на цели заканчивается болезнь.

**Текущее обновление ядра:**

Build 158 2017-05-18 12:45:36 +0400

**Comment by duressq** [comment]
Вот как работает у нас https://youtu.be/JwPzAVfCKt8
А вот как должно быть https://youtu.be/s28qpQG8c9U

**Comment by Riazarre** [comment]
Где доказательства правильной работы?
Видео с пиратского сервера не является таковым.
Предоставьте пруфы, или репорт будет отклонен.

**Comment by Riazarre** [comment]
Дубликат, закрыто.
https://github.com/VirginTeam/VirginCore/issues/137

**Comment by Riazarre** [comment]
Подтверждаю, при диспелле болезни дебаф таланта остается.

Пруф на правильную работоспособность:
> Chilblains: Icy Clutch can no longer miss when Frost Fever hits, however, when Frost Fever is dispelled Icy Clutch will also be dispelled.

http://eu.battle.net/wow/en/game/patch-notes/3-2-0

**Comment by Gooldark** [comment]
А что, нормального видео с фростом нету чтоль? Хотя патчноут довольно конкретный.

**Comment by Gooldark** [comment]
Похожая тема https://github.com/VirginTeam/VirginCore/issues/227

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления

**Comment by Gooldark** [comment]
Работает
