### ISSUE TITLE
[Заклинание] ID 50043/59921 - Вечная мерзлота/Озноб

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/VirginCore#227]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Взаимодействие  ID 50043 - Вечная мерзлота, ID 49203 - Ненасытная стужа, ID 59921 - Озноб.

**Что работает не так?**

При использовании Ненасытная стужа озноб не вызывает наложение Вечная мерзлота, в то же время Вечная мерзлота накладывается при использовании оков, ледяного прикосновения, мора.

**Как должно работать?**

Вечная мерзлота не должна прокать от оков, ледяного прикосновения, мора, а должен появляться непосредственно от наложения озноба. Таким образом Вечная мерзлота должна появляться при использовании ненасытной стужи, через 0,3 секунды(так как озноб в свою очередь должен вещаться от ненасытной стужи с задержкой, но это уже другой баг).

**Доказательства**

https://www.youtube.com/watch?v=ouU-s7e1o6k - 3:21 фдк использует Ненасытная стужа, через 0,3 сек накладывается озноб с вечной мерзлотой.

http://eu.battle.net/wow/ru/game/patch-notes/3-2-0
> Вечная мерзлота: «Ледяная хватка» теперь срабатывает всегда, если цель заражена «Ознобом», однако рассеивается при рассеивании «Озноба».

Похожая тема - https://github.com/VirginTeam/VirginCore/issues/222

**Текущее обновление ядра:**

22.05.2017.

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=534725

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления

**Comment by Gooldark** [comment]
Работает
