### ISSUE TITLE
[Рейд] Каражан (ID 18168 Ведьма)

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#23]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Ведьма http://ru.wowhead.com/npc=18168

**Что работает не так?**

НПЦ не агрится, ничем и никак, и его нельзя атаковать.

**Как должно работать?**

Босс должен агриться, и его можно убить.

**Текущее обновление ядра:**

Virgin Build 151 2017-04-03 15:25:08 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
