### ISSUE TITLE
[Заклинание] ID 49638 Талант дк "Порочность"

### ISSUE THREAD

**Issue by Manulli** [VirginTeam/VirginCore#231]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 49638

**Что работает не так?**

Не показывает спелл дамаг у дк, при взятом таланте [порочность](http://wowroad.info/?spell=49638)
[Скрин](http://radikal.ru/big/m8yoc3t8f4esb)

**Как должно работать?**

Могу предположить, что аналогично паловским [покрову света](http://wowroad.info/?spell=53503) или [касание света](http://wowroad.info/?spell=53592)
[Скрин1](http://radikal.ru/big/lxxef0bafagkx) (покров)
[Скрин2](http://radikal.ru/big/sl4qppzdtgipb) (касание)

**Шаги для воспроизведения ошибки:**

1. Взять 1-5 пунктов таланта [Порочность](http://wowroad.info/?spell=49638)
2. Открыть вкладку "магия" в окне инфо персонажа
3. Недоумевать

**Текущее обновление ядра:**

Build 158 2017-05-18
logo3 x1

**Comment by Gooldark** [comment]
Порочность просто апает зависимость спелов дк от апа, даже если порочность будет давать спд, это никак не повлияет на дк, так как его абилки скалируются только от апа.

Можно закрывать.
