### ISSUE TITLE
[Игровая механика] - Внутриигровой транспорт

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#232]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

При проплыве на корабле из Ауберлина в Тельдрассил, а так же при пролете на дирижабле из Подгорода в Тернистую долину игрока после прогрузки локации телепортирует в текстуры, или в море.

**Что работает не так?**

При проплыве на корабле из Ауберлина в Тельдрассил, а так же при пролете на дирижабле из Подгорода в Тернистую долину игрока после прогрузки локации телепортирует в текстуры.
http://i053.radikal.ru/1705/e0/e506a2f15a37.jpg
http://s019.radikal.ru/i622/1705/a7/2d1dd92011c1.jpg

**Как должно работать?**

При посадке на корабль, дирижабль, после пролета/проплыва некоторой территории игрока прогружает, и должно прогружать четко на тот же корабль/дирижабль на котором он двигался и должен доплывать/долетать до точки остановки.

**Шаги для воспроизведения ошибки:**

**Текущее обновление ядра:**

Build 158 2017-05-18 12:45:36 +0400

**Comment by Riazarre** [comment]
Проблема, как в #154

**Comment by Alexdaros** [comment]
так же персонаж может прогрузится раньше транспорта и это приведет к гибели персонажа

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
