### ISSUE TITLE
[NPC] ID 27136 - Главнокомандующий Халфорд Змеевержец <7-й легион>

### ISSUE THREAD

**Issue by Manulli** [VirginTeam/VirginCore#233]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 27136 - Главнокомандующий Халфорд Змеевержец <7-й легион>

**Что работает не так?**

Непись отказывается давать квесты, следубщие в цеопчки, при этом принимает квесты отменно

**Как должно работать?**

После сдачи одного квеста в цепочки, должен выдать следубщий. Не хочет.

**Шаги для воспроизведения ошибки:**

Вариант 1
1. Взять квест [id 12174](http://wowroad.info/?quest=12174)
2. Сдать этот квест Халфорду (непись из сабжа)
3. Не получить у Халфорда (непися из сабжа) [новый](http://wowroad.info/?quest=12235)

Вариант 2
1. Взять квест [праведная проповедь](http://wowroad.info/?quest=12321)
2. Сдать Халфорду
3. Не получить следущий [заброс на вражескую территорию](http://wowroad.info/?quest=12325)
 
**Текущее обновление ядра:**

Build 158 2017-05-18
logon3 x1

**Comment by Riazarre** [comment]
Не выдает квесты.
 - Должен выдать http://ru.wowhead.com/quest=12235 после http://ru.wowhead.com/quest=12174
 - Должен выдать http://ru.wowhead.com/quest=12325, после выполнения http://ru.wowhead.com/quest=12281 и http://ru.wowhead.com/quest=12321

**Comment by Scoren** [comment]
1 часть исправлена. Во второй бага нет, там 3 преквеста, а не два. Вовхедом пользуйтесь
