### ISSUE TITLE
[Задание] ID 12695/12692 - Возвращение сухой шкуры/Возвращение охотника на личей

### ISSUE THREAD

**Issue by Manulli** [VirginTeam/VirginCore#234]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 12695 - Возвращение сухой шкуры
ID 12692 - Возвращение охотника на личей

**Что работает не так?**

Оба квеста предшествуют дейликам в низине, каждый у своей фракции. Но ни один, ни второй взять нельзя

**Как должно работать?**

Либо оракулу, либо волчеру (зависит от того, кто остался в живых) сдается перманентный квест, и берется новый, один из указанных в шапке (зависит от фракции)

**Шаги для воспроизведения ошибки:**
Вариант1
1. [Бремя героя](http://wowroad.info/?quest=12581)
2. Во время убийства лича, оставить в живых либо оракула/волчера
3. Сдать квест [Длань Оракулов](http://wowroad.info/?quest=12689)/[Защитник племени Бешеного Сердца](http://wowroad.info/?quest=12582)
4. Следущим должен следовать квест из шапки [Возвращение сухой шкуры](http://wowroad.info/?quest=12695)/[Возвращение охотника на личей](http://wowroad.info/?quest=12692)

**Текущее обновление ядра:**

Build 158 2017-05-18
logon3 x1

**Comment by Riazarre** [comment]
Дубликат.
