### ISSUE TITLE
[NPC] ID 12876 Барон Акванис

### ISSUE THREAD

**Issue by Alexdaros** [VirginTeam/VirginCore#235]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Барон Акванис не призывается

**Что работает не так?**

При использовании камня, по заданию Среди руин должен появляться Барон Акванис, с которого для игроков орды падает Странная водяная сфера, начинающая задание Барон Акванис. Привести в действие камень может только игрок, у которого есть задание Среди руин

**Как должно работать?**
при взаимодействии с камнем должен призваться Барон Акванис

**Текущее обновление ядра:**

Build 158 2017-05-18 12:45:36 +0400 live сервер

**Comment by Riazarre** [comment]
Контейнер http://ru.wowhead.com/object=177964
Квест http://ru.wowhead.com/quest=6921
НПЦ http://ru.wowhead.com/npc=12876

**Comment by Kodekc** [comment]
Исправлено. Почему-то скрипт у объекта отвалился. Изменения будут применены в ближайшем обновлении
