### ISSUE TITLE
[Задание] ID 13664 - Падение Черного рыцаря

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#239]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

После выполнения http://ru.wowhead.com/quest=13663 нет продолжения цепочки http://ru.wowhead.com/quest=13664

**Что работает не так?**

После выполнения http://ru.wowhead.com/quest=13663 нет продолжения цепочки http://ru.wowhead.com/quest=13664

**Как должно работать?**

После выполнения http://ru.wowhead.com/quest=13663 нпс http://ru.wowhead.com/npc=33417 должен выдавать задание http://ru.wowhead.com/quest=13664

**Текущее обновление ядра:**

Build 158 2017-05-18 12:45:36 +0400

**Comment by Riazarre** [comment]
Чтобы получить данное задание нужно стать искателем славы хотя бы одной столицы.
Закрыто.
