### ISSUE TITLE
[Предмет] id 47499 - Настой севера

### ISSUE THREAD

**Issue by WoWz** [VirginTeam/VirginCore#246]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

** [Настой севера] и Друид**

Настой севера описание :Использование: Увеличивает силу заклинаний на 47, силу атаки на 80 или силу на 40 в течение 3600 sec. Считается как боевым, так и охранным эликсиром. Эффект сохраняется после смерти. (Восстановление 1 секунд)

**нет прока на 80 АП! прокает только на 40 силы или 47 спд. ( Друид кошка)**

Фактический результат — прокает только на 40 силы или 47 спд

**Как должно работать?**

Ожидаемый результат — Должно прокать все 3 бафа по очереди

**Шаги для воспроизведения ошибки:**

1. Шаг один Создать Друида
2. Шаг Вкачать ферал ветку
3. Шаг привратится в кошку и тыкать Настой севера

**Текущее обновление ядра:** Build 159 2017-05-29 Logon 3 WoW Circle 3.3.5a x1 PvE

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by ForesterDev** [comment]
Согласно комментариям с вовхеда так и должно быть

http://ru.wowhead.com/item=47499#english-comments

**Comment by Hringhorni** [comment]
Да, так же это заметил, но не придал значения.

**Comment by WoWz** [comment]
то есть получается 80 АП! Друидам не положено... ?
