### ISSUE TITLE
[Задание] ID 1960 - Лавка алхимика

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#247]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

НПЦ http://wowroad.info/?npc=6492

**Что работает не так?**

При использовании свитка http://wowroad.info/?item=7308 или АоЕ атаки в чате пишутся эмоции
>Порождение разлома приходит в ярость и бросается в атаку!

но сами НПЦ http://wowroad.info/?npc=6492 не становятся видимыми игроку. Через некоторое время они вновь прячутся
>Порождение разлома скрывается обратно в Бездну!

**Как должно работать?**

НПЦ должны быть видимы при использовании свитка, или АоЕ атаки.

**Текущее обновление ядра:**

PTR: Build 29

**Comment by ForesterDev** [comment]
Исправлено, проверьте после онбовления
