### ISSUE TITLE
[Задание] ID 1522 - Зов огня

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#248]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

НПС http://wowroad.info/?npc=5892 не выдает задание http://wowroad.info/?quest=1522 если ты Троль,

**Что работает не так?**

НПС http://wowroad.info/?npc=5892 не выдает задание http://wowroad.info/?quest=1522 если ты Троль,

**Как должно работать?**

НПС http://wowroad.info/?npc=5892 должен выдавать задание http://wowroad.info/?quest=1522 если ты Троль или Орк
**Шаги для воспроизведения ошибки:**

**Текущее обновление ядра:**

Build 159 2017-05-29 11:50:59 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено после обновления
