### ISSUE TITLE
[Задание] ID 11491 - Голем Железной руны: обучение "Обманке"

### ISSUE THREAD

**Issue by Kusakabe2310** [VirginTeam/VirginCore#25]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не работает задание http://ru.wowhead.com/quest=11491

**Что работает не так?**

После того как встал на коврик и произошел диалог, задание не засчитает

**Как должно работать?**

"Потопчись на его коврике. А когда он начнет возмущаться, воспользуйся "Обманкой"! " Синий Кристалл ненужен 

**Шаги для воспроизведения ошибки:**

1. Примеряем костюм голема
2. Идем к http://ru.wowhead.com/npc=24718
3. Топчим его ковер и ничего

**Текущее обновление ядра:**

Build 151 2017-04-03 15:25:08 +0400

**Comment by ForesterDev** [comment]
Исправлено .проверьте после обновления
