### ISSUE TITLE
[Задание] ID 5650 - Одеяния тьмы

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#252]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не засчитывает критерий задания

**Что работает не так?**

При исцелении нпс http://ru.wowhead.com/npc=12428 заклинанием Малое исцеление (уровень 2)
НПС встает с места, произносит диалог, исцеляется, но не засчитывает критерий задания

**Как должно работать?**

При исцелении нпс http://ru.wowhead.com/npc=12428 заклинанием Малое исцеление (уровень 2)
НПС встает с места, произносит диалог, исцеляется, и должен засчитывать критерий задания

**Текущее обновление ядра:**

Build 159 2017-05-29 11:50:59 +0400

**Comment by ForesterDev** [comment]
Задание засчитывается, не после исцеления, а после наложение бафа Слово силы: Стойкость. Читайте описание квеста
