### ISSUE TITLE
[Задание] ID 5060 - Под замком

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#253]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

объект http://wowroad.info/?object=175924 не выдает задания http://wowroad.info/?quest=5060

**Что работает не так?**

После выполнения задания http://wowroad.info/?quest=5059 оно считается как не выполненное на персонаже, по этому и объект http://wowroad.info/?object=175924 не выдает задания ttp://wowroad.info/?quest=5060

**Как должно работать?**

После выполнения задания http://wowroad.info/?quest=5059 оно должно считается как выполненное на персонаже, по этому и объект http://wowroad.info/?object=175924 должен выдавать задание ttp://wowroad.info/?quest=5060

**Текущее обновление ядра:**

Build 159 2017-05-29 11:50:59 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
