### ISSUE TITLE
[Задание] ID 10166 - Память о Белостволе

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#254]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://wowroad.info/?npc=19456 не становится дружелюбным после использования итема http://wowroad.info/?item=28209 около рунного камня.

**Что работает не так?**

http://wowroad.info/?npc=19456 не становится дружелюбным после использования итема http://wowroad.info/?item=28209 около рунного камня.

**Как должно работать?**

http://wowroad.info/?npc=19456 должен становится дружелюбным после использования итема http://wowroad.info/?item=28209 около рунного камня.

**Текущее обновление ядра:**

Build 159 2017-05-29 11:50:59 +0400

**Comment by ForesterDev** [comment]
Он становится дружелюбным не при использовании итема, а при хп <30%
