### ISSUE TITLE
[Заклинание] ID 59621 - Берсерк

### ISSUE THREAD

**Issue by Iammelkor** [VirginTeam/VirginCore#257]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 59621 - Берсерк

**Что работает не так?**

ID 59621 - Берсерк при нанесении на два оружия обновляет прок.

**Как должно работать?**

При нанесении данного заклинания на оружия(скажем для роги) при проке данного спела с одного оружия, прок со второго оружия должен дать второй такой баф. А не обновить.

**Шаги для воспроизведения ошибки:**
1. Взять рогу или энхшамана.
2. Нанести на оружие item=44492
3. Побить мобов. Прок обновляется, а не стакается.
**Текущее обновление ядра:**

Последнее обновление ядра: Build 159 2017-05-29 11:50:59 +0400

**Comment by Riazarre** [comment]
Прокает с обеих рук, не подтверждаю.
