### ISSUE TITLE
[Задание] id 12654 - Охотник на полставки

### ISSUE THREAD

**Issue by Immoretall** [VirginTeam/VirginCore#260]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Тамара Шестеркрут, квест Охотник на полставки http://ru.wowhead.com/quest=12654#english-comments 

**Что работает не так?**

Квеста нет.

**Как должно работать?**

Взять квест http://ru.wowhead.com/quest=12654#english-comments 

**Шаги для воспроизведения ошибки:**

1. Шаг один Поговорить с Тамарой
2. Шаг два Получить квест
3. Шаг три

**Текущее обновление ядра:**
Build 159 2017 05 23 Live Server
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by Scoren** [comment]
Задание доступно. бага нет.
