### ISSUE TITLE
[Заклинание] ID 48066 - Слово силы: Щит

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/VirginCore#263]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

ID 48066 - Слово силы: Щит и баф на 30%, ID 58597 - Священный щит этот репорт не касается так как на щит пала могут воздействовать только баф цлк и баф среза хила на аренах, у приста же есть таланты усиления исходящего исцеления которые влияют на щит.
Репорт продолжение https://github.com/VirginTeam/VirginCore/issues/148

**Что работает не так?**

Баф 30% к щиту перестает действовать если вкачать талант ID 33190 - Средоточие силы

**Как должно работать?**

Баф должен исчезать только при наличии бафа арены и бафа цлк.

Насколько я понимаю сейчас этот баф исчезает если на присте появляется ауры модифицирующие исходящее исцеление, по идее на присте из таких аур может быть только ID 33190 - Средоточие силы(возможно овер в каст вара).

Получается что сейчас только пал, шп, хприст получает бонус в 30% абсорба, у дц его нет, так как все дц качают талант на 4% хила.

**Текущее обновление ядра:**

03.06.2017

**Comment by ForesterDev** [comment]
Исправлено, проверять после обновления

**Comment by Gooldark** [comment]
Работает
