### ISSUE TITLE
[Задание] ID 9612 - Большое спасибо!

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#265]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

нпс http://ru.wowhead.com/npc=17587 не выдает задания http://ru.wowhead.com/quest=9612

**Что работает не так?**

нпс http://ru.wowhead.com/npc=17587 не выдает задания http://ru.wowhead.com/quest=9612

**Как должно работать?**

нпс http://ru.wowhead.com/npc=17587должен выдавать задание только ДРЕНЕЯМ http://ru.wowhead.com/quest=9612

**Текущее обновление ядра:**

Build 158 2017-05-18 12:45:36 +0400

**Comment by Ewropa** [comment]
он выдает задание только по скрипту, а именно после лечения или помощи в убийстве

**Comment by Ewropa** [comment]
для того. чтоб взять задание, нужно с агрить нипа http://www.wowhead.com/npc=17372 подвести к http://ru.wowhead.com/npc=17587, через несколько секунд он попросит помощи, использовать на него http://ru.wowhead.com/spell=28880, убил нипа http://www.wowhead.com/npc=17372 и вуаля кв. появился

**Comment by ForesterDev** [comment]
Заселение будет подкорректировано в обновлении
