### ISSUE TITLE
Перевод

### ISSUE THREAD

**Issue by murdalak** [VirginTeam/VirginCore#266]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Перевод диалога

**Что работает не так?**

Нет перевода в общем диалоге с "Делиана" [ID=16013]
(http://imgur.com/45DZVP9)
Нет перевода в прогрессе и завершении квеста "Справедливое вознаграждение ID=8937
[Прогресс](http://imgur.com/6gbBydU)
[Завершение квеста](http://imgur.com/Yf2BvHC)

**Как должно работать?**

Перевод

**Шаги для воспроизведения ошибки:**

**Текущее обновление ядра:**

Build 159 2017-05-29 11:50:59 +0400

**Comment by ForesterDev** [comment]
Чтобы подобные репорты были исправлены, найдите корректный перевод и приложите к репорту. Это значительно ускорит процесс

**Comment by Luchass** [comment]
locales_broadcast_text 11904
"Постарайтесь не привлекать слишком много внимания. Я жду, пока Совет удостоит меня аудиенции. Я готова ждать сколько потребуется – среди этих мускулистых стражей я чувствую себя в безопасности."

**Comment by Luchass** [comment]
Переведены почти все окна диалога со всеми NPC.
