### ISSUE TITLE
Задание ID=8309

### ISSUE THREAD

**Issue by murdalak** [VirginTeam/VirginCore#267]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Кристалл не копируется

**Что работает не так?**

После нажатия на кристалл и последующего нажатия на кнопку ничего не происходит

**Как должно работать?**

Кристалл должен работать

**Шаги для воспроизведения ошибки:**

1. Заходим в любой из 3 ульев и идем к кристаллу
2. Нажимаем на кристалл
3. Нажимаем на диалоговое окно

**Текущее обновление ядра:**

Build 159 2017-05-29 11:50:59 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
