### ISSUE TITLE
[Объект] ID 182393 - Телаарская доска объявлений

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#269]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

Можно взять задание, не обладая положительной репутацией с Куренай (http://ru.wowhead.com/faction=978)

**Как должно работать?**

Квесты с доски можно взять при дружелюбной репутации.
Из пруфов - только комментарий с вовхеда дополнения Дренор (http://ru.wowhead.com/quest=9940#comments)

> От Planktontrue (823 – 2·10) 2015-01-15 (Обновление 6.0.3)		
> Для получения квеста с Доски необходимо иметь дружелюбные отношения с фракцией Куренай.

Возникает ситуация, что можно взять квест, но некому сдать из-за отсутствия нейтральной репутации (нпц не хотят разговаривать).

**Текущее обновление ядра:**

Build 159

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
