### ISSUE TITLE
[Задание] id 9433 - Проба из Лунного колодца

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#271]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://ru.wowhead.com/quest=9433
Квест работает как должен, но есть возможность выполнить его не blizzlike.

**Что работает не так?**

Лутаем панель - получаем квеститем.
```
[18:40:23] [Concealed Control Panel] GUID: 36727 ID: 401000
[18:40:23] X: -4516.649902 Y: -849.263977 Z: -41.723701 MapId: 1
[18:40:23] Ориентация: 4.743020
[18:40:23] Phasemask 1
[18:40:23] SpawnTime: Full:10m Remain:0s
```
**Как должно работать?**

Не должно быть панели, с которой можно лутануть итем.

**Текущее обновление ядра:**

Build 159

**Comment by ForesterDev** [comment]
Исправлено. будет применено в обновлении
