### ISSUE TITLE
[NPC] id 9499 - Штоппор Наливалс

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#273]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

Низкий шанс дропа, либо отсутствует лут при убийстве НПЦ (список лута http://ru.wowhead.com/npc=9499). Просьба проверить по базе данных.

**Текущее обновление ядра:**

Virgin: Build 159

**Comment by ForesterDev** [comment]
Лута нет, будет исправлено в обновлении
