### ISSUE TITLE
[Задание] id 12855 - Найти преступника

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#275]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

Заюзав квеститем, призывается волк. Игрок садится на него, и может им управлять. НПЦ призываются постоянно, даже если стоять на месте.
Квест не выполняется, даже если самому прибежать на место.

**Как должно работать?**

Волк бежит самостоятельно по маршруту, игрок не может им управлять, только использовать способности, чтобы замедлять появляющихся НПЦ.
Видео: http://www.youtube.com/watch?v=t418T0miLfg

**Текущее обновление ядра:**

Virgin Build 159

**Comment by Accycc** [comment]
и когда исправят? хранителя не  могу сделать

**Comment by Riazarre** [comment]
Исправлено, будет применено после обновления.
