### ISSUE TITLE
[Задание] ID 12924 - Возобновление союза

### ISSUE THREAD

**Issue by Volendelon** [VirginTeam/VirginCore#276]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Невозможно сдать квест королю Йоккуму из-за враждебности самого короля Йоккума

**Что работает не так?**

Йоккум враждебен.

**Как должно работать?**

Йоккум доступен для сдачи квеста.

**Шаги для воспроизведения ошибки:**
Ниче не понял тут

**Текущее обновление ядра:**

Build 48 2017-05-02 16:08:09 +0400
logon3 server x3

**Comment by Volendelon** [comment]
Хееееелп

**Comment by Volendelon** [comment]
Хееееееелп

**Comment by Ewropa** [comment]
такой вопрос, задание http://ru.wowhead.com/quest=12956 выполнялось?
есть вероятность, что при перестроении таблиц заданий в базе, слетели некоторые фиксы, если задание не выполнялось, отменяем задание возобновление союза, отлетаем от дун нефелема, возвращаемся, ковыряем там мобов, пока не выпадет http://ru.wowhead.com/item=41556, делаем дающие задани и по завершении берем про союз.
Это лишь мои доводы, нужно все проверять, если кто проверит и скажет, что действительно задание 12924 доступно при не выполненном 12956. то будет сделан еще один фикс, который исправит проблему.
Если же задание выполнялось, нужно тогда смотреть, сколько репутации дается за задания 12956 и 12915, должно быть по 28,6К выдавать

**Comment by Ewropa** [comment]
проблем с цепочкой не обнаружено, все работает правильно
