### ISSUE TITLE
[Символ] ID 63903 - Символ духа дикого волка

### ISSUE THREAD

**Issue by Anjeydub** [VirginTeam/VirginCore#279]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
Не коректная  робота Символа у шамана

Символ http://wowroad.info/?spell=63903 "Символ духа дикого волка"

**Что работает не так?**- он не увиличает ап у http://ru.wowhead.com/spell=51533

Фактический результат — тот, который вы наблюдаете урон волков по 300 хп крит 600 

**Как должно работать?** урон воллков по 3000 хп

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы - урона волков 30% од ап шамана + свой ап

**Шаги для воспроизведения ошибки:**

1. Шаг один вызвали волков 
2. Шаг два смотрим 
3. Шаг три щитаем

**Текущее обновление ядра:** 159 2017-05-29

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование
Logon3-x1 pve

**Comment by Plasmashield** [comment]
Да скорее всего дело не в глифе. Волкам вообще статы от шамана не идут

**Comment by Trombocid** [comment]
Потестил собак (выбрал легко армированный таргет - приста (13% снижение урона) в дуэль зоне, дабы не мучиться с откатами), результат таков: при раздетом до нитки шамане средний дамаг волков без глифа 320, с глифом - так же 320; при одетом шамане, но без глифа - 480, и при одетом шаме с глифом на собак - 640. Тестил несколько раз, так что погрешность минимальна. Результат, как по мне, довольно противоречив. При раздетом шамане урон с глифом и без идентичен, хотя при одетом шамане разница вполне себе заметна. С другой стороны разница в 6к апа у шамана (6.332ед в шмоте против 532ед. без шмота, а это так то 12ти кратная разница) дает собакам прирост в 50% от дефолтного урона, и еще 50% от него же накидывает глиф. Одним словом проблемы со скалированием имеют место быть. Скрины добавлю по надобности.

**Comment by Gooldark** [comment]
Глиф работает, проверяется элементарно, вызываешь волков в манекен без глифа, смотришь сколько нанесли урона, втыкаешь глиф, повторяешь манипуляции, сравниваешь. У меня без глифа за 59 атак(9 критовых) волки нанесли 29160 урона, с глифом 57 атак(6 критовых) волки нанесли 36366 урона.

Вот тема про волков, там почти все есть https://github.com/VirginTeam/VirginCore/issues/96 не хватает информации о хп волков, если у вас есть скрины/видео с офа, где видно кп волков пожалуйста скиньте мне, это в ваших же интересах.

**Comment by Riazarre** [comment]
Закрыто, идем в репорт #96
