### ISSUE TITLE
[Задание] ID 12140 - Славься, Роанук

### ISSUE THREAD

**Issue by nikonavr** [VirginTeam/VirginCore#281]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Когда кто-то берет квест "[Славься, Роанук!](http://ru.wowhead.com/quest=12140)", командиру Агмару нельзя сдать квест и он сидит возле Роанука, ждет когда игрок совершит диалог с Роануком, чтобы тот зачитал какую-то присягу.
[Скриншоты](http://imgur.com/a/4wzmB)

**Что работает не так?**

NPC стоит неактивный, у него нельзя взять и завершить задания. Он не идет обратно на место спавна 

**Как должно работать?**

Чтобы NPC Командир Агмар спустя какое-то время, 2-3 минуты, шел обратно на свой трон. Этого времени вполне хватит на прослушивание диалога.

**Шаги для воспроизведения ошибки:**

1. Нужно чтобы кто-то взял квест [Славься, Роанук!](http://ru.wowhead.com/quest=12140)
2. Нужно чтобы этот кто-то улетел делать другие квесты и не запускал диалог с Роануком Ледяной Пылью
3. Теперь Командир Агмар неактивен 

**Текущее обновление ядра:**

Logon 3 WowCircle Development
[14:07:20] Последнее обновление ядра: Build 159 2017-05-29 11:50:59 +0400
Logon3 x1 WotLK

**Comment by Scoren** [comment]
не совсем корректный репорт. https://github.com/VirginTeam/VirginCore/issues/343
