### ISSUE TITLE
[Задание] ID 8309- Поиски рун

### ISSUE THREAD

**Issue by sega693** [VirginTeam/VirginCore#283]
**Описание:**
http://wowroad.info/?quest=8309
http://ru.wowhead.com/quest=8309

**Что работает не так?**
при взаимодействии с 
http://wowroad.info/?object=180453
http://wowroad.info/?object=180454
http://wowroad.info/?object=180455
ничего не происходит

**Как должно работать?**

Должны даваться кв итемы

**Шаги для воспроизведения ошибки:**

1. взять кв
2. поговорить с кристалом
3. ...

**Текущее обновление ядра:**
Build 159 2017-05-29 11:50:59 +0400
х1пве

**Comment by murdalak** [comment]
Уже писал про репорт на этот квест, сказали что исправили и применят в обновлении

**Comment by sega693** [comment]
Сорь, по названию искал репорт только.

**Comment by Riazarre** [comment]
Дубликат: #267
