### ISSUE TITLE
[Задание] ID 10720 - Самые маленькие создания

### ISSUE THREAD

**Issue by burninglove** [VirginTeam/VirginCore#285]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не работает квест Самые маленькие создания

**Что работает не так?**

При использовании барабана, нужно чтобы появилось управление сурком, а в результате изменяется вид вокруг (вы находитесь среди стаи сурков) и в данном виде нет возможности отравить бочонок(при нажатии ПКМ пропадает эфект барабана бочонок не отравлен, других умений и предметов не появляется)

**Как должно работать?**
в идеале, наверно, так
http://ru.wowhead.com/quest=10720#videos:id=57938
но хочется хотя бы иметь возможность завершить задание
**Шаги для воспроизведения ошибки:**

1. Берем задание у Рексара(id=21984)
2. Подходим к норе и используем барабан
3. Далее к любому бочонку (не известно надо ли идти к ним в этом облике)

так же при выходе из облика на 5 минут видно суслика отмеченного зеленым маркером, но управления им нет

**Текущее обновление ядра:**
Build 159 2017-0529 11:50:59

**Comment by Lexwood** [comment]
На 25.06.2017 так же не работает. Build 160 2017-06-15 12:40:01 +0400

**Comment by burninglove** [comment]
Build 162 2017-07-03 14:02:08 +0400 не работает до сих пор 13.07.2017

**Comment by san911** [comment]
27.07.2017  не работает. Ребят, а чинить собираетесь?! сильно влияет на получение ачивы "На пиках скал"!

**Comment by DualPain** [comment]
Мне тоже 2 кв не хватает до этой ачивы
