### ISSUE TITLE
[Задание] ID 12270 - Искрошить Альянс

### ISSUE THREAD

**Issue by nikonavr** [VirginTeam/VirginCore#286]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

В [квесте](http://ru.wowhead.com/quest=12270), в некоторые крошшеры нельзя сесть

**Что работает не так?**

В крошшеры которые использовались другими игроками нельзя сесть.
Было проверено с другом, крошшеры которые я привел нпс стали неактивными
http://imgur.com/a/4bvwG

**Как должно работать?**

Ожидаемый результат - крошшеры должны быть многоразовые

**Шаги для воспроизведения ошибки:**

1. Взять задание ["Искрошить Альянс"](http://ru.wowhead.com/quest=12270)
2. Подойти к крошшеру и взаимодействовать с ним
3. Надеяться на удачу, повезет ли сесть в крошшер

**Текущее обновление ядра:**

Logon 3 WowCircle Development
[15:53:42] Последнее обновление ядра: Build 159 2017-05-29 11:50:59 +0400
Logon3 x1 WotLK

**Comment by Scoren** [comment]
https://github.com/VirginTeam/VirginCore/issues/228
