### ISSUE TITLE
[Задание] id 6063 - Приручение зверя

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#287]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://wowroad.info/?quest=6063

**Что работает не так?**

Неверное описание квеста.

> 
> С помощью хлыста приручения приручите чащобного тенетника. Поупражняйтесь, затем верните хлыст приручения Дазалару в Доланаар.
>  
> Приручите чащобного тенетника.
> 
> Описание
> 
> Охотнику важно помнить о том, какая перед ним стоит ответственность. Природа – не та сила, которую можно подчинить своим прихотям. Ее следует почитать как нечто, без чего само твое существование было бы невозможным.
> 
> <имя>, ты <должен/должна> доказать, что понимаешь это, прежде чем получишь способность превращать любое животное в своего верного спутника.
> 
> Первым делом возьми этот хлыст приручения. С его помощью ты сумеешь приручить чащобного тенетника. Приручи его и поупражняйся в своем охотничьем искусстве.

**Как должно работать?**

http://ru.wowhead.com/quest=6063

> С помощью хлыста приручения приручите чащобного скрытня. Поупражняйтесь, затем верните хлыст приручения Дазалару в Доланаар.
>  
> Приручите чащобного скрытня.
> 
> Описание
> Охотнику важно помнить о том, какая перед ним стоит ответственность. Природа – не та сила, которую можно подчинить своим прихотям. Ее следует почитать как нечто, без чего само твое существование было бы невозможным.
> 
> <имя>, ты <должен/должна> доказать, что понимаешь это, прежде чем получишь способность превращать любое животное в своего верного спутника.
> 
> Первым делом возьми этот хлыст приручения. С его помощью ты сумеешь приручить чащобного скрытня. Приручи его и поупражняйся в своем охотничьем искусстве.

Заменить в описании квеста Чащобый тенетник на Чащобный скрытень.

**Comment by ForesterDev** [comment]
Отклонено. В квесте все верно, а вот нпц http://ru.wowhead.com/npc=1998 надо переименовать, поскольку после каты его переименовали
