### ISSUE TITLE
[Задание] ID 13071 - Злоб любит огонь!

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/VirginCore#29]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не работает задание [Злоб любит огонь!](http://wowroad.info/?quest=13071)

**Что работает не так?**

Не засчитывает сжигание зданий

**Как должно работать?**

Садишься на дракона, летаешь , жмякаешь [Бомбардировка йотунхеймского здания](http://wowroad.info/?spell=7769)
Постепенно засчитывает сгоревшие здания.

**Шаги для воспроизведения ошибки:**

1. сесть на дракона
2. полететь над зданиями
3. Пожмякать бомбардировку

**Текущее обновление ядра:**

Build 151 2017-04-03

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
