### ISSUE TITLE
[Задание] id 11188 - Минус на минус

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#290]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

При использовании квеститема, дракон опускается, но потом вновь взлетает, становясь недоступным для атак ближнего боя.

**Как должно работать?**

Дракон не должен взлетать, чтобы классы, не обладающие рдд атаками могли его убить.
Процесс правильной работы: https://youtu.be/lQP62koyNbQ

**Текущее обновление ядра:**

Virgin Build 159

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
