### ISSUE TITLE
[Задание] id 12245 - Никакой пощады пленникам

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#293]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

Нельзя атаковать квестовых НПЦ после разговора с ними. НПЦ становятся враждебными, но персонаж не может их бить. Судя по всему мешает клетка, в которой они сидят. Ошибка при попытки автоатаки "Вы слишком далеко", при попытке использовать способность "Цель вне поля зрения".
Если переместить НПЦ из клетки - он убивается прекрасно.

**Как должно работать?**

https://youtu.be/bq-p6ih3E2w
Клетка не должна мешать сражению с НПЦ.

**Текущее обновление ядра:**

Virgin Build 159

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении

**Comment by adecvat** [comment]
До сих пор не корректно работает

**Comment by adecvat** [comment]
нпс враждебны
говорить нельзя и убить тоже

**Comment by adecvat** [comment]
до сих пор не работает
