### ISSUE TITLE
Неработает квест, Ид 10911

### ISSUE THREAD

**Issue by bolis16** [VirginTeam/VirginCore#295]
проблема с квестом, неработает ваше он. Невожможно взять пушку и стрелять по воротам, + мобы невыбигают. http://www.wowhead.com/quest=10911/fire-at-will
Видео как ему надо идти https://www.youtube.com/watch?v=6_AOkxleLS0&t=1s

**Comment by Ewropa** [comment]
оформить нужно https://github.com/VirginTeam/VirginCore/blob/master/issue_template.md
иначе работать и не будет
