### ISSUE TITLE
Неработает квест. Ид 10720

### ISSUE THREAD

**Issue by bolis16** [VirginTeam/VirginCore#296]
Квест вапше неправилно работает, http://www.wowhead.com/quest=10720/the-smallest-creatures
Видак как надо работат - https://www.youtube.com/watch?v=0rqnWqbDPfk

**Comment by Ewropa** [comment]
оформить нужно https://github.com/VirginTeam/VirginCore/blob/master/issue_template.md
иначе работать и не будет

**Comment by Riazarre** [comment]
Дубликат.
#285
