### ISSUE TITLE
[NPC] ID 29445 - Торим

### ISSUE THREAD

**Issue by Ewropa** [VirginTeam/VirginCore#298]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

NPC - Торим http://ru.wowhead.com/npc=29445 периодически сидит спиной, т.е. на стуле ногами в спинку стула  

**Что работает не так?**

NPC - Торим http://ru.wowhead.com/npc=29445 периодически сидит спиной, т.е. на стуле ногами в спинку стула 

**Как должно работать?**

Должен сидеть как на картинке http://ru.wowhead.com/npc=29445#screenshots:id=126284

**Шаги для воспроизведения ошибки:**

1. Прилететь в грозовую гряду
2. Побывать в Храме штормов

**Текущее обновление ядра:**

 Build 159 2017-05-29 11:50:59 +0400

**Comment by ForesterDev** [comment]
Проверьте после обновления
