### ISSUE TITLE
[Символ] id 40913 - Символ омоложения

### ISSUE THREAD

**Issue by Lamantinka** [VirginTeam/VirginCore#299]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**
Когда у персонажа <50% хп, то эффект от омоложения на 50% слабее.

**Как должно работать?**
При хп персонажа <50%  эффект от омоложения должен быть на 50% больше.

**Текущее обновление ядра:**

Последнее обновление ядра: Build 160 2017-06-15 12:40:01 +0400

**Comment by Scoren** [comment]
доказательства?

**Comment by Lamantinka** [comment]
Ага, я понял, то оно просто не одной цифрой показывает что хилит на 50% больше, а дополнительной(1600 и 800), в итоге мне всё время высвечивало только 800 вот и подумал, закрыто.
