### ISSUE TITLE
[Группа предметов] Дополнительные критерии от предметов экипировки

### ISSUE THREAD

**Issue by Amfinia** [VirginTeam/VirginCore#300]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://wowroad.info/?item=24121 - Цепь сумеречной совы
http://wowroad.info/?item=24114 - оплетенная этерниевая кольчуга
http://wowroad.info/?item=24117 - объятия рассвета
(Возможно, и другие шеи этого типа)

**Что работает не так?**

Во время висящего бафа от данной шеи (шея должна быть экипирована) делаем Alt+F4. Заходим в игру и меняем шею на любую другую. Бонус от шеи сохраняется у всех участников группы. 
После использования получаем дополнительные 45 рейтинга критического урона.

**Как должно работать?**

Бонус должен работать только при экипированной шее и должен спадать при её смене или снятии.

**Шаги для воспроизведения ошибки:**

1. Надеть шею
2. Релог
3. Переодеть на ту, что обычно носим. Баф от предмета остается.

**Текущее обновление ядра:**

Build 160 2017-06-15 12:40:01 +0400
Logon 3 x1 PVE

**Comment by ForesterDev** [comment]
Исправлено, будет применено после обновления
