### ISSUE TITLE
[NPC] ID 12384 - Август Помешанный

### ISSUE THREAD

**Issue by murdalak** [VirginTeam/VirginCore#302]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Август Помешанный стоит не там

**Что работает не так?**

Август Помешанный стоит не там где нужно. Он стоит у горы, за холмом, как на [скриншоте](http://imgur.com/ubcYV4G)

**Как должно работать?**

Август должен стоять в доме, рядом с дворфом Эганом как на [скриншотах](http://ru.wowhead.com/npc=12384#screenshots)

**Шаги для воспроизведения ошибки:**

1. Идём в Восточные Чумные земли
2. Координаты 10.1;27.8

**Текущее обновление ядра:**

Build 160 2017-06-15 12:40:01 +0400

**Comment by Riazarre** [comment]
Оформляйте, пожалуйста, заголовок по шаблону, не в первый раз же уже репорт создаете.
[Категория] ID № - Название
на примере этого репорта: **[NPC] ID 12384 - Август Помешанный**
так же можно подсмотреть заголовки в других репортах.

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
