### ISSUE TITLE
[Задание] ID 5122 - Медальон веры

### ISSUE THREAD

**Issue by murdalak** [VirginTeam/VirginCore#304]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Аурий не начинает следующее задание "Слова Аурия" ID 5125

**Что работает не так?**

Задание Медальон веры зациклено у Аурия

**Как должно работать?**

После сдачи задания Медальон веры, Аурий должен дать задание Слова Аурия

**Шаги для воспроизведения ошибки:**

1. Идём в Стратхольм
2. Убиваем Малора Ревностного и лутаем сундучок рядом с ним
3. Сдаём медальон Аурию

**Текущее обновление ядра:**

Build 160 2017-06-15 12:40:01 +0400

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
