### ISSUE TITLE
[NPC] ID 3669 - просьба проверить лут

### ISSUE THREAD

**Issue by mirlis** [VirginTeam/VirginCore#310]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

NPC 3669 ( http://wowroad.info/?npc=3669 ) - не полностью прописан лут, либо занижен шанс дропа.

Согласно wowroad, с моба должны падать:
* http://wowroad.info/?item=6465 - шанс 60%
* http://wowroad.info/?item=6460 - шанс 20%
* http://wowroad.info/?item=10410 - шанс 20%

Согласно данным AtlasLoot, шансы немного другие:
* http://wowroad.info/?item=6465 - шанс 51.73%
* http://wowroad.info/?item=6460 - шанс 16.20%
* http://wowroad.info/?item=10410 - шанс 16.03%
(У AtlasLoot кривоваты значения, в сумме 100% не получается)

Убили этого босса раз 15 (или больше, к середине второго десятка я сбился со счёта), за это время в луте видели:
* http://wowroad.info/?item=6465 - падала постоянно, кроме одного раза
* http://wowroad.info/?item=6460 - 1 раз
* http://wowroad.info/?item=10410 - ни разу

Если взять шанс с wowroad-а, то получается, что шанс быть такими неудачниками как мы и не плучить ни одного http://wowroad.info/?item=10410 за 15 заходов составляет 0.8 ^ 15 = 0.035. Что заставляет предположить, что NPC-у не прописан лут.

**Текущее обновление ядра:**

Live, Build 160 2017-06-15

**Comment by ForesterDev** [comment]
привожу выборку из бд по дропу с данного моба
```
 Entry    Item  Reference   Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment  
------  ------  ---------  -------  -------------  --------  -------  --------  --------  ---------
  3669     858          0   1.0458              0         1        0         1         1  (NULL)   
  3669    1179          0    1.954              0         1        0         1         1  (NULL)   
  3669    1206          0   0.3922              0         1        0         1         1  (NULL)   
  3669    1210          0   0.8738              0         1        0         1         1  (NULL)   
  3669    1739       1739       10              0         1        0         1         1  (NULL)   
  3669    2455          0   0.5229              0         1        0         1         1  (NULL)   
  3669    2589          0  11.1532              0         1        0         1         5  (NULL)   
  3669    2592          0  14.1874              0         1        0         1         4  (NULL)   
  3669    2981       2981     0.25              0         1        0         1         1  (NULL)   
  3669    2982       2982     2.96              0         1        0         1         1  (NULL)   
  3669    2988       2988     0.72              0         1        0         1         1  (NULL)   
  3669    4537          0   3.6535              0         1        0         1         1  (NULL)   
  3669    6460          0       20              0         1        1         1         1  (NULL)   
  3669    6465          0       60              0         1        1         1         1  (NULL)   
  3669    9738          0      100              1         1        0         1         1  (NULL)   
  3669   10410          0       20              0         1        1         1         1  (NULL)   
```

Как видите, шансы дропа приведены такие же как вы указали

**Comment by mirlis** [comment]
Благодарю за информацию. Сегодня выпали с 6-й попытки. Просто не везло. =)
