### ISSUE TITLE
[NPC] ID 1364 - занижен шанс дропа предмета

### ISSUE THREAD

**Issue by mirlis** [VirginTeam/VirginCore#311]
**Описание:**

NPC 1364 ( http://wowroad.info/?npc=1364 , http://www.wowhead.com/npc=1364 ) должен дропать http://wowroad.info/?item=3639 по квесту http://wowroad.info/?quest=304 с шансом 100%

**Что работает не так?**

Квест итем выпал со второго раза, т.е. шанс дропа не стопроцентный.

**Как должно работать?**

Шанс дропа должен быть 100%.

**Текущее обновление ядра:**

Live, Build 160 2017-06-15

**Comment by ForesterDev** [comment]
По базе шанс дропа 100%, в игре проверил - падает всегда при взятом квесте. Возможно у вас что-то багнулось

**Comment by mirlis** [comment]
Ну что ж, если это баг ядра, вряд ли такой редкий баг возможно найти. Благодарю.
