### ISSUE TITLE
[Достижение] Заморозить повелителя холода

### ISSUE THREAD

**Issue by Necrius** [VirginTeam/VirginCore#312]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Убийство Ахуна не засчитывается для достижения и с него не падают Осколки Ахуна.

**Что работает не так?**
ГМ в игре мне написал, что для получения достижения необходимо убить Ахуна, взять с него Осколки Ахуна, выполнить их квест, взять новый квест и убить его еще раз. Я его убил три раза, дважды из них - впервые за день, но осколков нигде не нашел.

**Как должно работать?**

Ожидаемый результат — достижение дается сразу после убийства Ахуна.

**Шаги для воспроизведения ошибки:**

1. Воспользоваться поиском подземелий
2. Убить Ахуна и не получить за это достижение
3. Не найти Осколки Ахуна среди его дропа. 

**Текущее обновление ядра:**

Build 160 2017-06-15 12:40:01 +0400

**Comment by ForesterDev** [comment]
Будет исправлено после обновления

**Comment by Hellsingoff** [comment]
Снова те же симптомы на персонаже жены. Два убийства ахуна - ноль осколков и не дали ачив. Помня ситуацию прошлого года пришёл сюда, но в целом в чате пишут что в этом году ачив "вроде работает", но, как я понимаю, не всегда. Что делать? Писать в поддержку чтобы проверяли на персонаже убийства ахуна и выдавали ачив вручную?
