### ISSUE TITLE
[Заклинание] Id 129989 - Угроза Тассариана

### ISSUE THREAD

**Issue by duressq** [VirginTeam/VirginCore#315]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
Угроза Тассариана
Уровень 3
Instant
Когда вы держите в каждой руке по оружию, "Удар смерти", "Уничтожение", "Удар чумы", "Рунический удар", "Кровавый удар" и "Ледяной удар" с 100%-й вероятностью также могут нанести урон от оружия в левой руке.
**Что работает не так?**
УДар бьет 4000 например. От таланта должен быть еще один удар на 2000 и того 6000. У нас  два удара на 4000. И так на КАЖДОМ ударе. Представляете подъем дпса? Фдк сейчас абсолютно вне баланса.
Фактический результат — тот, который вы наблюдаете
https://www.youtube.com/watch?v=0HFZvIl9fDc

**Как должно работать?**
Threat of Thassarian: New 3-point talent. When dual-wielding, your Death Strikes, Obliterates, Plague Strikes, Blood Strikes and Frost Strikes have a 30/60/100% chance to also deal damage with your off-hand weapon.  Off-hand strikes are roughly one half the effect of the original strike.
Ссылка на источник http://eu.battle.net/wow/en/game/patch-notes/3-2-0
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
Off-hand strikes are roughly one half the effect of the original strike.
**Шаги для воспроизведения ошибки:**
Без понятия, я не разработчик. Чините уже. 
1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**
Build 160 25/06/2017
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by Riazarre** [comment]
Создали же уже один репорт, зачем плодить то?
Закрыто, дубль.

**Comment by duressq** [comment]
Две недели назад и до сих пор не закрыто. Что толку тогда от етого репорта? Дк как бьют так и бьют.
