### ISSUE TITLE
[npc] id 37098 - Валь'кира-глашатай

### ISSUE THREAD

**Issue by zyxellgit** [VirginTeam/VirginCore#318]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
ЦЛК, верхний ярус, нпц Валь'кира-глашатай http://ru.wowhead.com/npc=37098 со способностью Страждущая душа http://ru.wowhead.com/spell=71906#used-by-npc
Добавьте описание проблемы здесь.
если вайпнуться в бое с Валь'кира-глашатай http://ru.wowhead.com/npc=37098 после того как она напризывала копии, то копии остаются
**Что работает не так?**
копии остаются
Фактический результат — тот, который вы наблюдаете
копии остаются
**Как должно работать?**
видимо должны пропадать
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Шаг один подняться на верхний ярус в цлк
2. Шаг два сагрить валькиру, дождаться копий, умереть
3. Шаг три вернуться в цлк, подняться на верхний ярус

**Текущее обновление ядра:**

**Comment by ForesterDev** [comment]
Исправлено, будет применено после обновления

**Comment by zyxellgit** [comment]
проблема вернулась
