### ISSUE TITLE
[Группа заданий] Гонки Драконьей Пасти

### ISSUE THREAD

**Issue by Luchass** [VirginTeam/VirginCore#32]
**Описание:**

http://ru.wowhead.com/quest=11064
http://ru.wowhead.com/quest=11067
http://ru.wowhead.com/quest=11068
http://ru.wowhead.com/quest=11069
http://ru.wowhead.com/quest=11070
http://ru.wowhead.com/quest=11071

**Что работает не так?**

Не работает ивенты квестов

**Как должно работать?**

Должно проводиться гонка с квестгиверами

**Шаги для воспроизведения ошибки:**

1. Взять задание
2. Увидеть, что ничего не происходит

**Текущее обновление ядра:**

PTR Build 20 2017-04-05 12:06:47 +0400

**Comment by Luchass** [comment]
Неработоспособность задания не дает выполнить достижение [Небокрушитель](http://ru.wowhead.com/achievement=1638)

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления

**Comment by Riazarre** [comment]
**Найденные баги**
Если по какой-либо причине отстать от НПЦ - он умирает (в режиме ГМ видно труп). 
После реса НПЦ оказывает там, где умер, хотя должен прибыть на свою изначальную точку.
