### ISSUE TITLE
spell=42650

### ISSUE THREAD

**Issue by zyxellgit** [VirginTeam/VirginCore#320]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
http://www.wowhead.com/spell=42650/army-of-the-dead
призывает легион вурдалаков, которые сражаются на вашей стороне в течение 40 sec., нападая на всех.
Добавьте описание проблемы здесь.
при вызове войска все гули сбегаются в 1 точку и стоят как 1 моб
**Что работает не так?**
 вызываем войско, а получаем визуально одного гуля
Фактический результат — тот, который вы наблюдаете
http://forum.wowcircle.com/attachment.php?attachmentid=318231&d=1456837944
http://forum.wowcircle.com/showthread.php?t=538767
**Как должно работать?**

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
http://www.wowhead.com/spell=42650/army-of-the-dead#screenshots:id=173958
**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления сервера
