### ISSUE TITLE
[Заклинание] id 52858 - Контроль популяции

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#323]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

Может прокнуть от любого успешного применения заклинаний, написанных в тултипе.

**Как должно работать?**

Должен прокать только от критических заклинаний.

**Текущее обновление ядра:**

PTR Build 31

**Comment by ForesterDev** [comment]
Исправлено, тестируйте после обновления
