### ISSUE TITLE
[Задание] ID 25285 - Входит и выходит!

### ISSUE THREAD

**Issue by Foolkor** [VirginTeam/VirginCore#324]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

После получения квеста "Входит и выходит!" нужно испытать систему катапультирования, для этого нужно подойти к "Механотанк'у - катапульта" и испытать саму систему, но при активации механизма ничего не происходит и квест не засчитывается.

**Что работает не так?**

После получения квеста "Входит и выходит!" нужно испытать систему катапультирования, для этого нужно подойти к "Механотанк'у - катапульте" и испытать саму систему, но при активации механизма ничего не происходит и квест не засчитывается.

**Как должно работать?**

Мне кажется после использования персонаж должен оказаться в механизме и нажать кнопку катапульты.

**Шаги для воспроизведения ошибки:**

1. Взять квест
2. Подойти к "Механотанк'у - катапульте"
3. Нажать ПКМ по механизму

**Текущее обновление ядра:**

Build 160 2017-06-15 12:40:01 +0400

Live server

**Comment by Riazarre** [comment]
Дубликат. #48
