### ISSUE TITLE
[Задание] ID 10847 - Глаза скеттиса

### ISSUE THREAD

**Issue by Scoren** [VirginTeam/VirginCore#325]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Задание не становится доступным после выполнения условия (преквестов) у выборочных персонажей.

**Что работает не так?**

После выполнения условия http://ru.wowhead.com/quest=10908 задание 10847 недоступно после выполнения условий 10863/10862 задание не становится доступным.

**Как должно работать?**

Задание 10847 должно быть доступно после выполнения условий 10908 или 10863/10862 (фракционные)

**Текущее обновление ядра:**

Build 160 2017-06-15 12:40:01 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
