### ISSUE TITLE
[Игровая механика] Эффекты контроля над персонажем

### ISSUE THREAD

**Issue by TepaMeTp** [VirginTeam/VirginCore#328]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

На данный момент при взятии персонажа в контроль каким-либо NPC есть возможность слегка изменять экипировку.
Персонаж под контролем NPC не использует некоторые способности.

**Что работает не так?**

При взятии в контроль можно снять или экипировать оружие
Воины под эффектом контроля не используют ярость берсерка. 

**Как должно работать?**

При взятии в контроль не должно быть возможности игроком воздействовать на персонажа (возможно кроме эффектов снятия контроля аналогичных рассовой "Каждый за себя" человека.)
Воины должны использовать в контроле способность ярость берсерка.
**Шаги для воспроизведения ошибки:**

1. Шаг один - создать комплект экипировки, в котором слоты оружия пустые. Вытащить сохраненный комплект на панель
2. Шаг два - попасть под эффект контроля. (К примеру на Леди Смертный Шепот)
3. Шаг три  - нажать на выведенный на панель комплект экипировки.

**Текущее обновление ядра:**

 Последнее обновление ядра: Build 160 2017-06-15 12:40:01 +0400

**Comment by ForesterDev** [comment]
Будет исправлено в ближайшем обновлении
