### ISSUE TITLE
[Задание] id 12328 - Просьба Рууны

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/VirginCore#329]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Нет задания http://wowroad.info/?quest=12328 у квестгивера http://wowroad.info/?npc=27581
Мой уровень на данный момент: 76.

**Что работает не так?**

Выполнена цепочка и предстоящее перед нужным задание http://wowroad.info/?quest=12425
но задание не дается.

**Как должно работать?**

выполнил предыдущее задание - получи следующее

**Шаги для воспроизведения ошибки:**

сделать цепочку заданий за орду 
the whole series:

Horde part:
[74] Mikhail's Journal 
[74] Gorgonna 
[74] Tactical Clemency 
[75] Ruuna the Blind 
**Текущее обновление ядра:**

[11:00:41] Ïîñëåäíåå îáíîâëåíèå ÿäðà: Build 160 2017-06-15 12:40:01 +0400
[11:00:41] Èãðîêîâ îíëàéí: 3053 (ìàêñèìóì: 4527). Èãðîêîâ â î÷åðåäè: 0 (ìàêñèìóì: 0).
[11:00:41] Ïðîäîëæèòåëüíîñòü ðàáîòû ñåðâåðà: 2 Day(s) 20 Hour(s) 36 Minute(s) 52 Second(s).
[11:00:41] Ñåðâåðíàÿ çàäåðæêà: 32.
[11:00:41] Ñëåäóþùåå íà÷èñëåíèå î÷êîâ àðåíû: 09.07.2017  10:22

**Comment by Rorshah** [comment]
https://github.com/VirginTeam/VirginCore/issues/169
повтор.

**Comment by Riazarre** [comment]
Ой, действительно, прослакал =D
Закрою, дубликат.
