### ISSUE TITLE
[Задание] id 11728 - Собаки-каки

### ISSUE THREAD

**Issue by ar4i2018** [VirginTeam/VirginCore#330]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Задание  [[Собаки-каки]](http://ru.wowhead.com/quest=11728) не работает.

**Что работает не так?**

Бросаешь [мясо](http://ru.wowhead.com/item=35121) в [Запятнанного нефтью волка](http://ru.wowhead.com/npc=25791), но ничего не происходит.

**Как должно работать?**

[Запятнанный нефтью волк](http://ru.wowhead.com/npc=25791) должен съесть это [мясо](http://ru.wowhead.com/item=35121) и "вывалить" квестовый предмет — [Микропленка](http://ru.wowhead.com/item=35123).
[Видео](https://www.youtube.com/watch?v=W9pp1HqtSzw)

**Шаги для воспроизведения ошибки:**

1. Шаг один. Бросаешь  [мясо](http://ru.wowhead.com/item=35121).
2. Шаг два. Ждешь... Ждешь... Ждешь... Ждешь... И... Еще ждешь... И теперь... Ждешь...
3. Шаг три. Ничего не произошло... Ждешь... Ждешь... 
Даже если бросить 100 кусков [мяса](http://ru.wowhead.com/item=35121), все равно ничего не произойдет.

**Текущее обновление ядра:**

WoW Circle 3.3.5a x1 PvE
Build 160 2017-06-15 12:40:01 +0400

**Comment by DarkCloud069** [comment]
квест работает, но не так как надо, там есть невраждебные волки и возле них надо собирать микропленку

**Comment by ar4i2018** [comment]
@DarkCloud069, бегал по часу два дня подряд, но нашел только одну микропленку.

**Comment by Scoren** [comment]
https://github.com/VirginTeam/VirginCore/issues/230
