### ISSUE TITLE
[Задание] ID 12910 - Найти преступника

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/VirginCore#336]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

Описание:
Честно говоря в шоке.
Почитал историю - уже чинили.
Но видимо применили какую-то старую заплатку и состояние работоспособности откатило.
Сесть на кошку нельзя.

http://wowroad.info/?quest=12910
http://ru.wowhead.com/quest=12910

Что работает не так?

Нельзя сесть на кошку http://wowroad.info/?npc=29857

Как должно работать?

Садишься на кошку и едешь к пещере
https://www.youtube.com/watch?v=0RxjPFMEG-g&feature=youtu.be

Шаги для воспроизведения ошибки:

Взять кв
**Текущее обновление ядра:**

[20:46:00] Ïîñëåäíåå îáíîâëåíèå ÿäðà: Build 162 2017-07-03 14:02:08 +0400
[20:46:00] Èãðîêîâ îíëàéí: 4495 (ìàêñèìóì: 4821). Èãðîêîâ â î÷åðåäè: 0 (ìàêñèìóì: 0).
[20:46:00] Ïðîäîëæèòåëüíîñòü ðàáîòû ñåðâåðà: 2 Day(s) 7 Hour(s) 7 Minute(s) 44 Second(s).
[20:46:00] Ñåðâåðíàÿ çàäåðæêà: 37.
[20:46:00] Ñëåäóþùåå íà÷èñëåíèå î÷êîâ àðåíû: 09.07.2017  10:22

**Comment by DarkCloud069** [comment]
у альянса тоже не работает, гончая должна отвезти к пещере и должен выполниться пункт в квесте

**Comment by Scoren** [comment]
https://github.com/VirginTeam/VirginCore/issues/275 дубликат
Ордынская версия работает

**Comment by Rorshah** [comment]
проверил сегодня - работает.
Возможно перезапуск сервера исправил ошибку.
