### ISSUE TITLE
[Задание] id 3369 - Кошмары

### ISSUE THREAD

**Issue by evgen153d** [VirginTeam/VirginCore#338]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

После выполнения задания "Светящийся осколок" (id 6981), которое даёт предмет Светящийся осколок (id 10441), который падает с Мутанус Пожиратель (id 3654) в Пещерах стенаний, далее по цепочке у Фолла Ветер Мудрости (id 8418) должно становиться доступным задание Кошмары (id 3369).
Существует 2 задания "Кошмары", для Альянса и для Орды. В данном случае идёт речь про ордынский квест.

**Что работает не так?**

Невозможно взять задание. Восклицательного знака нет, взаимодействовать с npc Фолла Ветер Мудрости никак нельзя.
Гейм-мастер сделал вывод, что сломались зависимости квестов.
Проверил на двух персонажах.

**Как должно работать?**

Должно становиться доступным задание Кошмары.

**Шаги для воспроизведения ошибки:**

1. Убить финального босса подземелья Пещеры стенаний, взять с него предмет Светящийся осколок (шанс дропа 70%).
2. Взять с выпавшего предмета задание "Светящийся осколок", поговорить в Кабестане с npc Пароклапан (id 3442) (Степи 63.0 | 37.2), завершить задание у Фолла Ветер Мудрости (Степи 48.4 | 33.0).
3. Обнаружить, что Фолла Ветер Мудрости не даёт Кошмары.

**Текущее обновление ядра:**

Build 162 2017-07-03 14:02:08 +0400
WotLK x1 PvE Live Server

**Comment by Scoren** [comment]
Исправлен
