### ISSUE TITLE
[Заклинание] ID 24858 - Облик лунного совуха

### ISSUE THREAD

**Issue by Ghostly2009** [VirginTeam/VirginCore#339]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Рекаст формы совы не снимает замедления и сковывания.

**Что работает не так?**
В форме совы кастуя форму совы повторно для снятия замедления.Пример: /cast !Облик лунного совуха.Форма остаётся,мана забирается,а замедления не спадают.С другими обликами работает.Пример: /cast !Походный облик

**Как должно работать?**

При нажатии макросы для решифта. /cast !Облик лунного совуха как и другие облики должны снимать все виды сковывания.

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Последнее обновление ядра: Build 162 2017-07-03 14:02:08 +0400

**Comment by TepaMeTp** [comment]
Насколько понимаю механику для решифта из совы с сову требуется нечто вроде
/cancelaura Облик лунного совуха
/cast Облик лунного совуха
 А на данный момент форма совы конфликтует сама с собой, следовательно решифт не происходит

**Comment by Ghostly2009** [comment]
неправильно вы понимаете. /cast !Облик лунного совуха правильно написанный
макрос .! для того чтоб не было формы коровы а сразу из совы в сову

7 июля 2017 г., 10:22 пользователь TepaMeTp <notifications@github.com>
написал:

**Comment by Riazarre** [comment]
А пруфы правильной работоспособности? Почему Вы не допускаете, что это правильно, а все остальные облики работают неправильно?

**Comment by TepaMeTp** [comment]
> неправильно вы понимаете. /cast !Облик лунного совуха правильно написанный
макрос .! для того чтоб не было формы коровы а сразу из совы в сову

Подобная логика баффов действует на баффы имеющие значение "мощности баффа" и время действия баффа. В этом случае при повторном касте баффа он заменяется на себя же, так как длительность "нового" баффа будет длительности "старого" баффа.

В случае же с формой друида длительность действия отсутствует, следовательно идет рповерка только по силе баффа.
Логика игровой механики по типу "на мне есть кепка с надписью "Я сова". Чтобы ее надеть нужно ее для начала снять"

**Comment by Ghostly2009** [comment]
Это ваша версия происходящего и ей есть место быть.Но остальные формы
устроены  по другому.И мне бы не хотелось развивать эту тему.Я просто хочу
чтобы  форму совы не оставили обделённой и приспособили к игре как это уже
было сделано с другими формами.

8 июля 2017 г., 13:56 пользователь TepaMeTp <notifications@github.com>
написал:

**Comment by ForesterDev** [comment]
Складывается ощущение, что подобная механика заложена в клиент. Это заметно, что если юзать макрос /cast !Походный облик и другие подобные - то в панели бафов пропадают иконки, связанные с обликами и заново появляются. То есть происходит снятие, и заново наложение ауры. Для облика лунного совуха - не происходит снятие ауры совуха и наложение. То есть как такового решифта не происходит. Поэтому в данном случае нужно искать пруфы, что подобной проблемы не было на оффе

**Comment by Ghostly2009** [comment]
с формой дерева так же не работает снятие замедления при рекасте формы. Пример: ''/cast !Древо Жизни". Как и с формой совы мана на применение формы забирается,а в остальном без изменений.

**Comment by TepaMeTp** [comment]
Однако вы шустрее, чем я думал, опередили. В целом остается только искать видео с оффа в актуальном патче (хотя можно и принять внимание логику "большая часть работает правильно, баг с получаемыми с талантов", но это уже решать не обычным юзверям)

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
