### ISSUE TITLE
[Задание] ID 13141 - Битва за Вершину Рыцарей

### ISSUE THREAD

**Issue by Edmenen** [VirginTeam/VirginCore#340]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не возможно установить знамя в груду черепов из-за того что там уже находиться установленное. Ивент как будто бы зацикливается, треш продолжает ресаться и в итоге его там накапливается огромная куча. Уже установленное знамя пропадает только после ребута сервера.

**Что работает не так?**

Нельзя установить знамя, а соответственно пройти квест.

**Как должно работать?**

Устанавливаем знамя, запускается ивент, убиваем появившийся треш, квест пройден.

**Текущее обновление ядра:**

Build 162 2017-07-03 14:02:08 +0400

**Comment by Riazarre** [comment]
Исправлено, проверяйте после перезагрузки.
