### ISSUE TITLE
[Задание] ID 12094 - Спящая сила

### ISSUE THREAD

**Issue by Random12025331** [VirginTeam/VirginCore#344]
**Описание:**
Отсутствует первый камень.
http://ru.wowhead.com/quest=12094

**Что работает не так?**
Из-за того, что первого камня нет квест-итем не срабатывает (при том, что каст проходит) и не дает завершить квест

**Как должно работать?**
Там где должен быть первый камень, видимо должен быть первый камень, видео в комментариях к заданию на wowhead является подтверждением.

**Шаги для воспроизведения ошибки:**
1. Взять квест
2. Долететь до места где должен быть первый камень
3. Обнаружить его отсутствие

**Текущее обновление ядра:**
Build 162 2017-07-03 14:02:08 +0400
WoW Circle 3.3.5a x1 PvE

**Comment by Kodekc** [comment]
Все камни на месте. Попробовал сделать задание, всё выполнилось, не воспроизводится ошибка.
