### ISSUE TITLE
[Задание] ID 9063 - Землепроходец Торва

### ISSUE THREAD

**Issue by DualPain** [VirginTeam/VirginCore#347]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не могу получить квест Землепроходец Торва

**Что работает не так?**

НПС Башана Рунический Тотем не дает этот квест

**Как должно работать?**

НПС Башана Рунический Тотем должна дать этот квест

**Шаги для воспроизведения ошибки:**

Подойти к квест гиверу

**Текущее обновление ядра:**

Build 162 2017-07-03 14:02:08 +0400

**Comment by Riazarre** [comment]
Ссылку на задание добавьте.
Заголовок переоформите по шаблону.

**Comment by Scoren** [comment]
http://s019.radikal.ru/i618/1707/f7/85fe9dff8d34.jpg

закройте репорт

**Comment by DualPain** [comment]
а продолжение цепочки взять можете? потому что этого квеста у меня нет, а Торва дает только 2 других квеста
