### ISSUE TITLE
[Задание] ID 12555 - Оплетающие сети

### ISSUE THREAD

**Issue by Random12025331** [VirginTeam/VirginCore#349]
**Описание:**
По заданию нужно взять в таргет летающие сеятели чумы, нажать на квеститем и сеятель после каста должен уничтожиться ( это видно на видео в комментариях)
http://ru.wowhead.com/quest=12555

**Что работает не так?**
Каст квеститема проходит, но прогресс не засчитывается. И взрыва тоже нет.

**Как должно работать?**
После каста должен произойти взрыв (как на видео), и за считаться прогресс.

**Шаги для воспроизведения ошибки:**
1. Взять квест
2. Найти сеятель
3. Нажать на квеститем и увидеть, что ничего не происходит.

**Текущее обновление ядра:**
Build 162 2017-07-03 14:02:08 +0400
WoW Circle 3.3.5a x1 PvE

**Comment by Riazarre** [comment]
Дубликат
#173
