### ISSUE TITLE
Задание [Месть короля Бурь]

### ISSUE THREAD

**Issue by ar4i2018** [VirginTeam/VirginCore#350]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
Задание [[Месть короля Бурь]](http://ru.wowhead.com/quest=12919#comments)

**Что работает не так?**

Когда жмешь кнопку, чтобы сесть на великана, происходит [это](http://savepic.ru/14822083.jpg), а когда жмешь еще раз, персонаж оказывается где-то между первым и вторым великаном и не может двигаться.
**Как должно работать?**

[Видео](https://www.youtube.com/watch?v=zlw0L36RYKE&t=12s)

**Текущее обновление ядра:**

Build 162 2017-07-03 14:02:08 +0400

**Comment by Riazarre** [comment]
Дубликат
#53
