### ISSUE TITLE
[npc] id 7572 - Павший Герой Орды

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/VirginCore#355]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Послушайте, как павший герой Орды рассказывает свою историю.

**Что работает не так?**

После завершения квеста Болотный говорун, НПЦ Павший герой Орды должен давать задание Печальная история после которого открывается еще одна цепочка.

**Как должно работать?**

Квест должен быть, но НПЦ его не даёт, ожидалась выдача следующего квеста, начинающего новую цепочку. Когда-то давно обращались с такой же проблемой, но решения я так и не нашел. Вот тикет: http://forum.wowcircle.com/showthread.php?t=612763
Обращался к модератору форума Логон 3 Kusakabe лично в публ.сообщ, и он перенаправил меня к DB_Killer, а этот, увы меня проигнорировал. Такая беда наблюдается только у стороны орды, со стороны альянса другой преквест был сдан, и Павший Герой выдал нужное Нам задание. 
Прикрепляю скриншот с доказательствами EverQuest, который подтверждает то, что ранее это квест я не делал...
![wowscrnshot_071817_183724](https://user-images.githubusercontent.com/27158518/28326123-91b2cafe-6be8-11e7-8f65-dd052dfdb741.jpg)

**Шаги для воспроизведения ошибки:**

1. Сдать преквест http://wowroad.info/?quest=2623
2. Взять квест http://wowroad.info/?quest=2801, он открывает еще одну цепь заданий.
3. Послушать Павшего Героя http://wowroad.info/?npc=7572, сдать кв, взять следующий.
**Текущее обновление ядра:**

Build 162 2017-07-03

**Comment by Scoren** [comment]
Цепочка полностью исправна. Проверено 21.07.17

**Comment by odino4estvo** [comment]
Цепочка не исправлена!

**Comment by odino4estvo** [comment]
Возможно она исправна... Но мне данный нип [http://wowroad.info/?npc=7572](url) не выдает следующий квест [http://wowroad.info/?quest=2801](url) после сдачи преквеста [http://wowroad.info/?quest=2623](url), который выдавал [http://wowroad.info/?npc=7643](url)
Я вновь подтверждаю свою правоту свежими скриншотами на сей момент!
По порядку! 
Скрин №1 
![1](https://user-images.githubusercontent.com/27158518/28477865-a3d59b3a-6e5e-11e7-9fd1-f1736fb12f92.jpg)
Я облазил всю пещеру (три раза!) где водятся [http://wowroad.info/?npc=950](url), перебив их всех, с них данный итем [http://wowroad.info/?item=8463](url) (внимание!!!) со 100% дропом этой вещи не выпало! Ни с одного нип'а! Могу смело заявить, что это квест я уже сдавал! Да, да, сдавал! Я просто хочу доказать, что может быть именно для моего персонажа это квест баганулся... Об этом позже.
Скрин №2
Эта картинка подтверждает следующее, как я и написал, что квест на приказы я сдавал, я брал его у [http://wowroad.info/?npc=7643](url)! Даже если я пропустил бы его, как правило, над ним бы висел желтый восклицательный знак... Справа EerQuest доказывает, что квест сдан!
![2](https://user-images.githubusercontent.com/27158518/28478054-6887f702-6e5f-11e7-967f-bd82e10ac3f9.jpg)
Скрин №3
Прикладываю скрин как был в тикете ранее, уже свежий, опять же, повторюсь, квест [http://wowroad.info/?quest=2801](url) у [http://wowroad.info/?npc=7572](url) после сдачи ему же преквеста [http://wowroad.info/?quest=2623](url), а именно этой вещи [http://wowroad.info/?item=8463](url), следующего квеста нет. Опять же повторюсь, на форуме циркуля, была проблема не одного у меня, там даже прикрепляли видео с Ютуба, убедительная просьба ознакомится с видео [https://www.youtube.com/watch?v=v4jxm_fr7RM&feature=youtu.be](url)
У меня же аналогичная проблема... Вопрос, как быть? Что сделать что бы Павший Герой выдал следующее задание на огромную и интересную цепь заданий?! Жду Ваших отзывов, решений. Меня ответ Ваш, увы, не удовлетворил... Спасибо заранее...

**Comment by Riazarre** [comment]
Оформите запрос в Центре поддержки http://helpl3.ru
Проблема единичная, только с Вашим персонажем.

**Comment by odino4estvo** [comment]
Спасибо! Обратился туда! В течении суток решили мою проблему! Прикладываю скрин!
Просто добавили задание в квестлист, все получилось! Отдельная благодарность тому, кто помог с моей проблемой! ^_^
![2](https://user-images.githubusercontent.com/27158518/28586241-c1c46a02-717b-11e7-8d66-cd9dcfe46ac1.jpg)
