### ISSUE TITLE
[Задание] ID 12967 - Сражение со стихиями

### ISSUE THREAD

**Issue by Random12025331** [VirginTeam/VirginCore#356]
**Описание:**
По квесту надо убить 10 Пылающих загробников. 
http://ru.wowhead.com/quest=12967

**Что работает не так?**
Они не засчитываются при убийстве. И вообще не помечены как квестовые мобы. 

**Как должно работать?**
Их убийства должны засчитываться, а сами мобы должны быть квестовыми.

**Шаги для воспроизведения ошибки:**
1. Взять квест
2. Найти мобов
3. Убить и увидеть, они не засчитываются.

**Текущее обновление ядра:**
 Build 162 2017-07-03 14:02:08 +0400
WoW Circle 3.3.5a x1 PvE

**Comment by nordwindd** [comment]
Меньше недели назад делал этот квест. Работал согласно коментария из вовхеда. Подозреваю что ТС просто убивал загробников вручную.

От sadsmile (4,212 – 12·35) 2008-11-29 (Обновление 3.0.3) 
Садимся на гиганта Храппи

берем снежок из кучи используя первое умение на панели, кидаем снежок в элема вторым.
если гигант засыпает - будим его пятым скиллом.

**Comment by Scoren** [comment]
Вы бы хоть комментарии на вовхеде к заданию прочитали. Садитесь в храппи и выполняете задание выполняете. На край на том же вовхеде видео посмотрите.
