### ISSUE TITLE
[NPC] id 89341 - Магистр Горухад 

### ISSUE THREAD

**Issue by Uruu2013** [VirginTeam/VirginCore#358]
Описание:
Проблема в обнаружении нипа.
(Не могу сдать квест)

Что работает не так?

Я проходил 2 квеста у этого нипа (Искусство сервировки) и (Мастер Миксологии). Всё сделал, но когда хотел сдать квесты, нипа стало не видно. 

Как должно работать?

Я должен был увидеть нипа и сдать ему квесты.

Шаги для воспроизведения ошибки:
1.Беру квесты.
2.Прохожу их.
3.Обнаруживаю нипа и сдаю квесты.
Текущее обновление ядра:

Build
WoW Circle 7.1.5 x4 PvE

2017-07-19

22:30:52 +0030

**Comment by Riazarre** [comment]
Это баг-трекер миров Logon 3, у нас нет миров Легиона.
