### ISSUE TITLE
[Задание] id 12237 - Полет защитника Стражей Зимы

### ISSUE THREAD

**Issue by RaGeNemezid** [VirginTeam/VirginCore#362]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
После выполнения квестовой цепочки которая начинается с задания "Пропавший курьер" и завершения задания "Наксрамас и падение крепости Стражей Зимы"
Задание "Полет защитника Стражей Зимы" не выдается нпс Командир грифонов Урик

**Что работает не так?**

Нет продолжения квестовой цепочки "Полет защитника Стражей Зимы" 

**Как должно работать?**

После завершения задания "Наксрамас и падение крепости Стражей Зимы" должна продолжатся квестовая цепочка и должны открываться дополнительные задания.

**Шаги для воспроизведения ошибки:**

1. Начать цепочку заданий начиная с "Пропавший курьер"
http://ru.wowhead.com/quest=12157
2. Выполнить задание "О предателях и предательстве"
3. Выполнить задание "Главнокомандующий Халфорд Змеевержец"
4. Завершить задание "Наксрамас и падение крепости Стражей Зимы"

**Текущее обновление ядра:**

Logon 3 WowCircle Development
Последнее обновление ядра: Build 162 2017-07-03 14:02:08 +0400

**Comment by Scoren** [comment]
дубликат https://github.com/VirginTeam/VirginCore/issues/233
