### ISSUE TITLE
quest=9051 [Испытание яда]

### ISSUE THREAD

**Issue by gooddruid** [VirginTeam/VirginCore#363]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
Уколите дьявозавра колючкой дьявозавра. По выполнении задания вернитесь к Землепроходцу Торве.
Добавьте описание проблемы здесь.

**Что работает не так?**
нет ни одного дьявозавра на всей локации. 
Фактический результат — тот, который вы наблюдаете

**Как должно работать?**

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
цепочка кв для друида

**Шаги для воспроизведения ошибки:**

1. Шаг один найти дьявозавра
2. Шаг два уколоть дьявозавра колючкой дьявозавра
3. Шаг три по выполнению задания вернуться  к Землепроходцу Торве.

**Текущее обновление ядра:**
Build 162 2017-07-03 14:02:08 +0400
Live Server 
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by Scoren** [comment]
http://s012.radikal.ru/i319/1707/e1/41e02aa1cd99.jpg

 о чем речь вообще?
