### ISSUE TITLE
[Задание] ID 12330 - Слабое место Анатолия

### ISSUE THREAD

**Issue by dener5878** [VirginTeam/VirginCore#369]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Татьяна не усыпляется "усыпляющим дротикам". А когда довозишь ее до Саши или Анатолия, она убегает через текстуры назад. И Татьяна горит как союзный моб.

**Что работает не так?**

Татьяна сразу сидит на лошади, ее нельзя усыпить, лошадью надо управлять самому, когда привозишь ее в "торговая лавка белой сосны" она убегает назад на свое место.  

**Как должно работать?**

Татьяна стоит ряжом со своим конем и горит как враждебный моб. Выстрелить в нее "усыпляющим дротикам. После чего она усыпляется и ложится на своего коня. После этого Коня можно оседлать и он доставляет тебя до "торговая лавка белой сосны". И квест засчитывается. Вот ссылка на видео как он должен работать https://www.youtube.com/watch?v=3NgXmbR5xic  

**Шаги для воспроизведения ошибки:**

1. Выполняем цепочку квестов которые приводят к Саше
2. Берем у Саши квест "Слабое место Анатолия"
3. Прибегаем в "деревню солнцестояния"
4. И наблюдаем эту картину которая была описана ранее 

**Текущее обновление ядра:**

[15:00:36] Logon 3 WowCircle Development
[15:00:36] Последнее обновление ядра: Build 162 2017-07-03 14:02:08 +0400
[15:00:36] Игроков онлайн: 2115 (максимум: 4783). Игроков в очереди: 0 (максимум: 0).
[15:00:36] Продолжительность работы сервера: 1 Day(s) 22 Hour(s) 5 Minute(s) 18 Second(s).
[15:00:36] Серверная задержка: 25.
[15:00:36] Следующее начисление очков арены: 30.07.2017  10:22
wow lich king 3.3.5.a PVE x1

**Comment by Riazarre** [comment]
Исправлено, будет применено после перезагрузки сервера.
