### ISSUE TITLE
[Задание] ID 2969 - Свободу всем живым существам!

### ISSUE THREAD

**Issue by Luchass** [VirginTeam/VirginCore#37]
**Описание:**

http://ru.wowhead.com/quest=2969
http://wowroad.info/?quest=2969

**Что работает не так?**

Не засчитывает выполнение задания

**Как должно работать?**

Должно засчитывать критерий задания

**Шаги для воспроизведения ошибки:**

1. Взять задание
2. Сопроводить хамелеонов
3. Увидеть, что задание не засчиталось

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
