### ISSUE TITLE
[Предмет] ID 33149 - Формула чар для плаща - незаметность

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/VirginCore#370]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://ru.wowhead.com/item=33149 отличается чарка после изучения рецепта
**Что работает не так*
После изучения рецепта нет 8 агилы

**Как должно работать?**

После изучения должно быть улучшение незаметности и 8 агилы
**Шаги для воспроизведения ошибки:**

1. Выбить рецепт
2. Изучить его
3. Сравнить описание рецепта и что вы изучили

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by Kodekc** [comment]
Изменено в 4.0.3 и только после этого стал давать прибавку к характеристикам.
