### ISSUE TITLE
Найти преступника не работает

### ISSUE THREAD

**Issue by Accycc** [VirginTeam/VirginCore#372]
сервер х3
не работает http://ru.wowhead.com/quest=12855 без которого не возможно получение цепо4ки кв и ачивы для хранителя
http://ru.wowhead.com/quest=12855 после того как заюзал  http://ru.wowhead.com/item=41430 я сажусь на волка но он не везет.
Сам добираюсь до нужной пещеры но ВЫСЛЕДИТЬ ВОРА не засчитывается

**Comment by Riazarre** [comment]
Дубликат, + не оформлено.
#275
