### ISSUE TITLE
[Игровая механика] Ошибка репутации с Сынами Ходира 

### ISSUE THREAD

**Issue by kikos2** [VirginTeam/VirginCore#373]
Что работает не так?
После прохождения [2-х цепочек квестов](http://forum.wowcircle.com/showthread.php?t=118431) репутация с Сынами Ходира стала мгновенно вражеской 28600. Ошибка не моя а именно сервера.. Ник персонажа Кикос. Ожидаю решение проблемы или подсказку по решению т.к. эта фракция мне необходима
Как должно работать?
После сдачи квеста Ториму, отрокется новая фракция Сыновья Ходира, а уровень репутации с ними будет Нейтральный 2000/3000.
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
Новая фракция Сыновья Ходира с нейтральной репутацией
Текущее обновление ядра:
Logon3
Build 163 2017:07:25 11:59:12 +0400 проблема случилась до обновления этого ядра.

**Comment by Scoren** [comment]
Уровень репутации нейтральным становится после выполнения ВСЕЙ цепочки, а именно возобновление союза.
Репорт пустышка, не пруфов, не знания игрового мира.

**Comment by Ewropa** [comment]
этот гайд написан для логона 1, у нас нужно делать эти задания http://forum.wowcircle.com/showthread.php?t=513109
после сдачи заданий 12956 и 12915 у Вас репутация будет уважение
Вы скорее всего не сделали задание http://ru.wowhead.com/quest=12922
