### ISSUE TITLE
[NPC] Укротитель ветрокрылов Жаубо - неправильная фракция

### ISSUE THREAD

**Issue by Hellsingoff** [VirginTeam/VirginCore#374]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

По многолетнему опыту на офе и нескольких пиратках NPC **Укротитель ветрокрылов Жаубо** (http://wowroad.info/?npc=35093) должен иметь фракцию Оргриммар. Это уже многие годы позволяет учить достаточно дорогую вещь - полёты за 5000 золотых со скидкой от столицы орды. Раньше на данном сервере так и было.

**Что работает не так?**

По неизвестной мне причине фракция данного NPC была изменена на Траллмар.

**Как должно работать?**

Фракция должна быть Оргриммар - скидка должна работать именно от Оргриммара.

**Шаги для воспроизведения ошибки:**

1. Шаг один
Захотеть обучиться перелётам на 70 уровне
2. Шаг два
Набить почтение Оргриммара
3. Шаг три
Офигеть, что скидка от Оргриммара отсуствует, а NPC переметнулся к другой фракции.
4. Шаг четыре, дополнительный
Прилететь в Оплот Чести альянса и понять, что их **Харген Бронзокрыл** (http://wowroad.info/?npc=35100) имеет правильную фракцию с работающей скидкой Штормграда. Неприятный дисбаланс налицо.

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

Сервер живой, не тест.

**Comment by Kodekc** [comment]
Когда я перезаселял Траллмар, допустил эту ошибку. Фракция NPC установлена, как Оргриммар. Изменения будут применены в ближайшем обновлении.
