### ISSUE TITLE
[Задание] ID 5528 - Лучшее пойло Гордока

### ISSUE THREAD

**Issue by Luchass** [VirginTeam/VirginCore#38]
**Описание:**

http://ru.wowhead.com/quest=5528
http://wowroad.info/?quest=5528

**Что работает не так?**

a) После нажатия кнопки "завершить" - ничего не происходит. Задание попросту не сдаётся.
b) Сдаётся Король Гордок

**Как должно работать?**

a) Задание должно сдаваться.
b) Задание должно сдаваться Топотун Криг

**Шаги для воспроизведения ошибки:**

1. Убить Короля Гордока
2. Попытаться сдать квест

**Comment by ForesterDev** [comment]
Исправлено, тестируйте после обновления
