### ISSUE TITLE
[Предмет] ID 16768 - Лекарственный мешочек фурболгов

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/VirginCore#380]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Нельзя использовать отхилку http://wowroad.info/?item=16768 на 19 уровне.

**Что работает не так?**

Не отхиливает на 19х уровнях

**Как должно работать?**

Отхил от http://wowroad.info/?item=16768 должен работать на 19х уровнях и вы

**Шаги для воспроизведения ошибки:**

1. найти 80го для кача репы
2. добраться живым до оскверненного леса
3. качнуть репу с древобрюхами до равнодушия
4. попробовать кого-то отхилить им

**Текущее обновление ядра:**

Последнее обновление ядра: Build 163 2017-07-25 12:38:12 +0400

**Comment by Riazarre** [comment]
http://www.wowhead.com/g00/spell=20631/furbolg-medicine-pouch
Носить можно с первого уровня, лечить - с 50.
