### ISSUE TITLE
[Задание] ID № - Против воли рока

### ISSUE THREAD

**Issue by mirageboys** [VirginTeam/VirginCore#381]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не возможно пройти квест "Против воли рока" ( http://wowroad.info/?npc=32346 ) и соответствующую цепочку квестов.

**Что работает не так?**

При телепорте в Оргриммар город не переходит в соответсвующую фазу, в следствии чего мгновенно убивает Тралл и его охрана.

**Как должно работать?**

При телепорте в Оргриммар производится катсцена, в которой Тралл останавливает стражу от нападения и становится мирным нпц с которым можно поговорить. Всё можно увидеть на видео: https://www.youtube.com/watch?v=yXnAZZC6OTU

**Шаги для воспроизведения ошибки:**

1. Берём квест у Вариана Ринна ( http://wowroad.info/?npc=29611 ) после цепочки квестов у врат гнева.
2. Просим телепорт у Джайны( http://wowroad.info/?npc=32346 ).
3. Телепортируемся.
 
**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by Devinette** [comment]
Дубль
[#50](https://github.com/VirginTeam/VirginCore/issues/50)
