### ISSUE TITLE
[Задание] ID 8985/8986/8987/8988 - Еще одна важная составляющая заклинания

### ISSUE THREAD

**Issue by murdalak** [VirginTeam/VirginCore#382]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

NPC не даёт следующий квест

**Что работает не так?**

После выполнения [Я вижу в твоем будущем остров Алькац...](http://wowroad.info/?quest=8970) [Бодли](http://wowroad.info/?npc=16033) не выдает квест

**Как должно работать?**

После выполнения [Я вижу в твоем будущем остров Алькац...](http://wowroad.info/?quest=8970) [Бодли](http://wowroad.info/?npc=16033) должен выдать один из квестов:
[Еще одна важная составляющая заклинания](http://wowroad.info/?quest=8985)
[Еще одна важная составляющая заклинания](http://wowroad.info/?quest=8986)
[Еще одна важная составляющая заклинания](http://wowroad.info/?quest=8987)
[Еще одна важная составляющая заклинания](http://wowroad.info/?quest=8988)

**Шаги для воспроизведения ошибки:**

1. Делаем квест
2. Возвращаемся к Бодли
3. Сдаём квест

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by murdalak** [comment]
Не раобтает даже не сам квест, а его просто нельзя взять

**Comment by Scoren** [comment]
я уже отвечал на репорт, у задания два преквеста, https://github.com/VirginTeam/VirginCore/issues/223 пользуйтесь вовхедом. В английских комментариях все подробно описано

**Comment by murdalak** [comment]
Так я сделал оба преквеста, но этот квест всё равно не дают
