### ISSUE TITLE
[Задание] ID 12244 - Починка крошшеров

### ISSUE THREAD

**Issue by DarkCloud069** [VirginTeam/VirginCore#384]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Невозможно выполнение квеста.

**Что работает не так?**

Невозможно сесть на крошшер для доставки его к квестгиверу.

**Как должно работать?**

https://www.youtube.com/watch?v=vtJJzzvvzfo

**Шаги для воспроизведения ошибки:**

1. Прилететь в седые холмы и взять квест http://ru.wowhead.com/quest=12244
2. Полететь к крошшерам для выполнения задания.
3. Обнаружить что не получается сесть на крошшер.

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by Scoren** [comment]
дубликат очередной. https://github.com/VirginTeam/VirginCore/issues/228
