### ISSUE TITLE
[Задание] ID 7046 - Скипетр Келебраса

### ISSUE THREAD

**Issue by Luchass** [VirginTeam/VirginCore#39]
**Описание:**

http://ru.wowhead.com/quest=7046
http://wowroad.info/?quest=7046

**Что работает не так?**

Не появляется книга, которую надо прочесть (Object Id 178965). Ивент задания зависает.

**Как должно работать?**

Книга должна появляться

**Шаги для воспроизведения ошибки:**

1. Взять квест
2. Сопроводить Келебраса

**Текущее обновление ядра:**

PTR Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Проверяйте после обновления
