### ISSUE TITLE
[Задание] ID 12980 - Секрет доспехов

### ISSUE THREAD

**Issue by Edmenen** [VirginTeam/VirginCore#398]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Квестовый нип убегает сквозь стену

**Что работает не так?**

http://ru.wowhead.com/npc=30190
Квестовый нип после разговора убегает куда то сквозь стену, что делает невозможным прохождение данного квеста другими игроками. Появляется только после ребута.

**Как должно работать?**

Взял квест, поговорил с нипом, сдал квест.

**Текущее обновление ядра:**

[21:35:26] Последнее обновление ядра : Build 163 2017-07-25 11:59:12 +0400

**Comment by Riazarre** [comment]
Проблема именно в НПЦ, само задание работает.
#165 репорт по НПЦ.
Пока не исправили, пишите тикет в игре, ГМы вернут его на место.
