### ISSUE TITLE
[Задание] ID 1090 - Приказы Геренцо

### ISSUE THREAD

**Issue by Nimlotnik** [VirginTeam/VirginCore#401]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Задание - [[Приказы Геренцо]](http://wowroad.info/?quest=1090)

**Что работает не так?**

[НИП](http://wowroad.info/?npc=4276) не начинает копать руду в следствии чего нельзя выполнить квест

**Как должно работать?**
[НИП](http://wowroad.info/?npc=4276) начинает копать, появляются разные НИП из племени Ветрорезов, после уничтожения 2х волн атаки - срабатывает триггер выполнения квеста.

**Шаги для воспроизведения ошибки:**

1. Взять квест [[Приказы Геренцо]](http://wowroad.info/?quest=1090) по координатам 71.86 60.02 предварительных требований для взятия квеста нет.

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by Devinette** [comment]
Дубль
https://github.com/VirginTeam/VirginCore/issues/236
