### ISSUE TITLE
[Задание] ID 25212 - Разведать обстановку

### ISSUE THREAD

**Issue by POVELITELnumber1** [VirginTeam/VirginCore#402]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не работает задание [Разведать обстановку](http://wowroad.info/?quest=25212)

**Что работает не так?**

При сбрасывании [Радиометрозиметр](http://wowroad.info/?item=52541) в [шахты](http://wowroad.info/?npc=39420), ничего не происходит - не засчитывается.

**Как должно работать?**

После того, как взял кв, нужно "поговорить" с [Молнией](http://wowroad.info/?npc=39396). Пролетая над [шахтами](http://wowroad.info/?npc=39420) нужно юзать [Радиометрозиметр](http://wowroad.info/?item=52541) (сбрасывать туда). Всего по кв нужно сбросить 3.

**Шаги для воспроизведения ошибки:**

1. Взять квест [Разведать обстановку](http://wowroad.info/?quest=25212)
2. Юзануть [Молнию](http://wowroad.info/?npc=39396) и полететь.
3. Попытаться сбросить [Радиометрозиметр](http://wowroad.info/?item=52541) в [шахты](http://wowroad.info/?npc=39420)

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by Luchass** [comment]
У меня работает
https://youtu.be/xhJU-ylj4hY

**Comment by POVELITELnumber1** [comment]
Проверил только что. Пытался 3 раза - никакого эффекта. А ты точно на этом логоне делал?

**Comment by Luchass** [comment]
На Open Test, в чате на видео написано.

**Comment by Luchass** [comment]
Крошка (GM) говорит, что у нее на x1 тоже работает. Может вы не правильно делаете задание?

**Comment by POVELITELnumber1** [comment]
Беру квест, юзаю вертолёт, скидываю кв итем в шахты с зелёным дымом. Я уже и пешком туда прибежал, пробовал вручную - они залетают прям в шахты, но ничего не засчитывается. Пробовал и верхние шахты и на земле. Удалял кэш, делал анэррор - всё бестолку...

**Comment by Devinette** [comment]
Пришлите видео с Вашим прохождением квеста

**Comment by POVELITELnumber1** [comment]
Задание действительно работает - только что сделал другим персонажем, но первым по-прежнему не могу. Делаю всё то же самое, но не засчитывается. Из-за чего это может быть? Отменял, брал заново, делал антиеррор, удалял кэш, в рейде не состою. Даже не представляю, почему не работает на одном персонаже.
