### ISSUE TITLE
[Задание] ID 834 -Ветра пустыни

### ISSUE THREAD

**Issue by JenHak** [VirginTeam/VirginCore#414]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
http://wowroad.info/?quest=834
Дуротар, 7+ левл.
Квест берется, мешки есть, но не кликабельны. Мешок припасов невозможно получить.

**Что работает не так?**

Объект "Украденный мешок с припасами" не кликабелен.

**Как должно работать?**
**Шаги для воспроизведения ошибки:**

1. Взять квест
2. Подойти к мешкам
3. Потыкаться у дригих мешков.

**Текущее обновление ядра:**
Logon 3 WowCircle Development
Bild 163 2017-07-25 11:56:12 +0400

**Comment by Devinette** [comment]
Квест работает
[22:16:59] Ваша добыча: [Мешок припасов].
[22:17:06] Ваша добыча: [Мешок припасов].

**Comment by JenHak** [comment]
Прошу прощения, Может ошибка клиента. Кеш удалял, аддоны выключил(переименовал папку).
Не кликается... и всё тут.. Спасибо за ответ.

**Comment by JenHak** [comment]
Проблема была в пати! Были в группе, настройки стандартные. Квест только у меня. Только вышел, сразу активные стали. Никогда такого не было. Лутали сундуки, если что редкое кидались кости. А тут квестовый недоступен..
