### ISSUE TITLE
Безрассудство

### ISSUE THREAD

**Issue by Ghostly2009** [VirginTeam/VirginCore#415]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Способность Безрассудство работает не согласно описанию.

**Что работает не так?**

Согласно описания,а оно звучит так:
Повышает вероятность нанесения критического удара каждой из 3 следующих атакующих способностей на 100%, но увеличивает получаемый воином урон на 20%. Время действия – 12 sec.
Способность в придачу к этому эффекту даёт невосприимчивость к страху(аналогично другой способности война Ярость берсерка)

**Как должно работать?**
Считаю,что способность не соответствует описанию и обладает завышенными характеристиками.
На мой взгляд эффект невосприимчивость к страху тут лишний,поскольку воин имеет не зря другую способность дающую этот эффект. 

**Шаги для воспроизведения ошибки:**

**Текущее обновление ядра:**
Build 163 2017-07-25 11:59:12 +0400

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by Devinette** [comment]
Оформите тему, согласно правилам.
Необходимы доказательства неверной работы.

**Comment by Riazarre** [comment]
Способность работает корректно.
Ваши мнения отправляйте в Близзард, чтобы они правили механики.
