### ISSUE TITLE
[Задание] ID 9433 - Проба из Лунного колодца

### ISSUE THREAD

**Issue by hylhart** [VirginTeam/VirginCore#419]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Квест "Проба из Лунного колодца" http://ru.wowhead.com/quest=9433, не работает.

**Что работает не так?**

Игрок садится на Роботроном 3000 с устройства управления Роботроном, которым управляет игрок. Он должен набрать немного воды из Лунного колодца, но не работает скилл "Сбор воды" http://ru.wowhead.com/spell=29992 и вернуться обратно

**Как должно работать?**

Роботроном 3000, которым управляет игрок, подходит к Лунному колодцу, игрок жмет скилл "Сбор воды", робот набирает воду и игрок идет обратно к устройству управления.

**Шаги для воспроизведения ошибки:**

1. Взять квест
2. На границе Тысячи Игл и Таланаара  игрок должен найти устройство управления Роботроном 3000
3. Взаимодействовать с устройством, после игрок начинает управлять Роботроном
4. Подойти к колодцу.
5. Нажать скилл "Сбор воды" (дальше идет ошибка и вода не набирается).

**Текущее обновление ядра:**
Logon 3 WowCircle Development
Последнее обновление ядра: Build 163 2017-07-25 11:59:12 +0400
х1

Очень жду рабочего квеста, с Уважением, Хулхарт

**Comment by Riazarre** [comment]
Хм, в 160 билде работало.
#271

**Comment by Ewropa** [comment]
Задание работает, баг не воспроизводится
