### ISSUE TITLE
[Рейд] Склеп Аркавона (ID 31125 Аркавон Страж Камня)

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#42]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

Отсутствует каст (SPELL_CAST_SUCCESS) [Резкий наскок ID 58960](http://wowroad.info/?spell=58960) предшествующий нанесению урона от [Резкий наскок ID 58963](http://wowroad.info/?spell=58963)
```
4/7 12:58:19.075  SWING_DAMAGE,0xF1500079953A40A1,"Аркавон Страж Камня",0x10a48,0x00000000004540B6,"Миссисболтон",0x512,12734,0,1,0,0,0,nil,nil,nil
4/7 12:58:19.692
SPELL_DAMAGE,0x0000000000453AD5,"Skywillburn",0x511,0xF1500079953A40A1,"Аркавон Страж Камня",0x10a48,42914,"Ледяное копье",0x10,221,0,16,55,0,0,nil,nil,nil
4/7 12:58:20.392  SPELL_DAMAGE,0xF1500079953A40A1,"Аркавон Страж Камня",0x10a48,0x0000000000453AD5,"Skywillburn",0x511,58963,"Резкий наскок",0x1,4973,0,1,0,0,0,nil,nil,nil
```

**Как должно работать?**

```
[00:27:27.660] Archavon the Stone Watcher casts Crushing Leap
[00:27:28.882] Archavon the Stone Watcher Crushing Leap Däs 3414
[00:27:28.882] Archavon the Stone Watcher Crushing Leap Littlemaan 2949
[00:27:28.882] Archavon the Stone Watcher Crushing Leap Deathrize 4363
```

**Текущее обновление ядра:**

PTR: Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
