### ISSUE TITLE
[NPC] ID 33350 - Мимирон

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/VirginCore#436]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Запуск босса в обычном и героическом режиме.

**Что работает не так?**

Босс в обычном режиме не запускается в течении 3-5 минут. Происходит удар по нему, он прыгает в танк и сидит там будучи неактивным. 
В героическом режиме после нажатия кнопки, происходит несколько залпов огнем и только потом босс становится активным. Так же возможно босс запускается при помощи питомцев дк, ханта и лока, поскольку он агрился сначала на них.

**Как должно работать?**

Босс должен нормально запускаться и не багаться при вайпах в героическом режиме, баги при вайпах не могут починить уже лет 5.

**Шаги для воспроизведения ошибки:**

1. Сагрить босса/Нажать кнопку
2. Ничего не происходит/Выбросы напалма
3. Ничего не происходит/Агрится на питомцев

**Текущее обновление ядра:**

Logon 3 WowCircle Development
[10:01] Ïîñëåäíåå îáíîâëåíèå ÿäðà: Build 163 2017-07-25 11:59:12 +0400

**Comment by Kodekc** [comment]
Исправлен баг с невозможностью стартовать обычный режим боя с Мимироном
Переписана механика эвейда босса Мимирона - теперь в случае вайпа рейда босс и суммоны будут полностью исчезать и восстанавливаться в исходное состояние, что должно устранить проблему забагивания боя на инсте
