### ISSUE TITLE
[NPC] id 25328 - Тенелов Лютер

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#448]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

По неустановленным причинам может оказаться под текстурами.

**Как должно работать?**

Должен находиться только на своем месте (НПЦ в принципе не должен никуда перемещаться) http://ru.wowhead.com/npc=25328#map

**Текущее обновление ядра:**

Virgin Build 163

**Comment by Ewropa** [comment]
старая тема на форуме http://forum.wowcircle.com/showthread.php?t=531511

**Comment by Riazarre** [comment]
Этот НПЦ никоим образом не относится к Сынам Ходира

**Comment by Riazarre** [comment]
Исправлено, будет применено после обновления.
