### ISSUE TITLE
Испытание чемпиона. Стартовый ивент

### ISSUE THREAD

**Issue by Rorshah** [VirginTeam/VirginCore#449]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://wowroad.info/?npc=35004
Чтобы стартовать ИЧ нужно поболтать с чуваком по ссылке выше и начинается 
5 минут трешевого разговора.
Это не есть хорошо. Должна быть альтернатива запустить сразу инст.

**Что работает не так?**

У Джерен Верный Солнцу всего один выбор в диалоге: "Давай помучаемся"

**Как должно работать?**

Должно быть два выбора:
1. "Давай помучаемся"
2. "Го сразу сражаться, без прилюдий"

В доказательство могу скинуть коммент с вовхеда:
http://ru.wowhead.com/npc=35004#english-comments
`От alexiel (6,085 – 1·12·64) 2009-09-24 (Обновление 3.2.0) 
As of 3.2.2, he now gives a second option to skip all the RP (under "I am ready") :
"I am ready. However I'd like to skip the pageantry."
Watch out and stay back near the door, because the bosses are immediately summoned instead of introduced one-by-one.
`

**Шаги для воспроизведения ошибки:**

Регнуть в группе Испытание чемпиона в любом режиме

**Текущее обновление ядра:**

[11:24:59] Ïîñëåäíåå îáíîâëåíèå ÿäðà: Build 163 2017-07-25 11:59:12 +0400
[11:24:59] Èãðîêîâ îíëàéí: 2274 (ìàêñèìóì: 4677). Èãðîêîâ â î÷åðåäè: 0 (ìàêñèìóì: 0).
[11:24:59] Ïðîäîëæèòåëüíîñòü ðàáîòû ñåðâåðà: 3 Day(s) 21 Hour(s) 43 Minute(s) 23 Second(s).
[11:24:59] Ñåðâåðíàÿ çàäåðæêà: 24.
[11:24:59] Ñëåäóþùåå íà÷èñëåíèå î÷êîâ àðåíû: 03.09.2017  10:22

**Comment by Devinette** [comment]
Реализовано

**Comment by Rorshah** [comment]
Сколько ни ходил последнее время (включая ппг, где у всех был проход по этому инсту)
Нигде не видел второго ответа при стартовом запуске инста.
Вы как починили ?
как ивент стартовый отменять ?

**Comment by Rorshah** [comment]
Мне кажется я понимаю о чем идет речь.
Но в описании бага нигде не вижу требования по наличию достижения.
Что за достижение ? И почему вдруг его стали проверять ?

**Comment by gmKroshka** [comment]
Из описания апдейта:
Испытание чемпиона: реализована опция, позволяющая пропустить долгое вступление при запуске 1 босса, если все игроки имеют выполненное достижение [Испытание чемпиона](http://db.logon3.com/?achievement=3778)

**Comment by Rorshah** [comment]
спасибо.
Вопросов нет.
