### ISSUE TITLE
[Подземелье] Вершина Утгард (ID 26861 Король Имирон)

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#45]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Каждые 33% в об, и каждые 20% в гер - Босс должен получать дополнительную способность от погребенных королей. Неправильная работа призываемых нпц.

**Что работает не так?**

1. В гер режиме, король должен обойти все лодки (на: 80%, 60%, 40%, 20%). Условие иногда не соблюдается, он использует лодки не при этих показателях. Босс может выбирать рандомно лодку, сейчас этого не замечается.
2. При поджигании лодки Король Ранульф (http://wowroad.info/?npc=27308) - появляется Источник духа (об, http://wowroad.info/?npc=27339) / Источник духа (гер, http://wowroad.info/?npc=30808) - Источник промахивается заклинанием (судя по всему из-за того, что он 1 лвл)
3. При поджигании лодки Король Галдор (http://wowroad.info/?npc=27307) - суммонятся Мстительный дух (об, http://wowroad.info/?npc=27386) / Мстительный дух (гер, http://wowroad.info/?npc=30756) 
Судя по англ. комментарием вовхеда:
> - (Back Left) Allows King Ymiron to summon a flood of adds. On normal it's around 4, but on heroic it can be upwards of 10. Each hit from the adds stacks a 2% decrease in attributes debuff and they attack fairly quickly. I've seen this stack up to 20 

мобы должны стакать дебафф при атаке, ID заклинания найти не удалось. На [видео №1](https://youtu.be/XDIZHKzEFXA?t=50) можно обратить внимание на членов группы (ДК, медведь), на них появляется неизвестный дебафф. На этом [видео №2](https://youtu.be/kPjlTk-_OGs?t=43) хил держит танка в таргете, и по хп танка видно, что дебафф уменьшает стамину.

**Как должно работать?**

В героическом режиме босс должен использовть лодки при верных показателях здоровья. Источних духа должен попадать по игрокам во всех сложностях. Мобы должны вешать стакающийся дебафф.

**Текущее обновление ядра:**

Virgin: Build 151 2017-04-03 15:25:08 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
