### ISSUE TITLE
Задание "Перехватить донесения" в Ледяной короне

### ISSUE THREAD

**Issue by MyWorldik** [VirginTeam/VirginCore#450]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Орда что-то затевает, и мне это не нравится! После того, что они вытворяли на Прорванном фронте, стало ясно, что они способны на все – и нам следует их остановить.
Небо над ледником Ледяной Короны, к западу от Алдур'тара и Железного вала, кишит их разведчиками. Всадники на дракондорах переносят депеши и донесения. Используй этот стреломет, когда понадобится убить разведчиков с "Молота Оргрима". Пожалуй, будет лучше, если ты тоже будешь летать...

**Что работает не так?**

НПС летают на земле. Когда используешь стреломет, он не стреляет. Просто так убить их тоже не получается - персонаж не ударяет

**Как должно работать?**

Используешь стреломет на НПС - отбираешь донесения

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Build 163 2017-07-05, 11:59:12, +0400

**Comment by Ewropa** [comment]
Фикс уже отправлен был разработчику, ожидайте его из отпуска, и следующего обновления)

**Comment by Riazarre** [comment]
Проверяйте после обновления.
