### ISSUE TITLE
Неверная репутация за выполнения квеста Зашифрованные Сумеречные тексты

### ISSUE THREAD

**Issue by any7hing** [VirginTeam/VirginCore#459]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Добавьте описание проблемы здесь.

согласно вовхеду и коментам должно давать 500 репы с кругом кенария, а дают 250 за этот квест
http://ru.wowhead.com/quest=8319

Фактический результат — тот, который вы наблюдаете

дают 250 репутации, вместо 500

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
должны давать 500 репутации с кругом кенария
**Шаги для воспроизведения ошибки:**

1. берете квест
2. сдаете квест
3. получаете репутацию за квест

**Текущее обновление ядра:**
 Последнее обновление ядра: Build 163 2017-07-25 11:59:12

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by Riazarre** [comment]
Запрос передан разработчику.
