### ISSUE TITLE
[Задание] ID 7603 - Огненное ядро Крошиуса

### ISSUE THREAD

**Issue by Devinette** [VirginTeam/VirginCore#46]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

По квесту [Огненное ядро Крошиуса](http://ru.wowhead.com/quest=7603) необходимо использовать [Пламя Скверны](http://ru.wowhead.com/item=18626) над останками для появления Крошиуса

**Что работает не так?**

[Пламя Скверны](http://ru.wowhead.com/item=18626) использовать не нужно, Крошиус сразу стоит на положенном месте

**Как должно работать?**

Используем [Пламя Скверны](http://ru.wowhead.com/item=18626), появляется Крошиус

**Шаги для воспроизведения ошибки:**

1. Берем квест
2. Используем [Пламя Скверны](http://ru.wowhead.com/item=18626) над останками Крошиуса

**Текущее обновление ядра:**

PTR Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверяйте после обновления
