### ISSUE TITLE
Чернокнижник/Охотник Скверны/Пожирание магии

### ISSUE THREAD

**Issue by Doomgodz** [VirginTeam/VirginCore#463]
**Описание**:
Способность питомца чернокнижника Охотника Скверны - Devour Magic (Пожирание магии) не диспелит вражеский таргет
Ссылка на спелл http://wowroad.info/?spell=67518
**Что работает не так?**
Нет диспела по вражескому таргету

**Как должно работать?**
Способность должна диспелить 1 благотворный эффект с противника

**Шаги для воспроизведения ошибки:**
1. Вызываем Охотника Скверны
2. Ставим дуэль или идем на бг и ищем любой вражеский таргет на котором есть баф, который можно сдиспелить
3. Жмем способность Охотника Скверны Devour Magic (Пожирание магии) 
При попытке будет писать "nothing to dispel"

**Текущее обновление ядра:**
Build 163 2017-07-25 11:59:12 +0400
 

Видео: https://www.youtube.com/watch?v=gdd0aK4AXfM&feature=youtu.be

**Comment by Riazarre** [comment]
Не удается воспроизвести, запишите видео с багом.
Ну и ссылку заклинания добавьте в описание.

**Comment by Doomgodz** [comment]
добавил

**Comment by Riazarre** [comment]
Способность работает корректно.
https://youtu.be/pIIO14IaaDc

**Comment by Doomgodz** [comment]
да не работает этот спелл, зайдите на х1 в хиджал и проверьте
