### ISSUE TITLE
Квест на бронника

### ISSUE THREAD

**Issue by Mardock90** [VirginTeam/VirginCore#464]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Трентон при сдаче квестов не дает рецепты для прохождения следующего этапа

**Что работает не так?**

Нет рецептов

**Как должно работать?**

3 рецепта для дальнейшего прохождения

**Шаги для воспроизведения ошибки:**

1a) Говорим с Ханком Молотом в Штормграде и делаем квест Происхождение Кузнечного Искусства (необходим уровень 40 и навык Кузнечного Дела 210). Вам понадобятся 30 Стальных Слитков и 12 Тяжелых Шлифовальных Камней;
1б) Берём у него же квест В Поисках Гальвана, летим\бежим в Пиратскую Бухту к Макгевану;
1в) У Макгевана берём квест Орден Мифрила и бежим к Гальвану Древнему; 

2a) Гальван Древний даёт три квеста - Могущество Камней, Обманное Серебро и Плавим, Не Плавим, Плавим, Не Плавим… После выполнения одного из квестов появится квест Лучший Ученик Гальвана, отправляющий вас к Трентону Молоту Света в Прибамбасск для продолжения цепочки. А после выполнения всех трёх квестов появится квест Кузнец-умелец!
P.S. Для выполнения всех трёх квестов вам понадобятся 120 Мифриловых Слитков, 40 Железных Слитков, 5 Слитков Истинного Серебра и 4 Цитрина. Можно взять всё это заранее, когда первый раз побежите к Гальвану. 

3a) Трентон Молот Света даст вам три квеста - Голова На Плечах, Мир У Твоих Ног и Мифриловый Парень. Для выполнения всех трёх квестов вам понадобятся 114 Мифриловых Слитков, 18 Магической Ткани, 14 Плотной Кожи, 3 Слитка Истинного Серебра и 2 Твёрдых Шлифовальных Камня. В награду вы получите три рецепта, необходимых для выполнения заключительного квеста цепочки.

**Текущее обновление ядра:**
Build 163 2017-07-25 11:59:12 +0400

**Comment by Riazarre** [comment]
На тесте работает прекрасно. Проверяйте свою профессию, по выполнению заданий вы должны были изучить рецепты.
