### ISSUE TITLE
[Задание] ID 12790 - Как уйти и вернуться: магический путь

### ISSUE THREAD

**Issue by POVELITELnumber1** [VirginTeam/VirginCore#465]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

[Как уйти и вернуться: магический путь](http://wowroad.info/?quest=12790) - Квест в Даларане не работает.

**Что работает не так?**

Когда юзаешь второй [кристалл на Аметистовой заставе](http://wowroad.info/?object=191230), он не засчитывается, а всплывает красная надпись на английском, что нужно сначала заюзать кристалл в Даларане, хотя это уже было сделано.
Кроме того, кристаллы не телепортируют в Даларан и на заставу.

**Как должно работать?**

При юзании второго кристалла, квест должен засчитываться.

**Шаги для воспроизведения ошибки:**

1. Юзануть [Кристалл телепортации на Аметистовую заставу](http://wowroad.info/?object=191229)
2. Юзануть [Кристалл телепортации в Даларан](http://wowroad.info/?object=191230)

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by Riazarre** [comment]
Только что выполнил это задание лично.
Работает правильно, почистите кеш игры, используйте antierror, убедитесь, что юзаете ТОТ кристалл. http://joxi.ru/52azoQbI43wzvA

**Comment by POVELITELnumber1** [comment]
Помогло, спасибо)
