### ISSUE TITLE
КД способностей петов у чернокнижника

### ISSUE THREAD

**Issue by Doomgodz** [VirginTeam/VirginCore#467]
**Описание:**

Не сбрасывается кд спеллов питомцев у чернокнижника после призыва

**Что работает не так?**

Например, берем спелл войда- жертвоприношение. Применив его, на чернокнижника вешается щит, поглощающий урон( кд=1 мин). При призыве нового войда кд на данный спелл не скидывается (это касается и других петов варлока, например охотник скверны со способностью Запрет чар (кд=24 сек)) 

**Как должно работать?**

При повторном призыве нового пета все кулдауны пет-спеллов должны скидываться
Видео: https://www.youtube.com/watch?v=g0eHQIMeKBo

**Шаги для воспроизведения ошибки:**

1. Заходим на чернокнижника, делаем призыв демона бездны.
2. Применяем способность пета Жертвоприношение
3. После этого сразу же вызываем нового демона бездны и видим, что кд с Жертвоприношения не скинулось
Видео: https://www.youtube.com/watch?v=l3Z8GIHuFL4

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by Riazarre** [comment]
Пруфы предоставьте.

**Comment by Doomgodz** [comment]
добавил

**Comment by Riazarre** [comment]
Пиратские сервера не являются пруфами.

**Comment by Gooldark** [comment]
дубль - https://github.com/VirginTeam/VirginCore/issues/87

**Comment by Doomgodz** [comment]
хорошо вот тема http://forum.wowcircle.com/showthread.php?t=581566&page=2, данный баг относительно недавно пофиксили, а вот и пруф http://www.warcraftmovies.com/movieview.php?id=161145 
3:25-3:37 спел лок, фел доминейшен - 2й спел лок. Видео с оффа, 3.3.5.
Вместе с тем, можно еще заметить, что нет никакого оглушения на пете после перепризыва, а так же полные ХП и МП.

**Comment by Riazarre** [comment]
Дубликат, закрыто.
