### ISSUE TITLE
[Задание] ID 13288 - Как все погано!

### ISSUE THREAD

**Issue by Devinette** [VirginTeam/VirginCore#47]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Для выполнения квеста призывается [Воскрешенное поганище](http://ru.wowhead.com/npc=31692), после призыва появляется панель управления

**Что работает не так?**

После призыва панель не появляется

**Как должно работать?**

Панель присутствует и можно использовать способности [Воскрешенное поганище](http://ru.wowhead.com/npc=31692)

**Шаги для воспроизведения ошибки:**

1. Выбиваем  Набор для оживления поганища
2. Призываем Воскрешенное поганище

**Текущее обновление ядра:**

PTR Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
