### ISSUE TITLE
Не работает квест "Самые маленькие создания" Logon 3 x1 WoW Circle

### ISSUE THREAD

**Issue by autodafe142** [VirginTeam/VirginCore#470]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Проблемы с работой квеста "Самые маленькие создания", который выдается Рексаром в Острогорье. Квест важен, потому что далее достаточно длинная цепочка, без которой никак не получается выполнить достижение "На пиках скал". 

**Что работает не так?**

При использовании кв итема "Барабан из шкуры кодо" мне не дается под контроль сурок, меня словно отправляет в мир призраков. При этом если я использую бочку, то кв не засчитывает, а меня выкидывает из этого "призрачного" состояния.

**Как должно работать?**

Меня должно переправлять в шкуру сурка при использовании  "Барабан из шкуры кодо" , чтобы я добежал до бочек и смог их отравить. 

**Шаги для воспроизведения ошибки:**

1. Подлететь к норе сурков
2. Использовать "Барабан из шкуры кодо"

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by Riazarre** [comment]
Дубликат.
#285
