### ISSUE TITLE
[Игровая Механика] ID 34753 -Пир На Весь Мир

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/VirginCore#475]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
Лоу лв могут юзать http://ru.wowhead.com/item=34753, когда он с 70го уровня

**Что работает не так?**

Фактический результат — тот, который вы наблюдаете

**Как должно работать?**

Лоу лв не должны использовать данный предмет 

**Шаги для воспроизведения ошибки:**

https://www.youtube.com/watch?v=kOmsDoSoE94&feature=youtu.be

**Текущее обновление ядра:**

На видео

**Comment by Riazarre** [comment]
А как насчет

> От fadeaway (8,485 – 1·26·66) 2008-11-21 (Обновление 3.0.3) 
> I invited a level 36 mage to my party in Stormwind and dropped one of these, he was able to click it and get the full buff. You need to be lvl 70 to drop the Great Feast, but it seems there's no level restrictions on eating it for the buff.. (cough twinks cough)

**Comment by kalipsa988** [comment]
Можно есть на 19ом и идти с этим бафом на бг?
