### ISSUE TITLE
[Задание] id 15005 - Миссия: Черная гора

### ISSUE THREAD

**Issue by Holyway** [VirginTeam/VirginCore#476]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

В задании "Миссия: Черная гора"  ID 15005 Требование "Глубины Черной горы:Тюрьма" засчитывает при убийстве Финий Темностой вместо Верховный дознаватель Герштан

**Что работает не так?**

Требование "Глубины Черной горы:Тюрьма" засчитывает при убийстве Финий Темностой который не является финальным боссом части "Тюрьмы" ,а находится совсем в другой части подземелья

**Как должно работать?**

Если исходить из того что финальным боссом Глубин Черной горы:Тюрьма через систему поиска подземелий является Верховный дознаватель Герштан то требование должно засчитывать при убийстве его

**Шаги для воспроизведения ошибки:**

1. Убить [Верховный дознаватель Герштан id 9018](http://ru.wowhead.com/npc=9018) (Требование не засчитано)  
2. Убить [Финий Темнострой id 9056](http://ru.wowhead.com/npc=9056) (Требование засчитано)

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в следующем обновлении
