### ISSUE TITLE
Квест "Манускрипт защиты"

### ISSUE THREAD

**Issue by djex777** [VirginTeam/VirginCore#477]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не могу сдать задание "Манускрипт защиты"

**Что работает не так?**

Есть все необходимые предметы, но кнопка для сдачи квеста неактивна.
**Как должно работать?**

Квест должен быть сдан. На скрине все понятно.

**Шаги для воспроизведения ошибки:**

1. Шаг один
![wowscrnshot_090817_143756](https://user-images.githubusercontent.com/31843900/30264809-32239fd6-96eb-11e7-9c6a-25e1907fd3c8.jpg)
![wowscrnshot_090817_143818](https://user-images.githubusercontent.com/31843900/30264808-322257e8-96eb-11e7-80db-48c861947f3a.jpg)

2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by kalipsa988** [comment]
Всё работает, я сам делаю эту ачиву, просто квест отмени и заново возьми

**Comment by Riazarre** [comment]
Тоже выполнял задание.
