### ISSUE TITLE
КД Озера Ледяных Оков

### ISSUE THREAD

**Issue by Doomgodz** [VirginTeam/VirginCore#483]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Озеро Ледяных Оков http://wowroad.info/?zone=4197

**Что работает не так?**

КД ОЛО составляет 6 часов 

**Как должно работать?**

КД ОЛО должно быть 2 часа 30 минут
Доказательство - сообщение на вовхеде времен вотлк http://ru.wowhead.com/wintergrasp#comments 
```
От molekylka (1,032 – 1·4·5) 2009-06-23 (Обновление 3.1.3)	
К большому сожаления ,только половина игроков попавших в эту пвп зону ,знают для чего она и как на ней выигрывать ,остальные же думают что Озеро ледяных оков это пастбище ,куда надо приходить # каждые 2 с половиной часа .
Начнём с того что все ноют что близзы олухи сделали пвп локацию где не реально играть из за жутких лагов .Поверьте мне близы далеко не олухи ,если каждый будет знать суть и задумку этой пвп зоны ,то лагов станет в разы меньше .
Сражение на озере ледяных оков ,как я уже заметил выше ,проходит каждые 2 с половиной часа, плюс-минус 15 минут
```

**Шаги для воспроизведения ошибки:**

Достаточно после окончания ОЛО открыть вкладку пвп и посмотреть кд, или же залететь на ОЛО во время боя, дождаться его окончания и посмотреть кд

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by Gooldark** [comment]
Насколько знаю в свое время сделали кд 6 часов чтобы на сервер меньше нагрузка была. Конечно хотелось бы офлайк 2.5 часа.
