### ISSUE TITLE
[Задание] ID 11079 - Бич Скверны для Гахка

### ISSUE THREAD

**Issue by Holyway** [VirginTeam/VirginCore#489]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Нельзя убить квестовых мобов из-за того что они вызываются в тектуру

**Что работает не так?**

Когда используешь [Хрустальная призма Скверны](http://ru.wowhead.com/object=185927) призывается один из четырёх мобов:
1) [Гальванот](http://ru.wowhead.com/npc=22281)
2) [Браксус](http://ru.wowhead.com/npc=23353)
3) [Зарцин](http://ru.wowhead.com/npc=23355)
4) [Мо'арг Испепелитель](http://ru.wowhead.com/npc=23354)
Но призываются они внутрь объекта из-за чего их нельзя атаковать и вобще каким либо способом вытащить из него

**Как должно работать?**

Нпс должны призываться выше самого объекта или около него

**Шаги для воспроизведения ошибки:**

1. Собрать 35 [Апекситовый осколок](http://ru.wowhead.com/item=32569)
2. Использовать обьект [Хрустальная призма Скверны](http://ru.wowhead.com/object=185927)
3. Попробовать атаковать призваного нпс (недоступен для атаки так как находится внутри обьекта)

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by odino4estvo** [comment]
Да не работает он, увы, еще с мая месяца...
https://github.com/VirginTeam/VirginCore/issues/211

**Comment by Riazarre** [comment]
Дубликат.
#211
