### ISSUE TITLE
Сбор кристаллов

### ISSUE THREAD

**Issue by Razama1234** [VirginTeam/VirginCore#49]
**Описание:**

Необходимо собрать кристаллы с помощью подчинённого гнилостного упыря.

**Что работает не так?**

[Гнилостный упырь](http://wowroad.info/?npc=28750) не собирает [Кристалл гнили](http://wowroad.info/?item=39670) по заданию [Сбор кристаллов](http://wowroad.info/?quest=12673)

**Как должно работать?**

После подчинения гнилостного упыря у нас появляется возможность собирать с его помощью кристалл гнили при помощи абилки "Добыча кристалла гнили", которые тот в свою очередь относит в портал в зиккурат "Волтар".
[Видео.](https://www.youtube.com/watch?v=mWyfdZzcTjE)

**Шаги для воспроизведения ошибки:**

1. Взять квест [Сбор кристаллов](http://wowroad.info/?quest=12673)
2. Подчинить упыря.
3. Использовать способность вурдалака "Добыча кристалла гнили".

**Текущее обновление ядра:**

Build 151 2017-04-03 15:25:08 +0400

**Comment by Riazarre** [comment]
Дубликат.

**Comment by Devinette** [comment]
https://github.com/VirginTeam/VirginCore/issues/7
