### ISSUE TITLE
[Задание] ID 15021 - Миссия: Членистоногие и крылатые (об)

### ISSUE THREAD

**Issue by Holyway** [VirginTeam/VirginCore#490]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

В задании "Миссия: Членистоногие и крылатые" ID 15021 Требование "Окулус" не засчитывает при убийстве [Хранитель энергии Эрегос](http://ru.wowhead.com/npc=27656)
**Что работает не так?**

Требование "Окулус" не засчитывает при убийстве [Хранитель энергии Эрегос](http://ru.wowhead.com/npc=27656) который является финальным боссом подземелья "Окулус"

Возможно требование не засчитывает из-за того что босс убивается находясь на драконе

**Как должно работать?**

Должно засчитывать требование "Окулус" при его убийстве находясь на одном из драконов:
 (список итемов для призыва одного из драконов)
1) http://ru.wowhead.com/item=37860
2) http://ru.wowhead.com/item=37859
3) http://ru.wowhead.com/item=37815

**Шаги для воспроизведения ошибки:**

1. Сесть на одного из драконов
2. Убить [Хранитель энергии Эрегос](http://ru.wowhead.com/npc=27656) (Требование не засчитывает)

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
