### ISSUE TITLE
[Объект] ID 2040 - Залежи мифрила

### ISSUE THREAD

**Issue by xxxPANCHERxxx** [VirginTeam/VirginCore#492]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

в Танарисе, Кратере УнГоро и Солитусе крайне мало залежей мифрила (http://www.wowhead.com/object=2040) и респаун залежей очень долгий.

**Что работает не так?**

Стоял возле залежы 30 минут. так и не отреспаунилась.

**Как должно работать?**

Наладить респаун залежей мифрила (и не только). Определить единую величину времени для респауна и применить их ко всем залежам ресурсов (трава, металы и т.д.)

**Шаги для воспроизведения ошибки:**

на постоянной основе.

**Текущее обновление ядра:**

Logon 3 WowCircle Virgin x1
Build 163 2017-07-15 11:59:12 +0400

**Comment by Kodekc** [comment]
С спавном всё в порядке, просто возможно вы привыкли к той системе, что руда должна обязательно появится на этом месте, где она была вами собрана. На самом деле она появляется где-то в другой точке из "списка точек" и при сборе будет выбирать другое свободное место, не обязательно это же, где находитесь вы.
