### ISSUE TITLE
[Задание] ID 15019 - Миссия: Тролли и врайкулы (об)

### ISSUE THREAD

**Issue by Holyway** [VirginTeam/VirginCore#493]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

В задании "Миссия: Тролли и врайкулы" ID 15019 Требование "Крепость Утгард" не засчитывает при убийстве [Ингвар Расхититель](http://ru.wowhead.com/npc=23954)

**Что работает не так?**

Требование "Крепость Утгард" не засчитывает при убийстве [Ингвар Расхититель](http://ru.wowhead.com/npc=23954) который является финальным боссом подземелья "Крепость Утгард"

Возможно требование не засчитывает из-за того что босс имеет две фазы с разными "обликами"

**Как должно работать?**

Должно засчитывать требование "Крепость Утгард" при его убийстве

**Шаги для воспроизведения ошибки:**

1. Убить [Ингвар Расхититель](http://ru.wowhead.com/npc=23954) (требование не засчитано)

**Текущее обновление ядра:**

Build 163 2017-07-25 11:59:12 +0400

**Comment by ForesterDev** [comment]
будет исправлено после обновления
