### ISSUE TITLE
[Талант] ID 62762 - Жестокая травля

### ISSUE THREAD

**Issue by Stimpi74** [VirginTeam/VirginCore#494]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

При прокачки таланта 2 уровня "Жестокая травля" у пета (помощника) должны повышаться на 40% выносливость и 30% сила атаки от аналогичных параметров охотника http://wowroad.info/?spell=62762

**Что работает не так?**

при прокачки таланта "Жестокая травля" у пета (помощника) не повышаются в данном соотношении параметры выносливости и силы атаки http://wowroad.info/?spell=62762  
http://s018.radikal.ru/i517/1709/cf/c36e5b51d24a.jpg

http://s019.radikal.ru/i619/1709/93/40da59d841e0.jpg

http://s018.radikal.ru/i512/1709/3e/f8eead612b6a.jpg

**Как должно работать?**

пету (помощнику) должны передаваться выносливость и сила атаки охотника в соотношении 40% и 30% 

**Шаги для воспроизведения ошибки:**

1. прокачиваешь талант 

**Текущее обновление ядра:**

Build - 163 (Build - 51)

**Comment by Stimpi74** [comment]
![wowscrnshot_091617_094738](https://user-images.githubusercontent.com/32007747/30509491-59648040-9acb-11e7-9459-25d67ed80fe5.jpg)
![wowscrnshot_091617_094809](https://user-images.githubusercontent.com/32007747/30509492-5964b420-9acb-11e7-8350-cede5ecf7896.jpg)
![wowscrnshot_091617_095011](https://user-images.githubusercontent.com/32007747/30509493-59655c2c-9acb-11e7-90de-adebfc88fd5d.jpg)
 
вот скрины

**Comment by Gooldark** [comment]
Этот талант прекрасно работает, даже делает перерасчет в реальном времени(на маунта садиться не нужно или призывать). Талант работает не как вы думаете, он не переносит пету 40% выносливости и 30% Апа, а увеличивает прирост. То есть у ханта базово передается пету 45% выносливости и 22% апа, с талантом это будет 45*1,4=63% выносливости и 22*1,3=28,6% апа.

**Comment by Stimpi74** [comment]
значит будем искать в другом месте, где урон занижен

**Comment by Stimpi74** [comment]
ПЭТ масштабирование
# **Домашние животные получают атрибут бонусы в размере 15% от статов хозяина:**

1 атака дальнего боя сила дает любимчика 0.22 АП и 0.1287 магический урон (0.338 АП и 0,18 магический урон с 2/2  [Дикая Охота]).
1 выносливость дает 0.45 выносливость бесталанный (ошибочно сообщили как 0,3 выносливость в охотника выносливости подсказка), или 0,63 выносливости 2/2  [Дикая Охота]). Питомцы не получают никакого здоровья от их базы выносливости, и получить 10.5 здоровья за каждый дополнительный пункт выносливости (10 здоровья за дополнительную выносливость до неотъемлемое животное бонус здоровья, который был стандартизован до 5% в патче 3.1.0).
1 сопротивление дает 0,4 сопротивление.
1 броня дает 0.35 броню.
1 точка заклинание проникновения дает 1 очко заклинания проникновения для вашего питомца.[1]
1 точка устойчивости дает 1 балл жизнестойкости клиентов к вашему питомцу как в патче 3.3.0. Раньше было 0,4 балла устойчивости на 1 балл.[2]
Масштабирование формул для нажмите пока не имеется, однако патч 3.2.0 стат отмечает, что "если игрок находится на их заклинания, удара или удара максимум, их питомец будет максимальны заклинание удара, удара, и опыт. Если они будут ниже максимума, их питомец будет пропорционально ниже этих максимумов.".[1] 
хотелось бы знать, сила ловкость и тд даются пету в размере этих 15% (вот ссылка https://wow.gamepedia.com/Hunter_pet#Pet_scaling )

**Comment by Gooldark** [comment]
Врятле там есть большие баги на дамаг. Вот старая тема, которую в последствии собираюсь переоформить и перенести сюда - http://forum.wowcircle.com/showthread.php?t=554377. Там есть 2 видео где видны статы пета с офы, с серклой почти все совпадает.

**Comment by Stimpi74** [comment]
было бы здорово))
