### ISSUE TITLE
[Задание] - Возвращение охотника на личей

### ISSUE THREAD

**Issue by warkks** [VirginTeam/VirginCore#495]
Последние задание для доступа к дейликам с Племенем Бешенного Сердца и НИП "Зепик охотник на горлоков"  не выдает финального задания.
![wowscrnshot_091617_100523](https://user-images.githubusercontent.com/32008813/30510132-1a4f0000-9ac7-11e7-95bb-fd29acadb4ee.jpg)
![wowscrnshot_091617_095350](https://user-images.githubusercontent.com/32008813/30510136-1fcdb1de-9ac7-11e7-84b4-bd419410dd6e.jpg)

**Comment by kalipsa988** [comment]
не оформлено
