### ISSUE TITLE
Ледяные пальцы

### ISSUE THREAD

**Issue by praded443** [VirginTeam/VirginCore#504]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://wowroad.info/?spell=44545 Ледяные пальцы работают некорректно

**Что работает не так?**

Снятие последнего стака http://wowroad.info/?spell=44545 моментально, что делает невозможным использования http://wowroad.info/?spell=42842 Ледяной стрелы и http://wowroad.info/?spell=42914 ледяного копья вместе. Либо ледяной стрелы и после нее http://wowroad.info/?spell=44572 глубокой заморозки
**Как должно работать?**

После произнесения заклинания, ледяные пальцы должные сниматься не 
моментально, а через небольшой промежуток времени, чтобы маг успевал кинуть еще мгновенный спелл, особенно это касается последнего стака.
**Шаги для воспроизведения ошибки:**

1.  Доказательства https://www.youtube.com/watch?v=ItJV_IApfPs. Нfчиная с 3:13 когда маг начинает кастовать сперва первую ледяную стрелу, а после на последнем стаке ледяных пальцев 2 ледяную стрелу и сразу ледяное копье, которое наносит утроенный урон как и должно быть.

**Текущее обновление ядра:**
 Build 164 2017-09-21 12:45:47 +0400. Live server Virgin x1 pve

**Comment by Devinette** [comment]
Дубль
https://github.com/VirginTeam/VirginCore/issues/405
