### ISSUE TITLE
[Задание] ID 24548 - Расколотый трон

### ISSUE THREAD

**Issue by autodafe142** [VirginTeam/VirginCore#506]
У меня есть квест "Расколотый трон", по которому я собираю осколки на ШМ. Вот у меня уже 48 осколков и, по какой-то причине, мой рейд лидер не может передать мне сначала один осколок с Синдагоссы, а потом другой осколок с Лич-Кинга. Делал релоги, чистил кеш, делал антиэрор - я даже не вижу эти осколки, их просто нет для меня, хотя у моего рейд лидера все в полном порядке.  До этого 8 осколков передавались нормально. 
Прилагаю скриншоты, где видно, что осколок есть и мой РЛ видит меня в списке тех, кому его можно отдать, но и ему и мне выдает ошибку, также там видно, что у меня есть квест и 48 осколков.
Ник Cup , x1 3.3.5 pve

https://ibb.co/jwRCG5
https://ibb.co/bB9XG5
https://ibb.co/hA2xik

Добавьте описание проблемы здесь.

Не передаются осколки на ШМ, когда мне нужно еще 2 осколка.

Фактический результат — тот, который вы наблюдаете

Осколки не могут быть переданны моему персонажу, на экране у меня возникает ошибка "Вы никогда не сможете это использовать". 

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

Ожидал собрать сегодня ШМ, при помощи последних осколков. 

1. Открыть лут с боссом
2. Передать осколок нужному персонажу
3. 

**Текущее обновление ядра:**

Build 164 2017-09-21 12:45:47 +0400

**Comment by Devinette** [comment]
1. Проверьте наличие осколков в банке
2. Отмените и возьмите квест заново. Осколки не пропадут.

**Comment by Holyway** [comment]
поможет если положить осколки в банк,там похоже проблема в том что когда есть 48 осколков в сумках то не отображаются в луте(и нельзя получить от РЛа) осколки

**Comment by autodafe142** [comment]
Действительно помог способ, описанный комментатором выше.
