### ISSUE TITLE
Отсутствие квестов на хлемеваре.

### ISSUE THREAD

**Issue by Gudzone** [VirginTeam/VirginCore#507]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:** Праздник хмелеваров, над нпс возле Стальгорна светятся ежедневные кв, но при разговоре с ними открывается пустое диалоговое окно.

Добавьте описание проблемы здесь. Отсутствие ежедневных кв.

**Что работает не так?** Восклицательный знак о наличии квеста есть, а по факту квеста у нпс взять не могу.

Фактический результат — тот, который вы наблюдаете. Квестов нет.

**Как должно работать?** В диалоговом окне должен быть квест.

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by Gudzone** [comment]
Чистка кэша и антиеррор не помогают.

**Comment by Riazarre** [comment]
Проблема сугубо индивидуальная, оформляйте запрос в центре поддержки http://logon3.com/support
