### ISSUE TITLE
[Игровая механика] Питомец АДК

### ISSUE THREAD

**Issue by AntonTor** [VirginTeam/VirginCore#508]
**Описание:**
На питомца-вурдалака перестали действовать баффы, накладываемые рыцарем смерти.

**Что работает не так?**
При применении заклинания "Зимний горн" не накладывается соответствующий эффект на вурдалака, при этом в логах пишется  "<Имя вурдалака> обладает неовсприимчивостью к заклинанию "Зимний горн" <Имя персонажа>". При использовании предмета "Пряное лакомство из мамонта" не накладывается эффект "Сытость" на питомца, в логах ошибка не отображается.

**Как должно работать?**
При применении заклинания "Зимний горн" на вурдалака должен накладываться эффект "Зимний горн". При использовании предмета "Пряное лакомство из мамонта" на вурдалака должен накладываться эффект "Сытость".

**Шаги для воспроизведения ошибки:**

**Текущее обновление ядра:**
Logon 3 WowCircle Development
Build 164 2017-09-21 12:45:47 +0400

**Comment by AntonTor** [comment]
Использование Anti-error в ЛК, чиска кеша в игре, сброс талантов, убийство притомца ("Отпустить питомца" или при помощи заклинания "Смертельный союз") не помогли.

**Comment by zyxellgit** [comment]
о, дополню
также не накладывается пристовские молитвы на дух и на стамину, молитва защиты от темной маги накладыватеся исправно
![wowscrnshot_092617_013217](https://user-images.githubusercontent.com/29210390/30829856-7bf9441e-a25b-11e7-9768-48fa2202cc58.jpg)

**Comment by Riazarre** [comment]
Проверяйте на Public Test Realm!

**Comment by AntonTor** [comment]
На Public Test Realm баффы накладываются.

![wowscrnshot_092817_234447](https://user-images.githubusercontent.com/29437991/30989684-3380a508-a4a7-11e7-8e4f-58b3f811462c.jpg)
