### ISSUE TITLE
[NPC] ID 20604  - Дугиру

### ISSUE THREAD

**Issue by 2dull2die** [VirginTeam/VirginCore#510]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Отсутствие у npc Дугиру http://wowroad.info/?npc=20604 квеста Пожертвование – шелк (http://wowroad.info/?quest=7798) и дальнейшей цепочки.

**Что работает не так?**

У npc Дугиру http://wowroad.info/?npc=20604 есть в наличии только один квест - Пожертвование - Шерсть http://wowroad.info/?quest=7792 (после его завершения новые квесты не появляются).

**Как должно работать?**

Изначально у npc Дугиру http://wowroad.info/?npc=20604 должно быть в наличии два квеста Пожертвование - Шерсть http://wowroad.info/?quest=7792 и Пожертвование - Шелк http://wowroad.info/?quest=7798, после сдачи квеста Пожертвование - Шелк http://wowroad.info/?quest=7798, должен появиться квест Пожертвование - Магическая ткань http://wowroad.info/?quest=10356, после сдачи квестов Пожертвование - Шерсть, Пожертвование - Шелк и Пожертвование - Магическая ткань должен появиться квест Пожертвование - Руническая ткань http://wowroad.info/?quest=10357, после сдачи которого должен появиться квест Больше Рунической ткани http://wowroad.info/?quest=10358. (Возможно это имеет значение - уровень персонажа 53)

**Шаги для воспроизведения ошибки:**

1. Сдать npc Дугиру http://wowroad.info/?npc=20604 квест - Пожертвование - Шерсть http://wowroad.info/?quest=7792
2. У npc Дугиру больше квестов нет и не появляется.

**Текущее обновление ядра:**

Build 51 2017-08-02 15:34:47 +0400

**Comment by Riazarre** [comment]
Проверяйте после обновления.
