### ISSUE TITLE
[Задание] ID 11538 - Сражение за оружейную Солнечного Края

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/VirginCore#511]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Предвестник Инууро просит вас убить 6 демонов Пылающего Легиона и эмиссара Ненависти на Рассветной площади или в оружейной Солнечного Края. Пригвоздите к земле древком Знамени Расколотого Солнца труп Эмиссара Ненависти.

**Что работает не так?**

Данный НПС http://wowroad.info/?npc=25061 не выдает ежедневный квест http://wowroad.info/?quest=11538, он вообще у него отсутствует, и диалога с ним при взаимодействии с вышеуказанным нпс нет...  Квест этот у него ни разу не брал, хотя по идее он должен быть, репутация у меня с Армией Солн.Солнца "Почтение", без 7к "Превознесение". Такая ситуация наблюдалась с ним еще как только начал фармить репутацию с ними. Квеста нет. Раньше была проблема на форуме, что сам НПС отсутствовал, но задание как комментировали там, он давал. 

Скрин прикрепил ниже, знак восклицания над ним отсутствует. И так ежедневно, его нету.

**Как должно работать?**

Все просто, взять ежедневный квест, думаю неважно какая репутация должна быть у игрока. Будь то уважение, или почтение. Быть может у меня одного такая ситуация, что он не выдает это задание. Похожая ситуация у меня была с https://github.com/VirginTeam/VirginCore/issues/355, быть может аналогичная проблема и с этим квестом?

**Шаги для воспроизведения ошибки:**

1. Взять квест http://wowroad.info/?quest=11538 у http://wowroad.info/?npc=25061
2. Выполнить квест согласно указанным пунктам.
3. Сдать его ему же обратно.

**Текущее обновление ядра:**

Build 164 

![wowscrnshot_092517_151017](https://user-images.githubusercontent.com/27158518/30807737-cb5f952e-a203-11e7-93f6-a10384137896.jpg)

**Comment by Riazarre** [comment]
Фикс передан разработчику.
