### ISSUE TITLE
[Задание] ID 15024 - Миссия: Прошлое и настоящие (гер)

### ISSUE THREAD

**Issue by Holyway** [VirginTeam/VirginCore#518]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

В задании "Миссия: Прошлое и настоящие (гер)" ID 15024 Требование "Очищение Стратхольма" не засчитывает при убийстве ласт босса

**Что работает не так?**

Требование "Очищение Стратхольма" не засчитывает при убийстве [Мал'Ганис](http://ru.wowhead.com/npc=26533) который является финальным боссом подземелья "Очищение Стратхольма"

**Как должно работать?**

Должно засчитывать требование "Очищение Стратхольма" при его убийстве

**Шаги для воспроизведения ошибки:**

1. Убить [Мал'Ганис](http://ru.wowhead.com/npc=26533) (требование не засчитано)

**Текущее обновление ядра:**

Build 164 2017-09-21

**Comment by ForesterDev** [comment]
Будет исправлено после обновления
