### ISSUE TITLE
[Задание] ID 10601 - Судьба Кагроша

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/VirginCore#519]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Разыщите Кагроша в Кузнице Смерти и принесите его сумку разведчику Заграну на вышку на золе.

**Что работает не так?**

При взаимодействии с его трупом, с него не берется нужная для задания вещь http://wowroad.info/?item=30659, при попытке "обшарить нпс", вылазит игровая ошибка "предмет не найден", скрин прикладываю.

**Как должно работать?**

Все просто, нужно обшарить/залутать нпс.

**Шаги для воспроизведения ошибки:**

1. Найти по координатам - 35.40 труп Кагроша, (вход через туннель - 40.38)
2. Залутать с него квестовой итем http://wowroad.info/?item=30659
3. Вернуться и сдать задание квестодателю http://wowroad.info/?npc=21475

**Текущее обновление ядра:**

Build 164

![wowscrnshot_100117_125019](https://user-images.githubusercontent.com/27158518/31054371-e81026ce-a6b9-11e7-9129-29e86432cfa5.jpg)

**Comment by Riazarre** [comment]
Проверяйте после обновления.
