### ISSUE TITLE
[Игровая механика] ID 49052 - Верный выстрел

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/VirginCore#520]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Неверное время каста.

**Что работает не так?**

Модификатор на 15% криво работает, вместо каста 1.74 сек при хасте 0, каст проходит 1.80
т е разница 0.06 сек. Далее при хасте 133 разница уже 0.08 сек. При хасте 712 разница 0.14 сек
На каждые 60 хасты разница увеличивается на 0.01 сек
**Как должно работать?**

Время каста Верного выстрела при хасте 0 должно быть 1.7 секунды, дальнейший расчёт идёт по принципу на каждые 32,79 балла скорости вы получите 1% более высокую скорость атаки на 80 уровне. 

**Шаги для воспроизведения ошибки:**

1. Посмотреть время каста верного выстрела при хасте 0 в книге заклинаний
2. Посмотреть время каста верного выстрела при хасте 0 на маникене
3. Сравнить разницу

**Текущее обновление ядра:**

Последнее обновление ядра: Build 164 2017-09-21 12:45:47 +0400

Доказательства 
https://www.youtube.com/watch?v=EX5311xCG-Y  - каст при хасте 0
https://www.youtube.com/watch?v=8y37_6EnrQ0 - каст при хасте 133
https://www.youtube.com/watch?v=5urudTOyWkw - каст при хасте 712
http://wowwiki.wikia.com/wiki/Steady_Shot?oldid=2358729, http://wowwiki.wikia.com/wiki/Haste_rating, http://wowwiki.wikia.com/wiki/Auto_Shot?oldid=2322240

**Comment by Gooldark** [comment]
На данный момент скорость рассчитывается так 1,5 / x + 0,5 где x - мультипликативно перемноженные модификаторы.
Как было на офе неизвестно, нужно найти видео, где видны модификаторы скорости охотника, и видна скорость каста этого спела в действии, а не на панельке заклинаний.

**Comment by kalipsa988** [comment]
https://www.youtube.com/watch?v=T7N4OIw3SPE вот

**Comment by kalipsa988** [comment]
https://www.youtube.com/watch?v=T7N4OIw3SPE вот видео

**Comment by kalipsa988** [comment]
https://www.youtube.com/watch?v=T7N4OIw3SPE вот видео верного выстрела со всеми подробностями

**Comment by kalipsa988** [comment]
https://www.youtube.com/watch?v=cMqaviT8vVM вот ещё одно, то тут аддона на каст нет

**Comment by Gooldark** [comment]
Первый пиратка, второй похоже тоже, да и все равно скорость каста невидно. Когда ищешь актуальное видео указывай год, тогда будет больше подходящих видео, мб найдешь, что нужно.
Например запрос: Hunter 3.3.5 2010

**Comment by kalipsa988** [comment]
https://www.youtube.com/watch?v=mKoA0NPJuGc вот этот подойдёт?

**Comment by Librariane** [comment]
@kalipsa988
при 0 рейтинга время каста по кварцу 1,8 потому что он округляет значение 1,74 до 1 знака вверх. Из-за этого у вас и появилась "ошибка" в расчете времени. Можете проверить через combatlog в игре, в нем фиксируется время с точностью до мс.

**Comment by Gooldark** [comment]
У кварца есть настройка показывать скорость до сотых, она действительно не совпадает с тултипом. Как она рассчитывается сейчас описал выше, 0,5 сек это добавочное время выстрела, но должно ли оно подвергаться модификации пока непонятно.

**Comment by Librariane** [comment]
@Gooldark
как считает кварц нам без разницы. Тултип в игре показывает верно рассчитанное время, фактическое, как я уже говорил ранее. проверяется через комбат лог.

**Comment by Gooldark** [comment]
Вот нашел видео с офы https://www.youtube.com/watch?v=F1H7Jm6FIpA, тут даже кварц есть.
Базовая скорость ружья 3 сек, + 15% от пассивки. Будет 2,608. То есть у ханта 2,608/2,52 = 1,0349 3,5% хасты. Когда хант врубает быструю стрельбу(40% скорости) скорость каста - 1,2; То есть 2/1,15/1,0349/1,4 = 1,2; если бы добавочные 0,5 не модифицировались, скорость была бы 1,5/1,15/1,0349/1,4 + 0,5 = 1,4

**Comment by Gooldark** [comment]
Работает
