### ISSUE TITLE
[Игровая механика] ID 19620 - Неудержимое неистовство

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/VirginCore#522]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Неверное описание.
**Что работает не так?**

1. Не верное описание таланта. 

1 | 3%
2 | 6%
3 | 9%
4 | 12%
5 | 15%
Описание на нашем сервере

**Как должно работать?**

1.  1 | 4%
     2 | 8%
     3 | 12%
     4 | 16%
     5 | 20%
Вот такое описание должно быть.

**Текущее обновление ядра:**

Последнее обновление ядра: Build 37 2017-09-29 13:54:15 +0400

Доказательства.
https://www.youtube.com/watch?v=rUY6JcYOBd4&feature=youtu.be неверное описание
http://wowwiki.wikia.com/wiki/Unleashed_Fury

**Comment by Devinette** [comment]
Только я вижу данное предложение?
Patch 3.0.8 (2009-01-20): This talent now grants only 3/6/9/12/15% pet damage.

**Comment by Stimpi74** [comment]
нет, все сидят)

**Comment by Devinette** [comment]
Описание и работа верные
