### ISSUE TITLE
[Заклинания] ID 19602 - Свирепость

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/VirginCore#523]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
Неработоспособен.

**Что работает не так?**

Талант не добавляет вероятность нанесения критического удара питомца

**Как должно работать?**

Талант должен увеличивать вероятность нанесения критического удара питомца в зависимости от прокачки таланта

**Шаги для воспроизведения ошибки:**

1. Посмотреть на вероятность нанесения критического удара питомца
2. Вкачать талант http://wowroad.info/?spell=19602
3. Увидеть отсутствие разницы в вероятности нанесения критического удара питомцем

**Текущее обновление ядра:**

Последнее обновление ядра: Build 37 2017-09-29 13:54:15 +0400

Доказательства.
https://www.youtube.com/watch?v=5EggCFDH5mM&feature=youtu.be не работает талант
http://wowwiki.wikia.com/wiki/Ferocity_(hunter_talent)

**Comment by Riazarre** [comment]
Талант работает, закрыто.
