### ISSUE TITLE
[Заклинания] ID 34454 - Опытный дрессировщик

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/VirginCore#524]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Неработоспособен.

**Что работает не так?**

Талант не увеличивает силу атаки питомца

**Как должно работать?**

Талант должен увеличивать силу атаки питомца в зависимости от уровня прокачки таланта.

**Шаги для воспроизведения ошибки:**

1. Посмотреть силу атаки питомца
2. Вкачать талант http://wowroad.info/?spell=34454
3. Увидеть отсутствие повышение силы атаки питомца

**Текущее обновление ядра:**

Последнее обновление ядра: Build 37 2017-09-29 13:54:15 +0400

Доказательства.
https://www.youtube.com/watch?v=c_xsgxwxhNQ&feature=youtu.be не работает талант 
http://wowwiki.wikia.com/wiki/Hunter_talents

**Comment by Stimpi74** [comment]
и правда не работает 10% к силе атаки петомца, прогонял и призывал петомца обратно, всё равно не давалась сила атаки

**Comment by Stimpi74** [comment]
а так же нельзя проверить шант крита петомца , сколько силы атаки даёт ему сила сколько крит ловкость и тд

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении

**Comment by Gooldark** [comment]
Работает
