### ISSUE TITLE
[Рейд] Храм Ан'Киража (ID 15275, 15276 Близнецы Императоры)

### ISSUE THREAD

**Issue by sega693** [VirginTeam/VirginCore#527]
Описание:

http://ru.wowhead.com/npc=15276#abilities http://wowroad.info/?npc=15276
http://ru.wowhead.com/npc=15275#abilities http://wowroad.info/?npc=15275
Неверная работа способности Двойной телепорт http://ru.wowhead.com/spell=800

Что работает не так?
1. При использовании спелла Двойной телепорт происходит вообще какая-то дичь. Пара вариантов для примера:
  а) После каста не происходит вообще ничего. 
  б) Телепортируется только ОДИН, и начитают оба бить только одну цель, хотя ранее били разных.
  в) Кастуют. Как нужно сбрасывают агро.. но остаются на своих местах, и БЕГУТ в противоположные концы комнаты к новой цели.

2. Хп у боссов не общее. Оно вообще в принципе разное у нас.. На вовхеде оба по 2,165,150хп

Как должно работать?
1. Должны мгновенно меняться местами при телепортации. Сброс агро работает почти правильно.. Но не всегда

2. Так же у боссов должно быть общее хп. 

https://www.youtube.com/watch?v=A3hG-KSvzLA Видео с катаклизма да, но зато хорошо видно все. Хз где искать актуальное. Что у нас творится лучше самим смотреть.

Шаги для воспроизведения ошибки:
1. спулить
2. подождать 30 сек до телепорта

Текущее обновление ядра:
Build 164 2017-09-21 12:45:47 +0400 Live Server

**Comment by Plasmashield** [comment]
Добавлю.
1. Должен быть мгновенный телепорт, сброс агро, 2 секунды ожидания. Через 2 секунды они выбирают вокруг себя "жертву", которая получает некоторое число трита и бой продолжается.
2. Хп у них верное. Их "общее хп" заключается в том, что они связаны не напрямую, а в %. Собственно с воввики: "Combined Health — The Emperors share percentage health. Damage to one emperor hurts the other emperor as well. HP of Vek'nilash is about 1.6M, HP of Vek'lor is about 1M. Therefore 100k damage done to Vek'lor equates to 160k damage done to Vek'nilash. This allows them to die simultaneously, but not in fact have the same real HP. Only their HP percentages go down simultaneously. This causes casters to have a greater effect in this fight than melee damage dealers."

**Comment by sega693** [comment]
Насчет хп. Странно тогда, что только в катаклизме изменили. Но не суть. У нас оно и в процентах не совпадает. Один раз после вайпа милишник вообще не отрегенился. Так и стоял с 2/3 при пуле. Есть подозрение, что багается, когда они за пределы видимости друг друга выходят.

**Comment by Plasmashield** [comment]
https://github.com/scriptdev2/scriptdev2-cata/commit/f7163421a9cb7cab1bff48243af7b8790cc8415a

**Comment by Plasmashield** [comment]
Так же, если придти на след. день и попытаться их убить, то у них сразу багается агро уже после первого телепорта. Почти всегда при вайпе у одного из близнецов висит в таргете кто то из игроков(особенно если был кинут диван)

**Comment by Kodekc** [comment]
В обновлении будут применены следующие изменения:

- реализованы тексты боссов
- реализован вступительный диалог боссов с Глазом
- переработана способность Двойной телепорт
- переработана система общего здоровья боссов
