### ISSUE TITLE
[Предмет] ID 23574 - Доверенный Ноздорму

### ISSUE THREAD

**Issue by sega693** [VirginTeam/VirginCore#528]
Описание:
http://wowroad.info/?npc=23574 http://ru.wowhead.com/item=20403#english-comments

Что работает не так?
Если у вас есть Агент Ноздорму http://wowroad.info/?item=20402 то при использовании пишет "У вас слишком много таких предметов". У цели точно нет итема  http://www.wowhead.com/item=20402

Как должно работать?
Должен даваться итем http://www.wowhead.com/item=20402 выбранной цели

For those now unfamiliar with this item and exactly what it does. It creates an Agent of Nozdormu for who ever you "...deputize..." within their bag (granting they have bag space). It is soul bound to them and remains within their bag until they trash it. You will not see anything on your screen chat stating they received the item even if in party or raid. They will receive the standard chat message on their screen indicating they received the item.
Consumed on use. So careful who you give it to.

Шаги для воспроизведения ошибки:
1 Выбрать союзника
2 тыкнуть итем

Если удалить свой "агент", то работает как нужно.

Текущее обновление ядра:
Build 165 2017-10-05 16:02:40 +0400 Live Server

**Comment by Kodekc** [comment]
Может в банке лежит?

**Comment by sega693** [comment]
нет. Как только свой итем выкинул этот смок кинуть тому же персонажу.
