### ISSUE TITLE
[Задание] ID 6627 - Испытание знаний

### ISSUE THREAD

**Issue by kotslik** [VirginTeam/VirginCore#529]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не работает задание "Испытание знаний" http://wowroad.info/?quest=6627

**Что работает не так?**

Не работает ни один из предложенных вариантов диалогов, включая тот, который необходимо выбрать для выполнения квеста. Диалоги отображались в окне общения с нпс даже до этой стадии квеста или если квест не взят.

**Как должно работать?**

Принятие квеста, выбор 2-го варианта ("Мой ответ - Нелтарион"), завершение квеста. При выборе иных вариантов - телепорт в Лагерь Турахо.

**Шаги для воспроизведения ошибки:**

1. Взаимодействие с нпс Брауг Тусклый Дух http://wowroad.info/?npc=4489 при актуальной стадии квеста
2. Выбор варианта диалога

**Текущее обновление ядра:**

logon3 x1PvE Build 165 2017-10-05 16:02:
![wowscrnshot_100617_021857](https://user-images.githubusercontent.com/32557478/31257278-67757c00-aa40-11e7-9d82-c506a7cdefef.jpg)
40

**Comment by Kodekc** [comment]
Исправлено. Изменения будут применены в ближайшем обновлении
