### ISSUE TITLE
[Задание] ID 11606 - Терпение – добродетель, которая не требуется

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/VirginCore#535]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

По поручению интенданта Холгота раздобудьте 15 ящиков с боеприпасами Песни Войны.

**Что работает не так?**

Интендант Холгот http://wowroad.info/?npc=25327 в Крепости не дает задание http://wowroad.info/?quest=11606. Подобная ситуация в предыдущем тикете.

**Как должно работать?**

Все просто, без каких-либо критериев он должен выдавать это задание на получение цепочки.

**Шаги для воспроизведения ошибки:**

1. Взять квест http://wowroad.info/?quest=11606 у http://wowroad.info/?npc=25327
2. Выполнить квест согласно пункту.
3. Сдать квест ему, и взять следующий.

**Текущее обновление ядра:**

Build 165
![1](https://user-images.githubusercontent.com/27158518/31345372-341c998e-ad1e-11e7-8dcd-e9484292cf74.jpg)

**Comment by Riazarre** [comment]
Проблема в конкретно Вашем персонаже.
