### ISSUE TITLE
[Задание] ID 11643 - Танковая пневматическая трансзажиматрица Мобу

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/VirginCore#536]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Принесите Мобу на берег Эха в Борейской тундре его танковую пневматическую трансзажиматрицу.

**Что работает не так?**

НИП http://wowroad.info/?npc=25475 не дает задание http://wowroad.info/?quest=11643. Скрин прикладываю.

**Как должно работать?**

Обычно без каких-либо критериев он должен выдавать это задание на получение цепочки.

**Шаги для воспроизведения ошибки:**

1. Взять квест http://wowroad.info/?quest=11643 у http://wowroad.info/?npc=25475
2. Выполнить согласно пунктам.
3. Сдать его ему же, и взять другой. (это уже в след.тикете...)

**Текущее обновление ядра:**

Все тот же 165 Build
![1](https://user-images.githubusercontent.com/27158518/31345710-50409d9e-ad1f-11e7-9bf0-dd50808a777b.jpg)

**Comment by Riazarre** [comment]
Проблема конкретно в Вашем персонаже.
