### ISSUE TITLE
[Задание] ID 11644 - Сверхпрочные металлические пластины!

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/VirginCore#537]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

По заданию Мобу соберите 10 сверхпрочных металлических пластин и принесите ему на берег Эха в Борейской тундре.

**Что работает не так?**

НИП http://wowroad.info/?npc=25475 не дает задание http://wowroad.info/?quest=11644. Скрин прикладываю (дубль скрина с другого тикета).

**Как должно работать?**

Обычно без каких-либо критериев он должен выдавать это задание на получение цепочки http://wowroad.info/?quest=11651

**Шаги для воспроизведения ошибки:**

1 - Взять квест http://wowroad.info/?quest=11644 у http://wowroad.info/?npc=25475
2 - Выполнить согласно пунктам.
3 - Сдать его ему же, и взять другой на цепочку http://wowroad.info/?quest=11651
**Текущее обновление ядра:**

Build 165
![1](https://user-images.githubusercontent.com/27158518/31345880-d4dcac8c-ad1f-11e7-8c6b-03d8c22d30ba.jpg)

**Comment by Riazarre** [comment]
Проблема конкретно в Вашем персонаже.
