### ISSUE TITLE
[Задание] ID 11906 - Очищение прудов

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/VirginCore#539]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Соберите 15 запасных деталей Выкрутеня и доставьте их Стальным Глазам в деревню Таунка'ле.

**Что работает не так?**

НИП http://wowroad.info/?npc=26104 не выдает задание http://wowroad.info/?quest=11906, благо у него оно только одно. 

**Как должно работать?**

Вышеуказанный НИП должен выдать задание, для квеста никаких критерий и преквестов нет. Скрин прилагаю.

**Шаги для воспроизведения ошибки:**

1. Взять квест http://wowroad.info/?quest=11906 у http://wowroad.info/?quest=11906
2. Выполнить условие.
3. Сдать задание.

**Текущее обновление ядра:**

Build 165
![1](https://user-images.githubusercontent.com/27158518/31348156-5c807c7a-ad27-11e7-922a-38dbcfab700e.jpg)

**Comment by Riazarre** [comment]
Проблема конкретно в Вашем персонаже.
