### ISSUE TITLE
[Заклинание] ID 12848 - Воспламенение

### ISSUE THREAD

**Issue by SystemHunterD** [VirginTeam/VirginCore#54]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Дот, который появляется на целях после критического удара магом, у которого вкачан талант Воспламенение.

**Что работает не так?**

Не складывается урон при перевешивании.

**Как должно работать?**

При перевешивании должен запоминаться урон, который не успела нанести дота и прибавляться к новой доте.
https://www.youtube.com/watch?v=GUuZ8B0hheo
У мага 100% критический удар. В разные моменты видно, что когда дота успевает тикнуть, то наносит 15-20-30к урона.

**Шаги для воспроизведения ошибки:**

1. Одеть мага в фул крит и вкачать огненную ветку до воспламенения, но еще лучше вкачать на фул - некоторые таланты добавят еще крита.
2. Критануть ожогом(из-за быстрого каста) цель.
3. Проверить урон, который нанесла повесившаяся дота.
4. Неприрывно кастовать ожог до тех пор, пока идут криты. Дота будет постоянно обновлятся.
4. Урон "настаканной" доты не будет отличаться(+-) от урона из шага 3.

**Текущее обновление ядра:**

PTR Server Build20 2017-04-05

**Comment by Gooldark** [comment]
Этот репорт будет переписан, так как баг касается общей механики и затрагивает почти все доты.

**Comment by ForesterDev** [comment]
Не подтверждаю, остаточный урон прибавляется при обновлении доты

**Comment by Gooldark** [comment]
Переписано https://github.com/VirginTeam/VirginCore/issues/71

**Comment by Riazarre** [comment]
Закрыто.
