### ISSUE TITLE
[Задание] ID 11676 - Наконец-то свобода!

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/VirginCore#541]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Освободить 5 узников Плети по просьбе тенелова Канариуса с заставы у ферм Песни Войны.

**Что работает не так?**

НИП http://wowroad.info/?npc=25438 не выдает задание http://wowroad.info/?quest=11676, он один, без цепочки. Скрин прикрепляю.

**Как должно работать?**

НИП должен выдать задание, никаких критерий и преквестов судя из вовхеда нету.

**Шаги для воспроизведения ошибки:**

1. Взять квест http://wowroad.info/?quest=11676 у http://wowroad.info/?npc=25438
2. Выполнить данное условие.
3. Сдать задание обратно.

**Текущее обновление ядра:**

Build 165

![default](https://user-images.githubusercontent.com/27158518/31348426-48f85992-ad28-11e7-9c5f-72870bb5cde3.png)

**Comment by Riazarre** [comment]
Проблема конкретно в Вашем персонаже.
