### ISSUE TITLE
[Задание] ID 11611 - Захваченные Плетью

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/VirginCore#542]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

По заданию штейгера Мортууса из Крепости Песни Войны освободите 5 батраков клана Песни Войны.

**Что работает не так?**

НИП http://wowroad.info/?npc=25280 не выдает задание http://wowroad.info/?quest=11611, скрин прикрепляю. 

**Как должно работать?**

Должен выдать задание, преквестов судя по всему нет. На вовхеде ничего не известно.  

**Шаги для воспроизведения ошибки:**

1. Взять задание http://wowroad.info/?quest=11611 у http://wowroad.info/?npc=25280
2. Выполнить условие.
3. Сдать квест. +1 к ачивменту.

**Текущее обновление ядра:**

Build 165
![default](https://user-images.githubusercontent.com/27158518/31348636-fa40542a-ad28-11e7-938b-3aed4633b968.png)

**Comment by Riazarre** [comment]
Проблема конкретно в Вашем персонаже.
