### ISSUE TITLE
[Задание] ID 11899 - Души распроклятых

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/VirginCore#543]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Используйте ловца душ Великой Матери, чтобы захватить души 10 мехагномов со станции Выкрутеня. Затем вернитесь к Великой Матери Тайге в деревне Таунка'ле.

**Что работает не так?**

НИП http://wowroad.info/?npc=25602 не выдает задание http://wowroad.info/?quest=11899. Все то же, все аналогично предыдущим тикетам.

**Как должно работать?**

НИП http://wowroad.info/?npc=25602 должен выдать его, на задание критериев и преквестов никаких нет. Вовхед ничего об этом не гласит. Скрин прикрепил.

**Шаги для воспроизведения ошибки:**

1. Взять квест http://wowroad.info/?quest=11899 у http://wowroad.info/?npc=25602
2. Выполните условие.
3. Сдать квест, +1 к ачиве.

**Текущее обновление ядра:**

Build 165
![default](https://user-images.githubusercontent.com/27158518/31348963-f48f2f0a-ad29-11e7-87c9-2b45db7dbb6e.png)

**Comment by Riazarre** [comment]
Проблема конкретно в Вашем персонаже.
