### ISSUE TITLE
[NPC] ID 8392 - Пилот Зиггс Зажигатель

### ISSUE THREAD

**Issue by murdalak** [VirginTeam/VirginCore#545]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Пилот стоит на площадке изначально.

**Что работает не так?**

Пилот стоит на площадке изначально.

**Как должно работать?**

Пилот должен появляться только после использования [Обычное сигнальное ружье
](http://ru.wowhead.com/item=10444).

**Шаги для воспроизведения ошибки:**

1. Берём квест [Чародейские руны
](http://ru.wowhead.com/quest=3449)
2. Собираем все 4 таблички 
3. Идём на 77;91 Азшара

**Текущее обновление ядра:**

Build 166 2017-10-07 19:53:21 +0400

**Comment by Kodekc** [comment]
Будет удалён из заселения в ближайшем обновлении
