### ISSUE TITLE
RVR Tips and Tricks - Vanish Sap

### ISSUE THREAD

**Issue by junked** [VirginTeam/VirginCore#553]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не сапается ваниш в рвр.

**Что работает не так?**

В рвр, если противник уходит в ваниш и в это время спамить сап, то он либо вообще не пройдет (противник исчезнет) либо уйдет в имун.

**Как должно работать?**

В рвр есть такая трикса - сап ваниша. У ваниша есть хайдтайм и очень короткий имун (имун на этом сервере почему то очень большой), за счет этого когда вражеский разбойник уходит в ваниш, его можно сапнуть.

**Шаги для воспроизведения ошибки:**

Самый простой способ как сапнуть ваниш не являясь богом РвР:
1. Два разбойника становятся друг перед другом и входят в комбат (просто тыкнуть автоатакой)
2. Один разбойник включает ШД и спамит сап, а второй в это время жмет ваниш
3. ???

**Текущее обновление ядра:**

Build 167 2017-10-11 10:49:14

**Comment by Gooldark** [comment]
В дальнейшем опишу механику стелса более конструктивно, сейчас она кривая увы(

**Comment by junked** [comment]
> а кричать почините то-то то-то не имеет смысла, все нужно расписывать.

На форуме с багами посылают сюда, времени после работы у меня не так много, и я не буду тратить его анализ мувиков и инфы которая осталась со времен 3.3.5 + разжевывание, мне за это не платят.
Я баг нашел, описал, если вам это надо, ищите инфу и чините.

**Comment by Gooldark** [comment]
А с чего вы взяли, что тут за написание репортов кто-то что-то получает? 
Я тоже работаю, у меня тоже почти нет свободного времени, и за написание репортов мне никто ничего не платит. К сожалению все эти организационные вопросы не ко мне. Я лишь написал как тут все фиксили до этого, составлялся репорт с пруфами и только после этого что-то фиксили. То есть все делали игроки. Поэтому приходиться ждать, когда какой-то добрый игрок соизволит все разжевать и разложить по полочкам.

По поводу этого репорта и остальных, часть инфы есть, если интересно могу написать что известно на данный момент и чего пока не достает чтобы описать картину полностью.
