### ISSUE TITLE
Слишком большое значение мирроров

### ISSUE THREAD

**Issue by junked** [VirginTeam/VirginCore#554]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

В механике есть такая штука как мирроры. Это когда 2 игрока одновременно кидают какие то спелы, самые главные это контроли, за счет небольшой искуственной задержки, например, могут кинуть какой то спел или контроль  друг в друга одновременно итд. Самый простой пример это дабл сап\блаинд, чипшот и сап, фир и блаинд, блаинд и овца, репитенс и фир итд итп. 

**Что работает не так?**

Эта задержка не много завышена. Это нормальная практика когда спелы проходят мироором, но тут за счет не много завышенного значения мирорров это происходит до смешного часто. А в купе с лагами сервера начинается полнейший цирк.

**Как должно работать?**

Как я уже писал, это нормальная практика когда спелы проходят мироором, но это должно происходить на много реже.

**Текущее обновление ядра:**

Build 167 2017-10-11 10:49:14

**Comment by Riazarre** [comment]
Пруфы будут?

**Comment by junked** [comment]
Пруфы чего, завышенного флайтайма? Того, что в мувиках показывали лучшие игроки с надроченной реакцией тут делают все чуть ли в каждой дуели.
Мое дело найти баг и зарепортить, хотите чините, хотите оставляйте. Это выгодно в первую очередь Вам а не мне, ваш сервер, ваша работоспособность, ваши донаты. Угу.
