### ISSUE TITLE
Имун ваниша

### ISSUE THREAD

**Issue by junked** [VirginTeam/VirginCore#555]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

У ваниша как всем известно есть имун.

**Что работает не так?**

Время имуна ваниша на данном сервере завышено. Дуели рвр превращаются в цирк, как бы это спешно и провокационно не звучало, но дуели даже самых неопытных разбойников базируются на том, что все чипшоты имунятся рандомным прожатием ваниша после открытия разбойничьей вертушкой. 

У меня лично не вызывает никаких проблем сванишить блаинд стоя **в упор** к разбойнику который его кидает. Так быть НЕ ДОЛЖНО, ибо с правильным временем имуна так могут сделать только скриптеры!!!

**Как должно работать?**

Имун должен быть короче чем он есть сейчас.

**Текущее обновление ядра:**

Build 167 2017-10-11 10:49:14

**Comment by Riazarre** [comment]
Пруфы будут?

**Comment by junked** [comment]
Мувики рвр посмотри. Их миллионы наверное наснимали.

**Comment by Devinette** [comment]
Предоставьте ссылки на данные "миллионы мувиков". Оформите репорт по правилам
