### ISSUE TITLE
[Заклинание] id 70337 - Мертвящая чума

### ISSUE THREAD

**Issue by MedoOf** [VirginTeam/VirginCore#556]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Сбитый таймер заклинания Мертвящая чума в героической сложности. Актуально и для 10гер и для 25гер.

**Что работает не так?**

На видео все видно. Обратите внимание на таймеры дбма и касты Короля Лича. Видео сегодняшнее с текущей обновы. https://www.youtube.com/watch?v=ugD2xhI1bSk

**Как должно работать?**

Правильный таймер накладывания чуму

**Шаги для воспроизведения ошибки:**

1. Посмотреть таймер ДБМА
2. Посмотреть когда Лич использует чуму
3. Немножко удивиться

**Текущее обновление ядра:**

[10:37] Ïîñëåäíåå îáíîâëåíèå ÿäðà: Build 167 2017-10-11 10:49:14 +0400

**Comment by TepaMeTp** [comment]
Возможно сам ДБМ некорректно отображает таймеры, т.к. берет их из об режима (для таймеров идентичных как для хм так и для об версий рейда).
Если на той же леди в хм треш выходит не по таймеру - проблема с дбм.

**Comment by Devinette** [comment]
На тест сервер обновление уже применено. На следующей неделе ожидаем и на х1.
