### ISSUE TITLE
[Задание] ID 11537 | 11538 - Сражение за оружейную Солнечного Края 

### ISSUE THREAD

**Issue by odino4estvo** [VirginTeam/VirginCore#558]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Предвестник Инууро просит вас убить 6 демонов Пылающего Легиона и эмиссара Ненависти на Рассветной площади или в оружейной Солнечного Края. Пригвоздите к земле древком Знамени Расколотого Солнца труп Эмиссара Ненависти.

**Что работает не так?**

При убийстве http://wowroad.info/?npc=25065 нельзя на его трупе использовать http://wowroad.info/?item=34414, пишет ошибку "Сейчас это невозможно" , скрин прикладываю. Так же пробовал и-за интереса проткнуть его копьем когда, он был присмерти (при 5-10% его хп), аналогичная проблема. 

**Как должно работать?**

Убиваем http://wowroad.info/?npc=25065, и на его трупе используем http://wowroad.info/?item=34414 который дается нам по заданию... 

**Шаги для воспроизведения ошибки:**

1. Взять задание.
2. Убить рядом шестерых http://wowroad.info/?npc=25068 что бы появился http://wowroad.info/?npc=25065 с портала.
3. Проткнуть его труп, надеюсь все...

**Текущее обновление ядра:**

Апдейт 176
![1](https://user-images.githubusercontent.com/27158518/31577951-0658d58e-b120-11e7-9524-94d32afe251d.jpg)

**Comment by gmKroshka** [comment]
Квест работает, Знамя Расколотого Солнца на труп Эмиссара применяется
