### ISSUE TITLE
[Задание] Id 2623 Болотный говорун

### ISSUE THREAD

**Issue by assdawr** [VirginTeam/VirginCore#559]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Бенгор не дает задание "Болотный говорун"

**Что работает не так?**

После сдачи Бенгору квеста "Пропавшие приказы" он не выдает следующее задание в цепочке

**Как должно работать?**

После завершения квеста "Пропавшие приказы" Бенгор должен выдавать квест "Болотный говорун"

**Шаги для воспроизведения ошибки:**
Начало цепочки у НПЦ "Павший герой Орды"  (http://wowroad.info/?quest=2784)
1. Первый квест "попавший в немилость" - выслушать рассказ, сдать павшему герою орды
2. Следующий квест "опозоренный" - берется у павшего героя орды, сдается командиру разведотряда Руагу
3. Руаг выдает квест "пропавшие приказы" - который сдается Бенгору
4.  Следующий квест "Болотный говорун" - Бенгор его не выдает

**Текущее обновление ядра:**

Build 167 2017-10-11 10:49:14 +0400  live сервер

**Comment by nordwindd** [comment]
Только хотел писать про этот баг.
Должен заметить, что на основном сервере Бенгор квест не выдает, а на тест сервере квест выдается как положено.

**Comment by Riazarre** [comment]
Будет исправлено в обновлении.

**Comment by nordwindd** [comment]
Мне по прежнему Бенгор не выдает этот квест.
