### ISSUE TITLE
[Задание] Id 838 Некроситет

### ISSUE THREAD

**Issue by assdawr** [VirginTeam/VirginCore#560]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Верховный палач Деррингтон не выдает задание "Некроситет"

**Что работает не так?**

После выполнения задания "Сторожевые башни" Деррингтон не выдает задание "Некроситет"
**Как должно работать?**

Верховный палач Деррингтон должен выдавать задание "Некроситет"

**Шаги для воспроизведения ошибки:**

1. Взять квест "Призыв к оружию: Чумные земли!" 
2. Сдать квест "Призыв к оружию: Чумные земли!" Верховному палачу Деррингтону
3. Взять у Деррингтона квест "Вылазка в стан Алого Ордена", выполнить его и сдать Деррингтону
4. Взять у Деррингтона квест "Сторожевые башни", выполнить его и сдать Деррингтону
5. Взять 55+ уровень
6. Подойти к Деррингтону и обнаружить отсутствие квеста "Некроситет"

**Текущее обновление ядра:**

Build 167 2017-10-11 10:49:14 +0400 live сервер

**Comment by Santaria94** [comment]
Он выдает это задание, но только после выполнения [http://ru.wowhead.com/quest=105](Увы тебе, Андорал). Это не отменяет того, что квест требует корректировки, но тем не менее его можно взять и выполнить.
