### ISSUE TITLE
[Задание] ID 13369 - Против воли рока

### ISSUE THREAD

**Issue by Diagil** [VirginTeam/VirginCore#561]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Задание за Альянс "Против воли Рока", начинающий ветку борьбы за Подгород. | http://wowroad.info/?quest=13369

**Что работает не так?**

Джайна открывает портал, игрок заходит в него и как только он оказывается в Огриммаре, то НПС Орды начинают бить игрока, тем самым не давая завершить квест.

**Как должно работать?**

Джайна должна была открыть портал, зайти в него и мы(игрок и Джайна) поговорили бы с Траллом.

**Шаги для воспроизведения ошибки:**

1. Берем квест "Против воли рока"
2. Говорим с Джайной и она начинает открывать портал
3. Заходим в портал
4. Игрока атакуют вражеские НПС Орды

**Текущее обновление ядра:**

Build 167 2017-10-11 10:49:14 +0400 | Live server

**Comment by Ewropa** [comment]
дубликат https://github.com/VirginTeam/VirginCore/issues/50
