### ISSUE TITLE
Задание 8307 - Desert Recipe (Silithus)

### ISSUE THREAD

**Issue by ivgas** [VirginTeam/VirginCore#578]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Нет доступа к заданию http://wowroad.info/?quest=8307

**Что работает не так?**

Задание Desert Recipe http://wowroad.info/?quest=8307 нельзя получить у нпс Calandrath 
http://wowroad.info/?npc=15174.

**Как должно работать?**

Приведенное задание должно быть доступно у приведенного нпс у обеих фракций с 54 уровня.

**Шаги для воспроизведения ошибки:**

1. Переместить персонажа выше 54 уровня в зону Silithus - Cenarion Hold Inn (Таверна в Крепости Кенария в Силитусе)
2. Обнаружить, что квеста у нпс Calandrath нет.

**Текущее обновление ядра:**

Build 168 2017-10-23 17:03:00 +0400

**Comment by Ewropa** [comment]
задание http://wowroad.info/?quest=8313 выполнено?

**Comment by ivgas** [comment]
Прошу прощения, поставил не тот квест.

**Comment by Ewropa** [comment]
кулинария прокачана на сколько у Вас?, по заданию нужно 285 уровень навыка

**Comment by ivgas** [comment]
281. Понял ошибку, спасибо большое. Пролистал все комменты, но так и не смог найти причину

**Comment by Ewropa** [comment]
Всегда пожалуйста=)
