### ISSUE TITLE
 Залагал Гб на акаунте

### ISSUE THREAD

**Issue by honas211** [VirginTeam/VirginCore#581]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Залагал ГБ на акаунте немогу нечево зделать только одна вкладка

**Что работает не так?**
ГБ неработает на акаунте
Фактический результат — тот, который вы наблюдаете

**Как должно работать?**
Должно откривать все вкладки гб а не только одна и штоб мог забирать з гб и влаживать туда
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Откриваем гб
2. Ложим в гб
3. Забираем з гб

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by Devinette** [comment]
Эта проблема не для Баг-трекера.
Выполните стандартные процедуры-Очистка кеша, антиеррор.
Если проблема остается, сделайте заявку в Центре поддержки ogon3.com/support
