### ISSUE TITLE
[Предмет] 37498 Горькое пойло Бартлетта 

### ISSUE THREAD

**Issue by TepaMeTp** [VirginTeam/VirginCore#583]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
При использовании http://wowroad.info/?item=37498 на персонажа вешается бафф "Тошнотворный запах", по истечении которого или при его отмене персонаж "блюет". Цель попавшая под "блевоту" получает дебафф "Рвота!". 
В случае получения дебаффа к примеру личом он запускаетсая и начинает использовать способности, однако стоит на месте и никого не атакует сам.

Добавьте описание проблемы здесь.
Можно спокойно запускать в бой таким образом различных НПС
**Что работает не так?**
НПС вступают в бой с игроком (дружественные сразу евейдятся)
Фактический результат — тот, который вы наблюдаете
Получение дебаффа мобом на стадии "говорильни" запускает его
**Как должно работать?**
НПС не должны никак реагировать на дебафф "Рвота!"
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Шаг один - получить "Горькое пойло Бартлетта"
2. Шаг два - выпить пойло и встеть лицом к мобу на близкой дистанции
3. Шаг три - отменить бафф "Тошнотворный запах" или дождаться его спада

**Текущее обновление ядра:**
[22:33:32] Последнее обновление ядра: Build 168 2017-10-23 17:03:00 +0400
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование

**Comment by Kodekc** [comment]
Уже исправлено
