### ISSUE TITLE
[NPC] ID 37562 Облако газа, ID 37697 Неустойчивый слизнюк

### ISSUE THREAD

**Issue by mmggnntt** [VirginTeam/VirginCore#596]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**
Х1 PVE Virgin
Нужна корректировка скорости передвижения слизнюка и облака газа на Профессоре Мерзоциде

**Что работает не так?**

Скорость передвижения Неустойчивого слизнюка ( http://ru.wowhead.com/npc=37697 ), а также Облака газа ( http://ru.wowhead.com/npc=37562 ) превышает нормальную, по оффу.

**Как должно работать?**

Видео с офф мира Разувия https://www.youtube.com/watch?v=DBvHQkoTiPg

**Текущее обновление ядра:**
Build 169 2017-11-06 15:24:37 +0400

**Comment by Kodekc** [comment]
Работает правильно.
