### ISSUE TITLE
[Группа заклинаний] Призыв петов (Варлок)

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/VirginCore#60]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

В репорте идет речь про игрока 80 лвла.

а) Призыв стража Скверны(ID 30146), Призыв охотника Скверны(ID 691), Призыв суккуба(ID 712), Призыв демона Бездны(ID 697), Призыв беса(ID 688), Воскрешение мертвых(ID 46584).

б) Призыв стража Скверны(ID 30146), Призыв демона Бездны(ID 697).

в)  Призыв стража Скверны(ID 30146), Призыв охотника Скверны(ID 691), Призыв суккуба(ID 712), Призыв демона Бездны(ID 697).

**Что работает не так?**

а) при призыве петов они появляются не с фул хп, учитываются только их базовые статы.(при дисмаунте все работает верно)

б) базовые 328 выносливости дают хп.

в) неверный базовый урон автоатаки.

**Как должно работать?**

а) при призыве хп пета должно быть полным, даже если это перепризыв при уже существующем пете.

б) должно быть - 5395 хп с 328 стамины(без учета базовой стамины - 6935, то есть за каждую базовую единицу стамины снималось 4,695 хп.)

в) Без учета базового 608 апа у петов урон должен быть:
Призыв демона Бездны(ID 697) 324-449
Призыв суккуба(ID 712) 374-548
Призыв охотника Скверны(ID 691) 246-379
Призыв стража Скверны(ID 30146) 329-495

**Текущее обновление ядра:**

09.04.2017. птр(20-ый билд)

**Доказательства**
http://forum.wowcircle.com/showthread.php?t=552481
http://wowwiki.wikia.com/wiki/Succubus_(warlock_minion)?oldid=2378840
http://wowwiki.wikia.com/wiki/Felhunter?oldid=2386876
http://forum.wowcircle.com/showthread.php?t=152592

**Перенесено** 
http://forum.wowcircle.com/showthread.php?t=538434

**Comment by ForesterDev** [comment]
Исправлено, проверите после применения исправлений
