### ISSUE TITLE
[Задание] - Путеводный огонек

### ISSUE THREAD

**Issue by zet228techies** [VirginTeam/VirginCore#600]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не могу сделать цепочку квестов из-за неправильной работы одного из первых заданий.

**Что работает не так?**

Предмет [Фрагмент пылающей души], получаемый при взятии задания [Путеводный огонек] не применяется вообще

**Как должно работать?**

Предмет [Фрагмент пылающей души] можно использовать, соответственно я могу выполнить задачу [Найдите последнее сокровище Громоборцев]

**Шаги для воспроизведения ошибки:**

1.Взять квест [Путеводный огонек] в Оплоте Громоборцев в Острогорье ( это задание можно получить после задания [Сокровища клана Громоборцев] 
2.Попытаться использовать предмет [Фрагмент пылающей души] в нужном месте ( входе в пещеру или же пройдя некоторое расстояние (я прошёл всю пещеру неистово нажимая на данный предмет и, на всякий случай прокликал много мест на улице, в воздухе и на скалах)) 

**Текущее обновление ядра:**

Build 171 2017-11-07 16:56:13 +0400 logon3. 3.3.5a x1

**Comment by Ewropa** [comment]
Тыкать на предмет нужно там, где взяли задание, а это у NPC http://ru.wowhead.com/npc=21311
в комментариях все подробно расписано http://ru.wowhead.com/quest=10525
