### ISSUE TITLE
[NPC] ID 35090 - Капитан Аэртас Огненный Ястреб

### ISSUE THREAD

**Issue by deexeq** [VirginTeam/VirginCore#602]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Нужна корректировка NPC (http://wowroad.info/?npc=35090)

**Что работает не так?**

Враждебен для Орды

**Как должно работать?**

Должен быть дружелюбным для Орды и враждебным для Альянса.

**Текущее обновление ядра:**

Build 171 2017-11-07 16:56:13 +0400

**Comment by Kodekc** [comment]
Исправлено
