### ISSUE TITLE
Мобы в непроглядной пучине 

### ISSUE THREAD

**Issue by kalambyr18** [VirginTeam/VirginCore#605]

**Comment by kalipsa988** [comment]
оформить нужно по правилам

**Comment by kalambyr18** [comment]
вопрос снимается. там все ок , надо приноровиться просто немного .

**Comment by kalambyr18** [comment]
нет, не снимается. мобы багаются, не агрятся , агро скидывают , бегают как ненормальные туда сюда , невозможно проходить .

**Comment by kalambyr18** [comment]
по каким правилам? я отписал в поддержку в игре , мне сказали писать сюда . я пишу , вы мне пишете по правилам оформлять . что вы хотите от меня !??

**Comment by kalambyr18** [comment]
мой игровой опыт : несколько тысяч пройденных подземелий . очередной вайп в пучине . спасибо вам , разрабы
