### ISSUE TITLE
[Задание] ID 10971 - Секреты Эфириума

### ISSUE THREAD

**Issue by assdawr** [VirginTeam/VirginCore#606]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Нет камер, которые открываются ключом от тюрьмы братства Эфириум

**Что работает не так?**

В Пустоверти по координатам 54,5/40,3 должны находиться камеры, в которых содержатся мобы, из которых в последствии добывается Идентификационная табличка пленника Эфириума, необходимая для завершения квеста 
**Как должно работать?**

Необходимо обеспечить присутствие камер и наличие в них пленников

**Шаги для воспроизведения ошибки:**

1. взять квест Секреты Эфириума
2. летим на место с координатами  54,5/40,3
3. ...

**Текущее обновление ядра:**

Build 171 2017-11-07 16:56:13 +0400

**Comment by deexeq** [comment]
Камеры есть, просто у них большое время респауна.

**Comment by Kodekc** [comment]
Камеры действительно есть. Поправил проблемы с заселением и таймеры возрождения объектов. Изменения будут применены в ближайшем обновлении.
