### ISSUE TITLE
[Группа заклинаний] Призыв питомцев (Рыцарь Смерти)

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/VirginCore#61]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Речь идет про игрока 80 лвл
 ID 46584 Воскрешение мертвых, ID 49206 Призыв горгульи

**Что работает не так?**

а) неверные базовые характеристики вурдалака( ID 46584)

б) неверное количество хп у горгульи(ID 49206) и наличие маны

в) неверное количество передаваемого апа горгулье(ID 49206)

**Как должно работать?**

а) у вурдалака( ID 46584) должно быть:
сила 331
ловкость 856
выносливость 361(базовая стамина не дожна влиять на хп! То есть 361 стамины дают 0 хп!)
интеллект 65
дух 109
базовый ап -20(с учетом силы и ловкости будет 331+856-20=1167 апа)
базовое хп 5338(включая базовые 361)

б) у горгульи(ID 49206) должно быть:
5338(включая базовые 361) базового хп, далее передавалось 30% выносливости(30*(1+0,2*3)=48% при вкачаном таланте Ненасытный мертвец(ID 49572)), если добавить Символ вурдалака(ID 43549) получиться 88%.
Горгуля не должна иметь мп.

в) горгулье(ID 49206) должно предаваться 100% апа дк в момент призыва и еще 4%*количество талантов вкинутых в Порочность(ID 49638).
Иначе говоря Порочность(ID 49638) должна влиять на горгулю.

**Текущее обновление ядра:**

09.04.2017. птр 20 билд.

**Доказательства**
а) http://forum.wowcircle.com/showthread.php?t=553862 - тема про вурдалака.

б) http://www.warcraftmovies.com/pv.php?l=shious - 07:39 у дк 25741 хп(1780 стамины) у гули 21002 хп
5338+1780 * 0,88 * 10 = 21002
https://www.youtube.com/watch?v=jA5I7jCqyfg - у дк 32921 хп(2498 стамины) у гули 27322 хп
5338+2498 * 0,88 * 10 = 27320,4
почти совпало в обоих случаях

в) http://forum.wowcircle.com/showthread.php?t=391578 -  старая тема в которой определили, что талант Порочность(ID 49638) должен давать горгуле дополнительные 20% апа.

**Comment by Riazarre** [comment]
http://forum.wowcircle.com/showthread.php?t=553862 - закрыл

**Comment by ForesterDev** [comment]
Исправлено, тестируем после применения

**Comment by Gooldark** [comment]
Пункт в) неплохо бы переделать, скрины кидал в конфу.
