### ISSUE TITLE
[Группа NPC] Боевой страж Сартура и ее королевская стража.

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/VirginCore#611]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

[Боевой страж Сартура](http://ru.wowhead.com/npc=15516)
[Королевский страж Сартуры](http://ru.wowhead.com/npc=15984)

**Что работает не так?**

Отсутствует привязка стражей к Сартуре. Ее можно убивать без ее стражей. Они присутствуют в подземелье, но не патрулируют территорию вместе с Сартурой, а также никак не реагируют на игроков, если они вступили в бой с боссом.

**Как должно работать?**

Стражи должны постоянно сопровождать Сартуру, а также вместе с ней вступать в бой с рейдом. Если бой окончился вайпом рейда, то все погибшие стражи должны быть воскрешены.

Видео: [Бой с Сартурой](https://www.youtube.com/watch?v=3WbnOsGvJl4)

**Текущее обновление ядра:**

Live Server
Build 173 2017-11-08

**Comment by Kodekc** [comment]
Исправлено. Изменения будут применены в ближайшем обновлении
