### ISSUE TITLE
[Задание] ID 12910 - Найти Преступника.

### ISSUE THREAD

**Issue by R38CS** [VirginTeam/VirginCore#612]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

квест делает порядочных игроков читерами по неволе сылка на видео ниже.

**Что работает не так?**

Друид летает во всех формах как на читах!

**Как должно работать?**

всё должно быть хорошо!

**Шаги для воспроизведения ошибки:**

https://www.youtube.com/watch?v=4ZdPe__OS6U&t=1s

**Текущее обновление ядра:**
Logon 3 WowCircle Development
Build 173 2017-11-08 19:06:21 +0400
проверял как на х1 когда получил за это бан, так и на тестовом.(Само видео было снято на тестовом)

**Comment by Riazarre** [comment]
Единственный баг, который здесь есть - баг с репорта #22 
Но ни летать, ни получить скорость флая при отмене формы - нельзя.
Пруф https://youtu.be/ngNO0iY_Mtw
Закрыто.

**Comment by R38CS** [comment]
,бан то снимите пожалуйста с друида Dargges

**Comment by R38CS** [comment]
На моём видео видно, что никаких читов я не использовал, просто может нужно кэш почитстить или новый клиент скачать

**Comment by R38CS** [comment]
На моём видео видно, что я не использую никаких читов, снимите бан
пожалуйста. Я обязуюсь больше не опльзоваться данной фичей и пи подобных
сбоях буду сразу делать релог

13 ноября 2017 г., 17:28 пользователь Overfire <notifications@github.com>
написал:

**Comment by R38CS** [comment]
АУУУ

**Comment by R38CS** [comment]
Причём тут баг?? Даже если бага не обнаружено моей вины ни в чём нет, за что мне бан? Видео посмотрите внимательно где какие читы я использую? Мб с помощью телепатии у меня персонажи летают? Я бы уже 80 взял и фармил ппг, что ввы как не люди...
