### ISSUE TITLE
[Задание] ID 11300 -Поражение на ринге

### ISSUE THREAD

**Issue by wowerpower** [VirginTeam/VirginCore#613]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Нет мобов по квесту

**Что работает не так?**

После взятия квеста не появляются мобы +Олуф Неистовый

**Как должно работать?**

После взятия квеста должны появляться Гладиаторы после их убийства выходит  Олуф Неистовый с него выпадает Древняя тайнопись предмет для завершения квеста. 

**Шаги для воспроизведения ошибки:**

1. Берем кв
2. Убиваем гладиаторов. Выходит Олуф Неистовый убиваем его, лутаем берем Древняя тайнопись 
3. сдаем кв

**Текущее обновление ядра:**
Build 175 2017-11-13 15:53:58 +0400

**Comment by Ewropa** [comment]
он появляется, но у стены, если его не начать атаковать исчезает, а должен он после появления бежать в центр ринга, но это уже другая история

**Comment by wowerpower** [comment]
Спасибо все работает сделал кв.

**Comment by gmKroshka** [comment]
http://forum.wowcircle.com/showthread.php?t=516298
