### ISSUE TITLE
[Подземелья] ID 10264 - Солакарский огнечервь

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/VirginCore#615]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Отсутствует босс

**Что работает не так?**

При использовании http://wowroad.info/?object=175245 лутается предмет http://wowroad.info/?item=13371, но больше ничего не происходит

**Как должно работать?**

При использовании объекта http://wowroad.info/?object=175245 должен начаться ивент: появляется 6 волн по 2 моба с интервалом примерно 30 сек, после их уничтожения появляется сам босс http://wowroad.info/?npc=10264
**Шаги для воспроизведения ошибки:**

1. Открыть http://wowroad.info/?object=175245
2. Ждать

**Текущее обновление ядра:**

Последнее обновление ядра: Build 175 2017-11-13 15:53:58 +0400

Доказательства
http://ru.wowhead.com/npc=10264#comments

**Comment by Santaria94** [comment]
Дубликат
[https://github.com/VirginTeam/VirginCore/issues/13](https://github.com/VirginTeam/VirginCore/issues/13)
