### ISSUE TITLE
[Рейд] Ульдуар (ID 33136, 33968 Страж Йогг-Сарона)

### ISSUE THREAD

**Issue by sega693** [VirginTeam/VirginCore#617]
Описание:

http://wowroad.info/?npc=33136
http://wowroad.info/?npc=33968

Что работает не так?
Не восприимчивы к таунтам (не имунитет, а просто безразличны). Агро висит на танке, но мобы бегут в рейд. Спеллами тоже не агрятся, только мили атакой (если сорвешь ей агро). Единственный нормальный вариант - за дк притягивать.
Если весь рейд встает в центре часть мобов просто эвейдится и никак не хочет идти в центр.

**Как должно работать?**
Должны нормально агриться.

Текущее обновление ядра:
Build 175 2017-11-13 15:53:58 +0400

**Comment by VirginGuard** [comment]
Тест

**Comment by VirginGuard** [comment]
Тестирование бот системы

**Comment by gmOverfire** [comment]
Test

**Comment by sega693** [comment]
Вы чего разбушевались :D

**Comment by gmKroshka** [comment]
Исправлено в последнем обновлении
