### ISSUE TITLE
[Игровая механика] Бонус 2т9 у Чернокнижника

### ISSUE THREAD

**Issue by Galakras** [VirginTeam/VirginCore#618]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не работает бонус от 2 штук из  9-го сета у чернокнижника. 
http://wowroad.info/?item=47782

**Что работает не так?**

1) Взял специализацию демонология.  Одел 2 штуки из 9-го тира http://wowroad.info/?item=47782 + http://wowroad.info/?item=47780 .
И бил петом - Бес (огненная стрела) Манекен 80-го уровня в течении 6- минут  (3 раза) - у пета было 172 каста, и по рекаунту у Беса было -  18%, 20%, 19% крита.

2) Потом одел 4 штуки из **10-го тира**, и повторил - пет (Бес) бил манекен Огненной стрелой 3 раза по 6 минут - 171каст - 25%, 26%, 21% крита. Посмотрел по Рекаунту.

**Как должно работать?**

При одевании 2х штук из 9-го сета - у пета крит должен увеличиться на 10%. 

На мой взгляд - при одевании 2х штук из 9го сета, пет (Бес http://wowroad.info/?spell=30066 ) должен был критовать огненной стрелой ( http://wowroad.info/?spell=47964 ) - на 10% больше, чем без т9. То есть, когда я одевал уже 9-й тир, крит пета должна была быть в районе  30%-35% из 172 кастов(6 минут боя на манекене).
Ну , или, как то должна различаться процент крита у Беса, при одевании т9, и при одевании т10. А так получается, что при т10  крит у пета даже больше, чем при 2шт из т9.

**Шаги для воспроизведения ошибки:**

1. Одень 2 штуки из 9-го тира Чернокнижника.
2. Включить счетчик, и бить манекен в течении... 6 минут. И ты и пет должны бить. Иначе спадает комбат и Рекаунт перестает считать.
3. После истечения 6 минут, отойтти от манекена, отозвать пета(беса) и после спада комбата - посмотреть Рекаунт - количество критов и некритов.
Я повторил 3 раза - одев 2штуки из 9-го тира Чернокнижника.
И еще 3 раза - одев 4 штуки из 10-го тира Чернокнижника.

**Текущее обновление ядра:**

x1 Build 175 2017-11-13

**Comment by Riazarre** [comment]
Подтверждаю
2т9 http://joxi.ru/p279zLKTok8WNr
без http://joxi.ru/823x0j6IJY3DoA

**Comment by Galakras** [comment]
Мой тест т9
https://youtu.be/pPy7Dqmx8Mc
https://www.youtube.com/watch?v=cmPjyksvp08&list=PLSElkc_fXgDunjOw-ptx1J9D-_ac_pcsi&index=4

Мой тест т10
https://youtu.be/pPy7Dqmx8Mc
https://www.youtube.com/watch?v=pPy7Dqmx8Mc&list=PLSElkc_fXgDunjOw-ptx1J9D-_ac_pcsi&index=5

Обращаю ваше внимание что в начале и в конце видео статы одинаковы - крит и хаста.
Там можно в начале секунд 20 посмотреть, и дальше уже конец смотреть последние секунд 20. В середине нудная битье манекена в течении 6 минут.
