### ISSUE TITLE
[NPC] ID 23090 - Тролль-верхолаз

### ISSUE THREAD

**Issue by Kodekc** [VirginTeam/VirginCore#619]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Неправильное/недостаточное заселение NPC - Тролль-верхолаз.

**Дополнительная информация**

Недостаточно информации для проведения корректного заселения
http://ru.wowhead.com/npc=23090

**Текущее обновление ядра:**

Build 175

**Comment by deexeq** [comment]
Вот нашёл http://db.wowz.ru/?npc=23090
http://wowwiki.wikia.com/wiki/Troll_Roof_Stalker

**Comment by Kodekc** [comment]
Ага, это значит надо копаться в старых базах бк, там есть заселение. Понятно. Спасибо, deexeq.

**Comment by Kodekc** [comment]
Заселены. Изменения будут применены в ближайшем обновлении
