### ISSUE TITLE
[NPC] ID 3142 - Оргнил Душегрыз

### ISSUE THREAD

**Issue by maxymasan** [VirginTeam/VirginCore#620]
**НПЦ Оргнил Душегрыз неактивен:**

Проблема с НПЦ [Оргнил Душегрыз](http://ru.wowhead.com/npc=3142), находится в локации Колючий Холм. Не дает квесты и также не принимает. Связанные с ним квесты - "Явится к Оргнилу", "Сгущаются черные тучи". После того как сервер был перезагружен, смог взять квест "Сгущаются черные тучи", но после его выполнения снова не могу сдать, так как НПЦ неактивен

**Что работает не так?**

Не принимает задания, и не выдает новые.

**Как должно работать?**

Должен быть активным, выдавать задания и завершать их.

**Текущее обновление ядра:**

Build 175

**Линк на скрин с пруфом**

http://shot.qip.ru/00RGO0-3Qx1MvcHL/

**Comment by Kodekc** [comment]
Я же его исправлял. Вы уверены, что проблема всё ещё сохранилась?

**Comment by Kodekc** [comment]
Да, вижу, изменения ещё не применялись.

**Comment by Hargell79** [comment]
Сдал квест "Сгущаются тучи"[http://wowroad.info/?quest=806](url), но квест "Маргоз" [http://wowroad.info/?quest=828](url) не дает
