### ISSUE TITLE
Квест "Явиться к Оргнилу" не сдается

### ISSUE THREAD

**Issue by ZenoMacabre** [VirginTeam/VirginCore#623]
**Описание:**

Квест "Явиться к Оргнилу" не сдается. http://wowroad.info/?quest=823

**Что работает не так?**

НПС не ведет себя, как должен. Не реагирует на квест.

**Как должно работать?**

"Поговорите с Оргнилом Душегрызом на Колючем Холме."
19.11.17 

set realmlist logon3.wowcircle.com

x1 pve Virgin

проблема появилась 19.11.17

приоритет проблемы 3-5

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by gmOverfire** [comment]
Вы уверены? Квест работает. Сделайте антиеррор, удалите папку Cache, и пробуйте еще раз.

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/VirginCore/issues/620
