### ISSUE TITLE
Забытый город

### ISSUE THREAD

**Issue by Malivan** [VirginTeam/VirginCore#625]
Невозможно пройти инст полностью.

Проходя инст упираемся в дверь которая требует ключь (http://ru.wowhead.com/item=18268).
Как видно из скрина размешенного на вовхед, 2 стражника  охраняют дверь, с них и должен падать ключь. Ключь не падает.

Мобы подписаны не так как на вовхед, т.е. возможно ето другие мобы. При етом нужных мобов нет.

Дверь не возможно открыть.

Должны быть нужные мобы с дропом ключа.

Открыть дверь, убить ласт босса, проити инст до конца, получить достижение "забытый город".

1. Шаг один: Зайти в часть подземелия "забытый город" для которой требуется "серповидный ключь".
2. Шаг два: Пройти в локацию внутреннийдвор с помошью "ключь от внутреннего двора".
3. Шаг три: Пойти в следующую локацию подземелья.

Build 175  2017-11-13  15:53:58  +0400

**Comment by Kodekc** [comment]
Ключ падает с Стражник Мол'дар, шанс выпадения не 100%, может ключ и не упасть, вы можете прочитать комментарии с того же wowhead, где ребятам ключ не выпал и они не смогли открыть дверь дальше.

**Comment by Malivan** [comment]
Спасибо, сам себя ввел в заблуждение, уже прошел инст сегодня. Спасибо за
своевременную реакцию.

2017-11-22 16:53 GMT+02:00 Kodekc <notifications@github.com>:
