### ISSUE TITLE
Исполнение приказа

### ISSUE THREAD

**Issue by anmaxien** [VirginTeam/VirginCore#628]
**Описание:**
Что ж, <парень/подружка>, у Ракжака есть для тебя очень, очень важное дело. Следопыт выследил к северу отсюда у реки раненого длинноязыкого. Иди и поймай его.

Не бери охотника в этот раз, охотник его захочет убивать. А я хочу спрятать его у себя. Я буду тыкать в него, а он будет говорить мне разные вещи.

Теперь иди и притащи мне длинноязыкого.
http://ru.wowhead.com/quest=12540

**Что работает не так?**

При попытке разговора с оракулом ничего не происходит, он просто лежит, диалоговое окно с ним не открывается.

**Как должно работать?**

При попытке разговора с оракулом должно появляться контекстное окошко, затем вылезает кроколиск, его убиваем и квест засчитывается.

build 1752017-11-13

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/VirginCore/issues/457
