### ISSUE TITLE
[NPC] ID 4586 - Грэхем ван Тален

### ISSUE THREAD

**Issue by Crazikus** [VirginTeam/VirginCore#629]
**Описание:**

Добавьте описание проблемы здесь.

  **Описание**
Грэхем ван Тален нету квеста в подгороде
 **Что работает не так?**
Грэхем ван Тален не даёт квеста

 **Как должно работать?**

 должен дать квест на специлизацию инженерии

Грэхем ван Тален у нпс должно быть 2 квеста на Гоблинскую и Гномскую инженерию

**Шаги для воспроизведения ошибки:**

1. Взаимодействую с нпс
2. Нет квеста
3. Должен быть квеста,до обновы была спеца на гоблинскую инженерию

**Текущее обновление ядра:**

Build 175 2017-11-13 15:53. logon3 WowCircle Development

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by gmKroshka** [comment]
В связи с удалением специализаций Гоблинского и Гномского механика в Инженерном деле был удален прогресс по заданиям, которые выполнялись Вами ранее. Чтобы вновь овладеть специализацией, Вам требуется выполнить один из следующих квестов:
http://wowroad.info/?quest=3643 - берется у http://wowroad.info/?npc=7406 - Гномский механик

http://wowroad.info/?quest=3639 - берется у http://wowroad.info/?npc=8126 - Гоблинский механик
После выполнения этих заданий Вы получите специализацию.

Обратите внимание, что не играет роли тот факт, какая специализация была у Вас до сброса, важно лишь то, на какую были сделаны квесты.

**Comment by Crazikus** [comment]
gmKroshka нет у них кв,что делать?

**Comment by gmKroshka** [comment]
Оформляйте заявку в ЦП http://logon3.com/support

**Comment by Crazikus** [comment]
цп это куда?

**Comment by gmKroshka** [comment]
Я дала ссылку выше

**Comment by Crazikus** [comment]
Центр Поддержки,а подробней можно?я просто уже неделю везде лазию и по форумам и везде,одни туда посылают другие туда.
Меня по ссылки кидает на главную страницу,подробней можно?
