### ISSUE TITLE
[Лучший табак Сиаби] в инсте Стратхольм

### ISSUE THREAD

**Issue by sosed213** [VirginTeam/VirginCore#63]
Квест [Лучший табак Сиаби] в инсте Стратхольм не работает. Коробка лежит там где и должна. Но не активна, т.е. мышкой если навести ничего не происходит.

**Comment by Devinette** [comment]
Оформите репорт по правилам, посмотрите шаблонное оформление других репортов.

**Comment by sosed213** [comment]
Мне проще отказаться от квеста. Я просто Вам дал ссылку на нерабочий квест. А Вы, если хотите, сами оформляйте репорт по шаблону.

**Comment by Kodekc** [comment]
Никто за вас оформлять не будет. Раз вы посетили баг трекер, следуйте правилам установленым здесь или будьте в роли наблюдателя.
