### ISSUE TITLE
Очень долгий респ квест айтема

### ISSUE THREAD

**Issue by pallyLunna** [VirginTeam/VirginCore#632]
**Описание:**

Квест - Промокшие страницы, требуется полутать Гримуар стихий Антеола

**Что работает не так?**

Очень долгий респ квест айтема Гримуар стихий Антеола

**Как должно работать?**

Респ должен быть не дольше 10 сек

**Шаги для воспроизведения ошибки:**

Выполнение квеста

**Текущее обновление ядра:**

Билд 176 2017-11-27

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by gmOverfire** [comment]
С чего вы решили, что респаун предмета должен быть 10 секунд?

**Comment by pallyLunna** [comment]
Опыт игры на офе, появляется и доступен для лутания квест-айтем практически мгновенно после того, как другой игрок его полутал.

**Comment by gmOverfire** [comment]
Я рад поверить Вам на слово, но не могу.
Есть какой-либо источник с информацией об этом?

**Comment by pallyLunna** [comment]
Какого рода вам информация нужна?  или источник?

**Comment by gmOverfire** [comment]
Источник информации, который актуален по отношению к дополнению 3.3.5а
