### ISSUE TITLE
[Игровая механика] - Предметы со случайными характеристиками

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/VirginCore#635]
**Описание:**

Нет отображения названия и стат предмета

**Что работает не так?**

При осмотре другого персонажа, если на нем есть шмотка с рандомной меткой, пишется только название шмотки без названия самой метки. На шмотках из http://db.logon3.com/?item=51999, отсутствуют статы
Пример: На персонаже Мерцающие брюки с печатью меткости на +26 силы атаки в дальнем бою, а при осмотре этого персонажа другим персонажем будет видно только Мерцающие брюки +26 силы атаки в дальнем бою
Пример 2:  На персонаже Пояс неутомимости с меткой преступника +5 к ловкости, +5 к выносливости, +10 к силе атаки, а при осмотре этого персонажа другим персонажем будет видно только Пояс неутомимости с меткой преступника +0 +0 +0

**Как должно работать?**

При осмотре персонажа другим персонажем должно полностью писать название вместе с названием рандомной характеристики 

**Шаги для воспроизведения ошибки:**

1. Найти перса со шмоткой, у которой рандомная метка
2. Увидеть отсутствие названия самой метки
3. Шаг три

**Текущее обновление ядра:**

Последнее обновление ядра: Build 177 2017-11-28 11:50:44 +0400

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by kalipsa988** [comment]
![wowscrnshot_110717_195129](https://user-images.githubusercontent.com/29568428/33445689-b0a7f5a2-d60e-11e7-9e81-d93442b3b319.jpg)
![wowscrnshot_110717_200211](https://user-images.githubusercontent.com/29568428/33445690-b0cf896e-d60e-11e7-8e51-2877414083db.jpg)
вот так должно при осмотре отображаться

**Comment by kalipsa988** [comment]
![wowscrnshot_110417_205924](https://user-images.githubusercontent.com/29568428/33445785-014ecce2-d60f-11e7-8a7b-cdbf36a68a33.jpg)
![wowscrnshot_110417_230237](https://user-images.githubusercontent.com/29568428/33445786-0172ed0c-d60f-11e7-98ea-2aa1546bdf93.jpg)
у нас такое

**Comment by gmOverfire** [comment]
Баг есть. 
![image](https://user-images.githubusercontent.com/26819342/33445860-08949fac-d620-11e7-92b2-78a467406aa5.png)

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении

**Comment by kalipsa988** [comment]
Проблема появилась следующая, название шмотки при осмотре пишется с названием метки, но нельзя линкануть шмотку в чат, линкуется без название метки предмета и ничего не пишется
