### ISSUE TITLE
[Задание] ID 5441 - Ленивые батраки

### ISSUE THREAD

**Issue by pallyLunna** [VirginTeam/VirginCore#637]
**Описание:**

Квест "Ленивые батраки" http://db.logon3.com/?quest=5441 в начальной локации орков\троллей вешает PvP флаг на персонажа

**Что работает не так?**

При использовании Дубинки Штейгера на спящем орке персонаж флагается на пвп

**Как должно работать?**

ПвП флаг не должен вешаться.

**Шаги для воспроизведения ошибки:**

1. Выбрать спящего орка
2. Использовать на нем квестайтем
3. Получить пвп флаг

**Текущее обновление ядра:**
177 билд
Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
