### ISSUE TITLE
[Подземелье] Испытание Чемпиона - (ID 35451 Черный Рыцарь)

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#64]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)
**Описание**

```
Entry: 35451
DisplayID: 21300 (Native: 29837).
```

**Что работает не так?**

Труп босса исчезает через 30 секунд. Нужно поправить существо, чтобы считалось боссом подземелья, т.к. у него другое время исчезновения трупа.

**Как должно работать?**

Труп должен существовать положенное для боссов подземелий время.

**Текущее обновление ядра:**

PTR: Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверяйте после обновления
