### ISSUE TITLE
[Подземелье] Гробницы маны (ID 3792)

### ISSUE THREAD

**Issue by pallyLunna** [VirginTeam/VirginCore#641]
**Описание:**

Инстанс Гробницы маны
Босс - Принц Шаффар
Не исчезают призванные адды после вайпа

**Что работает не так?**

Инстанс Гробницы маны
Босс - Принц Шаффар
Не исчезают призванные адды после вайпа

**Как должно работать?**

После вайпа сферы, которые принц Шаффр призывает должны исчезнуть.

**Шаги для воспроизведения ошибки:**

1. Старт энкаунтера с боссом Шаффар
2. Появляются призванные боссом сферы
3. Вайп группы
4. Сферы остаются на месте
https://i.gyazo.com/a178dd011cc3209a1d32a5f0f42a71d0.jpg

**Текущее обновление ядра:**
177 билд

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by ForesterDev** [comment]
Сферы после сброса энкаунтера должны исчезать и появляться 3 вокруг босса. А вот ученики должны исчезать в полном объеме. Будет исправлено после обновления
