### ISSUE TITLE
[Достижение] ID 3802 - Исповедница Серебрянного Авангарда

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#65]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

http://ru.wowhead.com/achievement=3802

**Что работает не так?**

Некорректное условие получения достижения - убил босса http://ru.wowhead.com/npc=34928 только 1 раз и видел только 1 воспоминание.

**Как должно работать?**

Нужно убить босса минимум 5 раз, как написано в тултипе достижения.

**Текущее обновление ядра:**

PTR: Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверяйте после обновления
