### ISSUE TITLE
[Предмет] ID 36862 - Потертая тролльская игральная кость

### ISSUE THREAD

**Issue by zyxellgit** [VirginTeam/VirginCore#655]
**Описание:**
http://db.logon3.com/?item=36862
потертая тролльская игральная кость
http://ru.wowhead.com/item=36862
при использование выдает в чат буржуйский текст, в котором к тому же не работает линк на предмет
![wowscrnshot_120717_234706](https://user-images.githubusercontent.com/29210390/33733395-80049bd8-dbab-11e7-93a9-b6c9b7f2d33f.jpg)

**Как должно работать?**

текст на русском языке

**Шаги для воспроизведения ошибки:**

кинуть кость

**Текущее обновление ядра:**

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Trombocid** [comment]
КПД репорта 146%. Самое то чтобы придать объём патчноуту без реальных исправлений

**Comment by gmOverfire** [comment]
Переводом различных текстов занимаются активисты Logon3, разработчик забирает их фиксы и применяет на сервер, поэтому сарказм неуместен.

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
