### ISSUE TITLE
[Задание] ID 11978 - Добро пожаловать в Орду

### ISSUE THREAD

**Issue by ilp2401** [VirginTeam/VirginCore#656]
**Описание:**

После прохождения квеста "Таурен среди таунка" http://ru.wowhead.com/quest=11977 НПС Эмиссар Светлое Копыто http://ru.wowhead.com/npc=26181 не выдает следующий по цепочке квест "Добро пожаловать в Орду" http://ru.wowhead.com/quest=11978. 

**Что работает не так?**

Не возможно получить квест "Добро пожаловать в Орду" http://ru.wowhead.com/quest=11978 и продолжить цепочку

**Как должно работать?**

НПС Эмиссар Светлое Копыто http://ru.wowhead.com/npc=26181 должен выдавать квест

**Шаги для воспроизведения ошибки:**

1. Выполнить квест "Таурен среди таунка" http://ru.wowhead.com/quest=11977
2. Сдать квест НПС Эмиссар Светлое Копыто http://ru.wowhead.com/npc=26181

**Текущее обновление ядра:**

Build 178 2017-12-05 11:53:10 +0400

**Comment by Ewropa** [comment]
Исправлена возможность брать задание "Добро пожаловать в Орду" (11798) после выполнения "Таунка и таурены" (11979) либо "Таурен среди таунка" (11977)
Теперь, можно на выбор взять задание "Таунка и таурены" либо "Таурен среди таунка", после выполнения одного из них, второй становится не доступным, при этом целостность цепочки не нарушается.
