### ISSUE TITLE
Квест: в ожидании дальнейших распоряжений.

### ISSUE THREAD

**Issue by sherwooddwarf** [VirginTeam/VirginCore#659]
**Описание:**
В задании http://db.logon3.com/?quest=13371
Нужно телепортироваться в тирисфальский лес и поговорить с Броллом Медвежей Шкурой.

**Что работает не так?**

Нету нпс Бролла М Ж.

**Как должно работать?**
Что бы он был .

**Шаги для воспроизведения ошибки:**
Не особо пойму к чему столько сложностей.

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Ewropa** [comment]
Дубликат https://github.com/VirginTeam/VirginCore/issues/140

**Comment by sherwooddwarf** [comment]
26 апреля писали, а результата нет.13.12.2017, 08:13, "Ewropa" <notifications@github.com>:Дубликат #140

**Comment by gmKroshka** [comment]
От дублирования репорта ускорение исправления не будет.
