### ISSUE TITLE
[Задание] ID 11241 - Путь огня

### ISSUE THREAD

**Issue by Ewropa** [VirginTeam/VirginCore#66]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не правильно работает задание http://ru.wowhead.com/quest=11241

**Что работает не так?**

http://ru.wowhead.com/npc=23784 глухонемой и имеет кривые маршруты движения

**Как должно работать?**

При спасении должен говорить с персонажем и нормально передвигаться

**Шаги для воспроизведения ошибки:**

1. Взять задание
2. Походить следом за аптекарем

**Текущее обновление ядра:**

PTR: Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
