### ISSUE TITLE
Баг на ОЛО

### ISSUE THREAD

**Issue by Kielanna** [VirginTeam/VirginCore#662]
Внутренние мастерские крепости принадлежат Альянсу, несмотря на то, что ОЛО находится под контролем Орды, что дает игрокам Альянса возможность захватить лишь одну внешнюю мастерскую и построить сразу 16 машин, вместо 4х. Когда ОЛО под контролем Альянса, с мастерскими все в порядке, т.е. они также находятся под контролем Альянса.

Logon3 х1 PVE
**Текущее обновление ядра:**
Build 178 2017-12-05 11:53:10 +0400

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by ForesterDev** [comment]
Уже исправлено и применено
