### ISSUE TITLE
[Задание] ID 7622 - Баланс Света и Тени

### ISSUE THREAD

**Issue by Delicate111** [VirginTeam/VirginCore#663]
**Описание:**

Не появляются крестьяне

**Что работает не так?**

Не появляются крестьяне
**Как должно работать?**
Спасите жизни 50 крестьян прежде, чем 15 из них будут убиты ( https://www.youtube.com/watch?v=mW6JJshDOm8 )
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
Появляются крестьяне
**Шаги для воспроизведения ошибки:**

1. Беру квест
2. Крестьяне не появляются
3. Шаг три

**Текущее обновление ядра:**
Logon 3 WowCircle Development
Последнее обновление ядра: Build 178 2017-12-05 11:53:10 +0400
Игроков онлайн: 4236 ( максимум: 4267). игроков в очереди: 0 (максимум: 0)
Продолжительность работы сервера: 8 Hour(s) 34 Minute(s) 41 Second(s)
Серверная задержка: 126
Следующее начисление очков арены: 17.12.2017 10:22

**Comment by gmOverfire** [comment]
Дубликат
#108
