### ISSUE TITLE
ПРОПАЛИ ВСЕ НПЦ КВЕСТ-ГИВЕРЫ

### ISSUE THREAD

**Issue by HypeBeastUA** [VirginTeam/VirginCore#664]
**Описание:**

Пропало большинство НПЦ в стартовой локации и в Элвинском лесу

**Что работает не так?**

Пропало большинство квест-гиверов, учителей профессий, учителей навыков в Элвинском лесу, включая стартовую зону. 

**Как должно работать?**

НПЦ должны быть на своих местах, выдавать квесты, обучать.

**Шаги для воспроизведения ошибки:**

1. Пробежаться по Элвинскому лесу и посмотреть каких НПЦ не хватает (практически всех)!!! 

**Текущее обновление ядра:**

Build 178 

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by gmKroshka** [comment]
Виновного наказали. Ожидайте возвращения нпц на свои места

**Comment by HypeBeastUA** [comment]
Добрый вечер! По прежнему не работает, нет ни одного НПЦ, новые персонажи абсолютно не имеют возможности прокачки. НПЦ не появились с момента вашего ответа, то есть 7 часов.
