### ISSUE TITLE
ПРОПАЛИ ВСЕ НПЦ КВЕСТ-ГИВЕРЫ 

### ISSUE THREAD

**Issue by HypeBeastUA** [VirginTeam/VirginCore#666]
**Описание:**

После ответа ГМ, НПЦ не появились по прошествии 7 часов.

Virgin x1 PVE 3,3,5a

Пропало большинство НПЦ в стартовой локации и в Элвинском лесу. Ещё вчера некоторые из НПЦ были на своих местах, сегодня уже нет ни одного! Торговцы, квест-гиверы, учителя, все! 

**Что работает не так?**

Пропали все квест-гиверы, учителя профессий, учителя навыков в Элвинском лесу, включая стартовую зону.

**Как должно работать?**

НПЦ должны быть на своих местах, выдавать квесты, обучать.

**Шаги для воспроизведения ошибки:**

1. Пробежаться по Элвинскому лесу и посмотреть каких НПЦ не хватает (практически всех)!!!

**Текущее обновление ядра:**

Build 178 2017-12-05 11:53:10 +0400

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by gmOverfire** [comment]
В прошлом репорта был ответ "Ожидайте... ", что означает необходимость подождать, пока НПЦ не будут возвращены на место. Дублировать репорты нет необходимости.
