### ISSUE TITLE
[Заклинание] ID 3714 - Льдистый путь

### ISSUE THREAD

**Issue by kalipsa988** [VirginTeam/VirginCore#667]
**Описание:**

Морозная аура рыцаря смерти сковывает льдом воду под его ногами и позволяет участникам его группы или рейда ходить по воде в течение 10 мин. Эффект прерывается при получении урона.

**Что работает не так?**

Слетает после наложения на вас Метка охотника(http://db.logon3.com/?spell=53338)
https://www.youtube.com/watch?v=QjC0GQVC20A&feature=youtu.be

**Как должно работать?**

Льдистый путь должен слетать только при получении урона.

**Шаги для воспроизведения ошибки:**

1. Повесить на себя Льдистый путь
2. Попросить ханта в дуэли кинуть только Метка охотника
3. Увидеть 

**Текущее обновление ядра:**

Последнее обновление ядра: Build 178 2017-12-05 11:53:10 +0400

**Comment by Santaria94** [comment]
Ошибки нет, так и должно быть.

C WoWHead, От jsfritz (275 – 1) 2009-01-12 (Обновление 3.0.3)
> The description for this skill is accurate, to a certain extent. However, it seems certain non-damaging combat skills will also cancel the effect. I just had vibrant blood cast on me and it canceled path of frost.
