### ISSUE TITLE
[Заклинание] ID 605 - Контроль над разумом

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/VirginCore#668]
**Описание:**

http://db.logon3.com/?spell=605

**Что работает не так?**

При воздействии на NPC ломает механику эвейда. NPC начинает бежать за игроком на неограниченные расстояния, т.е. зона эвейда полностью пропадает у NPC. Эвейд после применения заклинания может быть вызван, только если игрок запрыгнет в точку, в которую не могут забраться NPC, либо разрывом соединения игрока с сервером (Например релог со второго окна).

Если NPC был уведен от своей изначальной точки на существенное расстояние, то во время возвращения он в какой-то момент зависает, если поблизости от него нет игроков. Если же кто-то из игроков вновь появляется в его зоне видимости, то он снова начинает возвращаться в изначальную точку.

Если же завести NPC в малопосещаемое место, а также учитывая то, что NPC во время возвращения игнорирует текстуры и может зависнуть в них, то вероятность его самостоятельного возвращения без вмешательства ГМ становится минимальной.

**Как должно работать?**

Заклинание не должно ломать механику эвейда NPC.

**Шаги для воспроизведения ошибки:**

1. Применить "Контроль над разумом" на NPC
2. Отменить действие заклинания правой кнопкой мыши.
3. Отбежать на определенное расстояние, которое превышает зону эвейда NPC.

**Текущее обновление ядра:**

Build 178

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by gmKroshka** [comment]
В следующем обновлении данная ошибка будет исправлена.

Updates BotBOT - Сегодня в 14:40
Исправлен эксплоит, позволяющий уводить мобов за пределы агро-радиуса при помощи МК
