### ISSUE TITLE
задание id 13086 Последний рубеж

### ISSUE THREAD

**Issue by dlkjfalkf** [VirginTeam/VirginCore#669]
задание Последний рубеж http://ru.wowhead.com/quest=13086

Добавьте описание проблемы здесь.
Если сразу сесть на пушку то не видно мобов необходимых убить для цели
Если вылететь чуть дальше, то мобов видно, но проподает пушка

**Что работает не так?**
при посадки на пушку не видно мобов которых надо убить для цели задания

Фактический результат — тот, который вы наблюдаете
при посадки на пушку не видно мобов которых надо убить для цели задания
при вылете чуть дальше мобов видно, но проподает пушка

**Как должно работать?**
садишься на пушку и убиваешь мобов
https://www.youtube.com/watch?v=8sD5UN067m8&feature=youtu.be

Logon 3 WowCircle Development
Build 178 2017-12-05 11:53:10 +0400

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by gmOverfire** [comment]
Дубликат
#73
