### ISSUE TITLE
[Группа предметов] Зелье невидимости/Зелье невидимости

### ISSUE THREAD

**Issue by Ewropa** [VirginTeam/VirginCore#67]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не выводит из состояния невидимости при использованных ID 3823, ID 9172 (http://ru.wowhead.com/item=3823, http://ru.wowhead.com/item=9172) на полях боя

**Что работает не так?**

Не выводит из состояния невидимости, при захвате флага на полях боя

**Как должно работать?**

Захват флага должен выводить из состояния невидимости, либо не должно быть возможности использовать захват, до окончания бафа.

**Шаги для воспроизведения ошибки:**

1. Подходим к точке, где есть большое скопление ПВП игроков противоположной фракции
2. Выпиваем зелье, получаем баф Простая невидимость Невидимость и можем спокойно юзать флаг для захвата, ничего не опасаясь, что нас увидят

**Текущее обновление ядра:**

PTR: Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
