### ISSUE TITLE
[Задание] id 12274 - Греховное падение

### ISSUE THREAD

**Issue by lambazta** [VirginTeam/VirginCore#670]
**Описание:**

Проблема с одним из телохранителей Верховного настоятеля Ландгрена. 
http://db.logon3.com/?npc=27245

**Что работает не так?**

После звонка в колокол один из телохранителей поднимается наверх, а второй остается стоять внизу, из-за чего не появляется диалог с Верховным настоятелем Ландгреном, требующийся для продолжения квеста. Убить второго телохранителя тоже не возможно - все удары и способности по нему - промахи.

**Как должно работать?**

После использования колокола стражи около нпс http://db.logon3.com/?npc=27245 уходят, а сам нпс после диалога с ним должен следовать на выход из монастыря и выходит за пределы крепости алого натиска, где мы после небольшого ивентика можем его убить.

**Шаги для воспроизведения ошибки:**

1. Принять облик жреца-ворона Алого Натиска. (Работает)
2. Подняться под крышу аббатства. (Работает)
3. Позвонить в колокол. (Работает)
4. Спуститься вниз для разговора с Верховным настоятелем Ландгреном, пока телохранители ушли наверх. (Второй телохранитеть не уходит (и не убивается) - диалог не появляется)

**Текущее обновление ядра:**

[11:29:15] Последнее обновление ядра: Build 178 2017-12-05 11:53:10 +0400

**Comment by gmKroshka** [comment]
Выполняла квест на выходных-работает. Обновлений на х1 после этого не было.

**Comment by lambazta** [comment]
Не работает. В данный момент стою около этого нпс второй телохранитель по прежнему никуда не уходит и убить его тоже не возможно. Возможно в выходные он работал, но сейчас совершенно точно - нет.

**Comment by lambazta** [comment]
Заработал после перезагрузки серва.

**Comment by djex777** [comment]
Видимо снова не работает. Такая же история: телохранитель не убивается, настоятель стоит на месте.

**Comment by LexFreeman-nsk** [comment]
В данный момент не работает, предыдущий квест в цепочке не дает форму. Оба моба убегают после удара в колокол, но нпц не становится дружественным и не разговаривает.

**Comment by LexFreeman-nsk** [comment]
для тех, кто добрался с этим квестом сюда...=) 
после того как отдали зеркало и взяли этот квест, нужно снова обратиться к могильщице и принять облик жреца-ворона Алого Натиска, поговорив с ней.
затем идем бить в колокол,
затем идем общаться с  Верховным настоятелем Ландгреном (в  моем случае всегда, пока траил этот квест телохранители исправно уходили на башню)
затем, не дожидаясь его действий, выходим из здания и заходим за него. Там уже стоит застаканная пачка копий этого Верховного настоятеля Ландгрена =) ждем своего. Он через минуту приходит. 
Пытаемся поговорить со своим настоятелем (из той багнутой пачки. которая уже там стоит).
Квест заканчивается.
Хорошо, если кому-то помог.
