### ISSUE TITLE
[Заклинание] ID 51230 - Буээээ!

### ISSUE THREAD

**Issue by Santaria94** [VirginTeam/VirginCore#672]
**Описание:**

http://ru.wowhead.com/spell=51230

Вас рвет на землю! Гуманоиды замедляются и заражаются, зомби излечиваются.

**Что работает не так?**

Способность полностью не работает. Отсутствует замедление и заражение живых целей в области поражения, а также исцеление зомби. Кто-то утверждает, что исцеление есть, но на себя оно не действует. Подтверждения этому найти не удалось, т.к. исцеление могло поступать и от автоатак зомби, а не от этой способности. Так или иначе, она должна исцелять и самого игрока, что подтверждается комментариями игроков с wowhead, которые можно найти по ссылке выше.

**Как должно работать?**

Способность должна исцелять всех зомби, а также замедлять и заражать всех в области поражения. Последний пункт с заражением интересует больше всего.

**Шаги для воспроизведения ошибки:**

Использовать способность на живых целях и зомби. Понаблюдать за результатом и сравнить с тем, что должно быть.

**Текущее обновление ядра:**

Билд 181

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by ForesterDev** [comment]
Исправлено. Применено
