### ISSUE TITLE
не обновляются подземелия БАГ

### ISSUE THREAD

**Issue by dlkjfalkf** [VirginTeam/VirginCore#674]
не обновляются подземелия - при нажатии обновить все подземелия
раньше при нажатии обновить все подземелию все обновлялось
а сейчас не обновлятеся

**Comment by sega693** [comment]
Ты уверен, что внутри нет никого?
Поставь героик, потом обычку (или наоборот).

**Comment by kalipsa988** [comment]
не оформлено, можно обновлять инсты меняя сложности, кнопка обновить подземелья работает до появления гер режима инстов вроде

**Comment by dlkjfalkf** [comment]
пробовал, 3 дня назад все работало, после нажатия обнвоить все подземелия в чате появлялась надпись - такое то подемелие обновлено, а сейчас не обновляет.
Делаю все один

**Comment by dlkjfalkf** [comment]
сегодня попробовал и все работает
