### ISSUE TITLE
[Задание] ID 4941 - Мудрость Эйтригга

### ISSUE THREAD

**Issue by san911** [VirginTeam/VirginCore#675]
**Описание:**

Невозможно поговорить с Эйтриггом в Оргриммаре.

**Что работает не так?**

Подходим к Эйтриггу в крепости Громмаш вызываем диалоговое окно, нажимаем на кнопку продолжения диалога и ничего не происходит. Т.е. выполнить цепочку квестов на получение ключа в Логово Ониксии не представляется возможным.

**Как должно работать?**

Подходим к Эйтриггу в крепости Громмаш вызываем диалоговое окно, нажимаем на кнопку продолжения диалога, он говорит нам что-то, и сдаем квест тут же Траллу, затем получаем следующий.

**Шаги для воспроизведения ошибки:**

1. После успешного выполнения квеста "Приказ полководца" (ID #4903), получаем этот (ID #4941).
2. Прибегаем в Оргриммар к Эйтриггу и вызываем диалоговое окно с ним.
3. Не можем продолжить диалог с Эйтриггом (т.к. при нажатии кнопки ничего не происходит).

**Текущее обновление ядра:**

Build 183 2017-12-22 17:58:05 +0400 (Live Server)

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
