### ISSUE TITLE
БАГ отправка почты другой фракции на своем аке

### ISSUE THREAD

**Issue by dlkjfalkf** [VirginTeam/VirginCore#676]
БАГ - невозможно отправить почту персонажу другой фракции на своем аккаунте

- Игроки теперь могут отправлять почту персонажам другой фракции на своем аккаунте.
http://forum.wowcircle.com/showthread.php?t=736119
Updatepack 156 - 02.12.17

**Comment by sega693** [comment]
Вроде только голда и фамильки должны отправляться

**Comment by gmKroshka** [comment]
Вы дали ссылку на обновления с Logon 1.
Мы Logon 3 :)
