### ISSUE TITLE
[Предмет] ID 45994 (личный кабинет)

### ISSUE THREAD

**Issue by OrcKingdom28** [VirginTeam/VirginCore#677]
**Описание:**
Доброго времени суток, случилась такая нерпиятность - приобрел на персонажа (McCrusher, pve virgin) 2 потерянных кольца, хотев немного усилить персонажа, и подготовиться у грядущим данжам и героикам 80ых лвл, но кольца не дают абсолюно никаких статов.

**Что работает не так?**
Проблема в том что кольцо приобретенное через ЛК пришло по почте без "метки" и следовательно не дает никаких статов, а потраченное количество бонусов можно было просто обменять на золото и купить экипировку получше.

**Как должно работать?**

При получении к кольцу дожна случайным методом присваиваться "метка", определяющая атрибуты которые будут увеличены при надевани, чего тут не наблюдаеться даже после одевания зазначеного айтема. Судя по базе данных метки есть в игре (http://db.logon3.com/?item=45994).
Хотелось бы обменять 2 оставшихся кольца на робочие, или же присвоить метки имеющимся, или чделать хоть что-то, 200 бонусовхоть и не много, но что-то полезней вендорного треша по 5г приобрести бы можно.
**Шаги для воспроизведения ошибки:**

1. Покупаем через ЛК.
2. Забираем из почты

**Текущее обновление ядра:**
Build 185 2017-12-25 18:07:30
Logon 3, pvex1 virgin

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by gmOverfire** [comment]
Предметы со случайными зачарованиями нельзя приобретать через лк, т.к чарка накладывается на предмет только в момент получения его из лута.
Обращайтесь в ЦП http://logon3.com/support
