### ISSUE TITLE
[Задание] ID 9595 - Самоконтроль

### ISSUE THREAD

**Issue by WarFoll2** [VirginTeam/VirginCore#678]
**Описание:**
Не появляется "Призрак кель'дорайского мага" 
**Что работает не так?**
Не появляется "Призрак кель'дорайского мага" после уничтожения определённого числа мурлоков.
**Как должно работать?**
Уничтожаем определённое количество мурлоков илистого берега, после чего появляется "Призрак кель'дорайского мага".
**Шаги для воспроизведения ошибки:**
1.Прибегаем на Илистый берег
2. Уничтожаем несколько мурлоков, как сказано в задании.
3. После уничтожения мурлоков должен появится "Призрак кель'дорайского мага", но этого не происходит
**Текущее обновление ядра:**
Build 185 2017-12-25 18:07:30 +0400 (Live Server)

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
