### ISSUE TITLE
"Отмычка", некроситет.

### ISSUE THREAD

**Issue by Malivan** [VirginTeam/VirginCore#679]
**Описание:**
Невозможно получить предмет "отмычка". Следствие того что невозможно взять\продолжить цепочку заданий на этот предмет.

**Что работает не так?**

Отсутствует квест у всех НПЦ данной цепочки заданий для персонаж "Паречька". Цепочка не когда не завершалась этим персонажем.

**Как должно работать?**

Взять задание с н-точки цепочки заданий и выполнить его, как следствие получить предмет "отмычка".

**Шаги для воспроизведения ошибки:**

Не уверен в том была ли начата цепочка заданий, так как был не малый перерыв в игре, по этому не могу описать шаги воспроизведения.

**Текущее обновление ядра:**
Build 185 2017-12-25 18:07:30 +0400

**Comment by NIFOX013** [comment]
Вы пробовали начинать цепочку заданий? Стартует в Штормграде (Альянс)/Оргримар(Орда) у нпс-глашатаев?

Просто многие думают что она в самих Чумных землях(Западные) стартует?

**Comment by gmKroshka** [comment]
У кого именно Вы пытаетесь взять задание?

**Comment by Malivan** [comment]
По этому комментарию с http://ru.wowhead.com:   "...далее ордынцу придется сделать следующие задания: Вылазка в стан Алого Ордена->Сторожевые башни->Некроситет->Фрагменты скелетов->Форма денег стоит->Кузня Пламенного хребта->Скарабей Аража->Ключ от Некроситета(Отмычка). Отмычка - ваша.".
Пробовал взять у НИП дающих все выше перечисленные задания.

**Comment by Malivan** [comment]
вы правы, спасибо за уделенное внимание.
