### ISSUE TITLE
Арена гурубаши, "великий хозяин арены гурубаши".

### ISSUE THREAD

**Issue by Malivan** [VirginTeam/VirginCore#680]
**Описание:**

Невозможно взять задание с предмета "повелитель арены",  игра пишет "вы выполнили это задание.

**Что работает не так?**

Я, принял задание "великий хозяин арены гурубаши", после чего через не большой промежуток времени, меньше 30 минут, я был вынужден использовать "anti error" в личном кабинете, задание пропало, принять снова нет возможности, игра отвечает что задание выполнено но при этом достижение не выполнено.

**Как должно работать?**

Возможность принять задание с предмета.

**Шаги для воспроизведения ошибки:**

1.Получить из сундука на "арене гурубаши"  предмет дающий задание, аксессуар "повелитель арены".
2.Принять задание "великий хозяин арены гурубаши".
3.В течении меньше чем 30минут по принятию задания использовать "anti error".

**Текущее обновление ядра:**

Build 185 2017-12-25  18:07:30 +0400

**Comment by kalipsa988** [comment]
ты сдал задание после первого принятия?

**Comment by kalipsa988** [comment]
я всё понял, после сдачи кв с самой первой трини автоматически делается задание на 12 таких тринь, его нет в списке заданий и взять его нельзя, его можно только выполнить собрав 12 тринек с сундука и сразу отдать ему, а значёк задания будет висеть на трине после первой сдачи и будет постоянно писать задание выполнено

**Comment by Malivan** [comment]
Спасибо, за быструю реакцию.
