### ISSUE TITLE
Гербовая накидка "исследователя".

### ISSUE THREAD

**Issue by Malivan** [VirginTeam/VirginCore#681]
**Описание:**

После исследования всех территорий "Нордскола" и получении достижения "Нордскол" не получил накидку "исследователя".

**Что работает не так?**

Достижение "Нордскол" есть, памятной гербовой накидки "исследователя" нет.

**Как должно работать?**

По выполнению достижения "Нордскол" на игровую почту должно было придти письмо с гербовой накидкой "исследователя".

**Шаги для воспроизведения ошибки:**

1.Выполнить достижение "Нордскол".

**Текущее обновление ядра:**

Build 185 2017-12-25 18:07:30 +0400

**Comment by gmKroshka** [comment]
Оформите заявку в Центре поддержки со скриншотами полученных достижений
http://logon3.com/support
