### ISSUE TITLE
Малфурион Ярость Бури

### ISSUE THREAD

**Issue by Malivan** [VirginTeam/VirginCore#682]
**Описание:**

Не появляется в "затонувшем храме" при прохождении данного подземелья несколько дней подряд.

**Что работает не так?**

Фактически НПЦ "Малфурион Ярость Бури" отсутствует на своем месте в "затонувший храм".

**Как должно работать?**

НПЦ "Малфурион Ярость Бури" должен появляться  перед комнатой последнего босса в подземелье "затонувший храм" и предлагать задание.

**Шаги для воспроизведения ошибки:**

1.Пройти подземелье "затонувший храм" до комнаты с последним босом.

**Текущее обновление ядра:**

Build 185 2017-12-25 18:07:30 +0400

**Comment by sega693** [comment]
Только если преквесты делл в цепочке на жука. В силитусе

**Comment by Malivan** [comment]
Были сделаны все  сопутствующие задания.

**Comment by gmKroshka** [comment]
Выполняла квесты позавчера-присутствует в подземелье.

**Comment by Ewropa** [comment]
там вообще была вот такая беда http://forum.wowcircle.com/showthread.php?t=554783

**Comment by Malivan** [comment]
ну лучше уж 2, чем ни одного в єтом случае.
