### ISSUE TITLE
Нат Пегл, "наживка на грязнотинника".

### ISSUE THREAD

**Issue by Malivan** [VirginTeam/VirginCore#683]
**Описание:**

Невозможно купить "наживка на грязнотинника".

**Что работает не так?*

НПЦ "Нат Пегл" вообще не предлагает товаров.

**Как должно работать?**

Купить "наживку на гразнотинника" и выполнить достижение "последний улов".

**Шаги для воспроизведения ошибки:**

1.Попытаться купить "наживка на грязнотинника" у НПЦ "Нат Пегл".

**Текущее обновление ядра:**

Build 185 2017-12-25 18:07:30 +0400

**Comment by olegklim1991** [comment]
как бы все работает,ты квест сделай для начала,начало кв в зулгурубе,

**Comment by Malivan** [comment]
Хорошо, спасибо.
