### ISSUE TITLE
Собаки-каки

### ISSUE THREAD

**Issue by NIFOX013** [VirginTeam/VirginCore#685]
**Описание:**

Не выполняется задание: Собаки-каки. http://ru.wowhead.com/quest=11728

**Что работает не так?**

Не срабатывает квестовый итем: http://ru.wowhead.com/item=35121. Волк не становится нейтральным и не производит какашек из которых достается http://ru.wowhead.com/item=35123

**Как должно работать?**

Кидаете кусок мяса-волк становится желтым (нейтральным), через пару секунд появляется какашка, ее лутаете и оттуда достается микропленка

**Шаги для воспроизведения ошибки:**

1. Кидаете http://ru.wowhead.com/item=35121 в волка http://ru.wowhead.com/npc=25791

**Текущее обновление ядра:**

Build 186 2017-12-29 12:06:40 +0400

LIVE

**Comment by gmKroshka** [comment]
https://github.com/VirginTeam/VirginCore/issues/230
