### ISSUE TITLE
Цена на полетку

### ISSUE THREAD

**Issue by Kl1N** [VirginTeam/VirginCore#687]
Описание:
Не работает скидка на покупку полетки искусник

Что работает не так?:
Нет скидки при превознесении 

Как должно работать?
При получении превознесения у Кирин-тора есть скидка на полетку что приводит к цене в 4к а она остается как без репы в 5к

Текущее обновление ядра:
Build 186 2017-12-29 12:06:40 +0400

**Comment by ForesterDev** [comment]
Тренеры в Низине Шолазар, Грозовой Гряде, и Даларане не признают никаких репутаций, так что стоимость обучения у них снижена быть не может.
