### ISSUE TITLE
[Предмет] ID 22830 - Эликсир "Зоркий глаз"

### ISSUE THREAD

**Issue by deexeq** [VirginTeam/VirginCore#688]
**Описание:**

Проблема взаимодействия с другим эликсиром.

**Что работает не так?**

Эффект [Эликсир "Зоркий глаз"](http://db.logon3.com/?item=22830) складывается с эффектом [Эликсир "Кошачий глаз"](http://db.logon3.com/?item=10592)

**Как должно работать?**

Эффект [Эликсир "Зоркий глаз"](http://db.logon3.com/?item=22830) не должен складывается с эффектом [Эликсир "Кошачий глаз"](http://db.logon3.com/?item=10592)

> Though it's classified as an elixir, it won't use up either your Guardian or Battle slot. Thus, you can use it with a flask or the combination of a battle and guardian elixir. However, it will not stack with  Catseye Elixir. Searching Eye is the more powerful effect, so it won't let you drink Catseye while it's still active.

**Текущее обновление ядра:**

Build 186 2017-12-29 12:06:40 +0400

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
