### ISSUE TITLE
[Задание] ID 5214 - Великий Фрас Сиаби

### ISSUE THREAD

**Issue by Ewropa** [VirginTeam/VirginCore#69]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Не работает задание http://wowroad.info/?quest=5214

**Что работает не так?**

 Фрас Сиаби не приходит на стрелку раскурить http://wowroad.info/?item=13172 

**Как должно работать?**

Нип должен появляться

**Шаги для воспроизведения ошибки:**

1. Пойти в Стратхольм
2. Забить стрелку у почтового ящика 
3. И никого

**Текущее обновление ядра:**

PTR: Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
