### ISSUE TITLE
[Задание] ID 2118 - Зачумленные земли

### ISSUE THREAD

**Issue by Rinawow** [VirginTeam/VirginCore#690]
**Описание:**
В Аубердине Тарнариун Исцелитель Деревьев по квесту "Зачумленные земли" не выдает вторую ловушку. 
**Что работает не так?**
По кв нужно поймать медведя в нее, но в первый раз он почему-то не становится послушным. Соответственно, мне нужна вторая или чтобы работала корректно первая.
Фактический результат — тот, который вы наблюдаете
При нажатии на просьбу о второй ловушке ничего не происходит. Кв отменяла и начинала заново - результат тот же.
**Как должно работать?**
При нажатии на просьбу дать вторую ловушку Тарнариун должен ее выдавать. Сама ловушка должна делать медведя послушным на временной промежуток.
**Шаги для воспроизведения ошибки:**

1. Шаг один. Получаем квест и ловушку для медведя
2. Шаг два. Используем ловушку, медведь не пойман
3. Шаг три. Просим новую ловушку у Тарнариуна, ничего не получаем т.к при нажатии кнопки ничего не происходит

**Текущее обновление ядра:**
Build 186 2017-12-29 12:06:40 +0400 Live Server

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
