### ISSUE TITLE
[NPC] ID 3467 - Барон Дольноберег

### ISSUE THREAD

**Issue by eva299** [VirginTeam/VirginCore#691]
В степях вместо 1 Барона Дольноберег (npc=3467) находится 2. Респаунт тоже у двоих.
В принципе проблема не глобальная, но в одного тяжелее становиться сделать кв.
Этот мир слишком тесен для двух Баронов, необходимо по правилу одного ликвидировать.

**Comment by ForesterDev** [comment]
Исправлено. Будет применено в обновлении
