### ISSUE TITLE
[NPC] ID 9596 - Баннок Люторез

### ISSUE THREAD

**Issue by kapusta19941994** [VirginTeam/VirginCore#693]
**Описание:**

Баннок Люторез http://wowroad.info/?npc=9596 из Нижняя часть Черной горы http://wowroad.info/?achievement=643 не появился ни разу более чем за 100 заходов в Убийства Генерала Драккисата (Пик Черной горы) http://wowroad.info/?achievement=1096

**Что работает не так?**

Убийства Генерала Драккисата (Пик Черной горы) http://wowroad.info/?achievement=1096 были только Джед Руновед http://wowroad.info/?npc=10509 и Горалук Треснувшая Наковальня http://wowroad.info/?npc=10899 из Верхняя часть Черной горы http://wowroad.info/?achievement=1307 со 100% появлением

**Как должно работать?**

Баннок Люторез http://wowroad.info/?npc=9596 из Нижняя часть Черной горы http://wowroad.info/?achievement=643 должен появляться примерно один раз из пяти заходов в Убийства Генерала Драккисата (Пик Черной горы) http://wowroad.info/?achievement=1096

**Шаги для воспроизведения ошибки:**

1. с вероятностью 20% должен Баннок Люторез
2. убивается Баннок Люторез

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by ForesterDev** [comment]
Вероятность появления НПЦ 12%
