### ISSUE TITLE
[Заклинание] ID 31224 - Плащ Теней

### ISSUE THREAD

**Issue by 0v3rd0s3d** [VirginTeam/VirginCore#696]
**Описание:**

http://db.logon3.com/?spell=31224

**Что работает не так?**

Имеется общий ГКД с другими способностями.

**Как должно работать?**

Способность должна иметь мгновенное применение.

**Шаги для воспроизведения ошибки:**

1. Шаг один - использовать любую способность, стартующую ГКД;
2. Шаг два - дождаться отката ГКД для использованияПлаща Теней;
3. Шаг три - использовать Плащ Теней;

**Текущее обновление ядра:**

Build 186 2017-12-29 12:06:00 +0400.
Logon3 WowCircle server.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Gooldark** [comment]
Механика ГКД вшита в клиент, это невозможно исправить.
