### ISSUE TITLE
проблема с персонажем в игровой зоне "Низина шолазар"

### ISSUE THREAD

**Issue by meelkij** [VirginTeam/VirginCore#698]
**Описание:**
проблема с персонажем в игровой зоне "Низина шолазар"
Добавьте описание проблемы здесь.
Нет заданий у оракулов
**Что работает не так?**
Прошел все задания за племя бешеного сердца (ачив на превознос и ачив за задания имеются), открылись оракулы(оракулы-дружелюбие племя. бешенного сердца - ненависть) , но у них( оракулов) нет ни 1 ежедневного задания( взять невозможно)
Фактический результат — тот, который вы наблюдаете
нет заданий у оракулов
**Как должно работать?**
после прохождения цепочки заданий на племя бешенного сердца и прохождения последнего задания на убийство волчера в пещере ( дабы открыть оракулов) идем сдавать задание к оракулам и они дают ежедневные задания.
Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы
задания оракулов
**Шаги для воспроизведения ошибки:**
шаги неизвестны так как баг именно у персонажа ( на другом персонаже все работает исправно)
Игровой ник персонажа в игре Доринн
1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Bulid 186 2017-12-29 12:06:40 +04.00

**Comment by gmOverfire** [comment]
Не тема для баг-трекера.
Проверяйте проблему после обновления сервера, в случае ее сохранения оформляйте запрос в центр поддержки http://logon3.com/support/
