### ISSUE TITLE
[Задание] ID 12673 - Сбор кристаллов

### ISSUE THREAD

**Issue by Devinette** [VirginTeam/VirginCore#7]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Скриншоты демонстрирующие проблему, выделение проблемных мест с помощью графических редакторов приветствуются. Для описания ошибок, возникающих только в движении, снимите видео **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

После применения [Скипетр внушения](http://ru.wowhead.com/item=39157) в подчинении оказывается [Гнилостный упырь](http://ru.wowhead.com/npc=28750), но способность  [Добыча кристалла гнили](http://ru.wowhead.com/spell=52245) не работает.

**Что работает не так?**

Упырь игнорирует способность.

**Как должно работать?**

Упырь отправляется собирать кристалл и убегает с ним.

**Шаги для воспроизведения ошибки:**

1. Подчиняем упыря при помощи скипетра
2. Нажимаем спелл  Добыча кристалла

**Текущее обновление ядра:**

Актуально на Build 143 2017-03-13 14:38:04 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления

**Comment by pavaknsk** [comment]
На 14.08.2017 квест не работает.
