### ISSUE TITLE
[Задание] ID 12644 - Выпивка – дело тонкое…

### ISSUE THREAD

**Issue by Razama1234** [VirginTeam/VirginCore#70]
**Описание:**

Нельзя выполнить квест.

**Что работает не так?**

Для запуска ивента надо поговорить с [Поддатым "Макманусом"](http://wotlk.imobilazer.net/?npc=28566), но он не доступен для диалога, и поэтому нельзя запустить событие.

**Как должно работать?**

После взятия квеста подходим к Поддатому Макманусу и нажимаем строчку диалога, запуская ивент. После делаем все как он просит, и при успехе сдаём квест.

**Шаги для воспроизведения ошибки:**

1. Взять квест

**Текущее обновление ядра:**

Build 151 2017-04-03 15:25:08 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
