### ISSUE TITLE
[Задание] ID 13906 - Они так быстро растут

### ISSUE THREAD

**Issue by b4vrn** [VirginTeam/VirginCore#704]
**Описание:**

http://db.logon3.com/?quest=13906

**Что работает не так?**

При наличии в рюкзаке всех необходимых для сдачи квеста предметов квест "не сдается". Не активна кнопка "продолжить" в меню квеста. При этом в дневнике стоит отметка "Выполнено".

**Как должно работать?**

Квест должен корректно завершаться квестгивером с выдачей игроку 
http://db.logon3.com/?item=46102

**Шаги для воспроизведения ошибки:**

1. Взятие квеста
2. Выполнение условий его сдачи, то есть сбор: 
1x Равазаврик (итем выдается при взятии квеста)
20x Молочный зуб равазавра (награда за ежедневный квест, взятый у Равазаврика)
20x Руническая ткань
20x Грубая кожа
80г
3. Шаг три
Попытка сдачи квеста.

**Текущее обновление ядра:**

Build 186 2017-12-29 12:06:40 +0400

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by odino4estvo** [comment]
Решение простое, отмени задание (наличие предметов в инвентаре при этом сохранится!), и по новой возьми квест и сразу же квестгиверу сдай!

**Comment by b4vrn** [comment]
Проблема исчезла после рестарта сервера. Квест благополучно сдался квестгиверу.
