### ISSUE TITLE
[Задание] ID 6621 - Король гиблой чащи

### ISSUE THREAD

**Issue by fazov** [VirginTeam/VirginCore#706]
**Описание:**

http://db.logon3.com/?quest=6621

**Что работает не так?**

Стою на тотемном холме, не могу установить знамя, выдает сообщение: "Требуется находиться на тотемном холме.". Таким образом выполнить квест никак не удается.

**Как должно работать?**

Должно устанавливаться знамя и начаться следующая фаза квеста - защита знамени до прибытия вождя.

**Шаги для воспроизведения ошибки:**

1. Взятие квеста
2. Придти в пункт назначения
3. Попытаться установить знамя кликнув по его иконке:
http://db.logon3.com/?item=16972

**Текущее обновление ядра:**

Build 186 2017-12-29 12:06:40 +0400

Имя персонажа в игре: Achek

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by gmOverfire** [comment]
Дубликат #258
