### ISSUE TITLE
отображение "улучшенный ожог"

### ISSUE THREAD

**Issue by iljasem** [VirginTeam/VirginCore#709]
**Описание:**
улучшенный ожог пропадает 
Добавьте описание проблемы здесь.
когда начинаю кастовать "УО" иконка появляется на цели секунды на 2-3 после исчезает
**Что работает не так?**
дебаф "улучшенный ожог" пропадает
Фактический результат — тот, который вы наблюдаете
"УО" пропадает с таргета
**Как должно работать?**
УО должен присутсвовать как и "живая бомба"

Ожидаемый результат — то, чего вы ожидали при выполнении ваших действий. Процесс правильной работы

**Шаги для воспроизведения ошибки:**

1. Шаг один
2. Шаг два
3. Шаг три

**Текущее обновление ядра:**

Можно посмотреть в игре, введите в чат команду .server info и скопировать строку начиная с Build с номером и датой. Не забывайте указывать, Live Server или PTR Server, где проводилось тестирование.

[//]: # (** Всё, что ниже и выделено спецальными символами, это базовая информация о шаблоне баг репорта, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Когда требуется указать ссылку на игровые данные, используйте нашу базу данных: http://db.logon3.com **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Если вы хотите задать вопрос или уточнить что-то связанное с разработкой, присоединяйтесь к нашему каналу в Discord - https://discord.gg/A7kMHba **)
[//]: # (** Теперь можете заполнять поля выше, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Comment by Gooldark** [comment]
Дебаф скорее всего перекрывается дебафом шадоуболта лока, так и должно быть.
