### ISSUE TITLE
[Подземелье] Терраса Магистров - (ID 24685 Магистр из клана Солнечного Клинка)

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#78]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Бедняга пытается скастовать все и сразу.

**Что работает не так?**

НПЦ пытается скастовать несколько абилок одновременно, и в итоге у него получается только бафнуть себя. Другие заклинания, естественно, обрываются.
>13:56:33> [Магистр из клана Солнечного Клинка] начинает использовать "[Ледяная стрела]".
13:56:33> [Магистр из клана Солнечного Клинка] применяет заклинание "[Чары ускорения заклинаний]".
13:56:35> [Магистр из клана Солнечного Клинка] начинает использовать "[Ледяная стрела]".
13:56:35> [Магистр из клана Солнечного Клинка] применяет заклинание "[Чары ускорения заклинаний]".

**Как должно работать?**

Сводите беднягу в Хогвартс, пусть научится использовать заклинания правильно.

**Текущее обновление ядра:**

PTR: Build 20 2017-04-05 12:06:47 +0400

**Comment by ForesterDev** [comment]
Исправлено, тестируйте после применения
