### ISSUE TITLE
[Задание] ID 13288 - Как все погано!

### ISSUE THREAD

**Issue by Razama1234** [VirginTeam/VirginCore#79]
**Описание:**

Полурабочий квест.

**Что работает не так?**

У вызываемого Поганища нет панели управления, поэтому все приходится делать вручную.

**Как должно работать?**

Из [Неповоротливое поганище](http://wowroad.info/?npc=31140) выбивается [предмет](http://wowroad.info/?item=43966), и с помощью него можно собрать своё собственное поганище и взорвать толпы нежити.
[Видео.](https://www.youtube.com/watch?v=PAQiujWVI1M)

**Шаги для воспроизведения ошибки:**

1. Взять квест
2. Выбить внутренности.
3. Собрать поганище.

**Текущее обновление ядра:**

Build 151 2017-04-03 15:25:08 +0400

**Comment by Devinette** [comment]
Дубль
https://github.com/VirginTeam/VirginCore/issues/47
