### ISSUE TITLE
[Задание] ID 13380 - Возглавить нападение

### ISSUE THREAD

**Issue by Razama1234** [VirginTeam/VirginCore#80]
**Описание:**

Полурабочий квест.

**Что работает не так?**

Карен Нет должна выдать нам бомбардировщик для убийства квестовых мобов, но не выдаёт. Поэтому всё приходится делать вручную.
До кучи [Карен Нет](http://wowroad.info/?npc=31648), [Вилли Возможно](http://wowroad.info/?npc=32524), [Джонни Да](http://wowroad.info/?npc=32523) находятся не под куполом, где находится квестодатель [Кибли Киллогерц](http://wowroad.info/?npc=32444), который в свою очередь стоит немного не там, где надо. Ещё [Капитан из зоны бомбардировки](http://wowroad.info/?npc=32410) и [Пехотинец из зоны бомбардировки](http://wowroad.info/?npc=32399) невидимы, можно наткнуться или пройдя мимо, либо переключением целей на Tab, либо макросом /ц Капитан из зоны бомбардировки.
Вот как примерно должно [выглядеть](https://www.youtube.com/watch?v=nnJMLBD4oHs)

**Как должно работать?**

При просьбу выдать нам бомбардировщик нас сажают в него и мы убиваем мобов, сдаём квест.

**Шаги для воспроизведения ошибки:**

1. Взять квест.
2. Попросить выдать у Карен Нет бомбардировщик.
3. Убить мобов вручную.

**Текущее обновление ядра:**

Build 151 2017-04-03 15:25:08 +0400

**Comment by Riazarre** [comment]
Есть более актуальный репорт - #451 
Закрыто.
