### ISSUE TITLE
[Задание] ID 13318 - Перетащить и опустить

### ISSUE THREAD

**Issue by Razama1234** [VirginTeam/VirginCore#81]
**Описание:**

Полурабочий квест.

**Что работает не так?**

Нет нпс, которым можно применить [квестовый предмет](http://wowroad.info/?item=44246).

**Как должно работать?**

После получения сферы её можно использовать на [Тёмном поработителе](http://wowroad.info/?npc=32236), и того после превращения утаскивает гаргулья.
[Видео.](https://www.youtube.com/watch?v=DTK7hf8cwzs)

**Шаги для воспроизведения ошибки:**

1. Взять квест.
2. Выбить сферу

**Текущее обновление ядра:**

 Build 151 2017-04-03 15:25:08 +0400

**Comment by Scoren** [comment]
мобы летают в море около драконьего погоста

**Comment by ForesterDev** [comment]
исправлено, протестируйте после обновления
