### ISSUE TITLE
[Задание] ID 13170 - Честь – удел слабых

### ISSUE THREAD

**Issue by Razama1234** [VirginTeam/VirginCore#82]
**Описание:**

Полурабочий квест.

**Что работает не так?**

Неутомимый дозорный не убивается 5ой способностью. Проблема решается банальным убийством моба героем.
Ещё при отключении контроля над Эйдолонским наблюдателем нас должно телепортировать на место, где мы брали под контроль, а не в том месте, где мы его прерываем.
Ещё при контроле экран должен стать серым.

**Как должно работать?**

Неутомимый дозорный убивается 5ой способностью сразу.
[Видео.](https://www.youtube.com/watch?v=IJHKEX5J1Cc
)

**Шаги для воспроизведения ошибки:**

1. Взять квест.
2. Найти Неутомимого дозорного.
3. Попробовать использовать 5ый скил.

**Текущее обновление ядра:**

Build 151 2017-04-03 15:25:08 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
