### ISSUE TITLE
[Задание] ID 13169 - Лучший друг нежити

### ISSUE THREAD

**Issue by Razama1234** [VirginTeam/VirginCore#83]
**Описание:**

Полурабочий квест.

**Что работает не так?**

Собаки не реагируют на мясо, брошенное при помощи 4ого скила. Проблема решается банальным убийством моба героем.

**Как должно работать?**

Собаки реагируют на брошенное мясо.
[Видео.](https://www.youtube.com/watch?v=xXo5G2Axci4)

**Шаги для воспроизведения ошибки:**

1. Взять квест.
2. Взять тень под контроль.
3. Попытаться использовать 4ый скил.

**Текущее обновление ядра:**

Build 151 2017-04-03 15:25:08 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверяйте после обновления
