### ISSUE TITLE
[Заклинание] ID 33831 - Сила природы

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/VirginCore#85]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

При использовании Сила природы (ID 33831) все цели в стелсе, в довольно большом радиусе выходят из стелса/инвиза

**Как должно работать?**

Само использование Сила природы (ID 33831) никак не должно влиять на стелс/инвиз.

**Шаги для воспроизведения ошибки:**

1. Поставить враждебного рогу в стелсе на расстоянии ~30м
2. Использовать Сила природы (ID 33831)

**Текущее обновление ядра:**

11.04.2017 птр 21 билд

**Перенесено**

http://forum.wowcircle.com/showthread.php?t=642228

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления

**Comment by Gooldark** [comment]
Работает
