### ISSUE TITLE
[Задание] ID 9759 - Отречемся от старого мира

### ISSUE THREAD

**Issue by VassiliyR** [VirginTeam/VirginCore#90]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Квест взять можно но завершить и сдать невозможно 

**Что работает не так?**

[Легосо Подрывник](http://wowroad.info/?npc=17982) после выдачи квеста стоит на месте

**Как должно работать?**

[Легосо Подрывник](http://wowroad.info/?npc=17982) после выдачи квеста должен пойти до [Сиронас](http://wowroad.info/?npc=17678). По пути необходимо его защищать(помогать). Перед энергоблоком он должен заложить взрывчатку и подниматься дальше к  [Сиронас](http://wowroad.info/?npc=17678) чтобы её убить. Квест засчитывается и сдаётся [Экзарху Адметиусу](http://wowroad.info/?npc=17658) что в свою очередь позволяет продолжить квестовую линейку. По видео на ютубе в той локации где находится [Сиронас](http://wowroad.info/?npc=17678) окружающие её мобы являются простыми а не элитными как на сервере Virgin PVEx1

**Шаги для воспроизведения ошибки:**

1. Взять квест у [Легосо Подрывник](http://wowroad.info/?npc=17982)
2. Ничего не происходит

**Текущее обновление ядра:**

Build 151 2017-04-03 15:25:08 +0400

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновлении
