### ISSUE TITLE
[Общая механика] Опыт от наследуемых предметов

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#92]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Некорректное начисление опыта при одетых фамильках в количестве, более чем 1.

**Что работает не так?**

Некорректно складываются бонусы от наследуемых предметов.
Приведем пример на 3 предметах:
10% от ID 57353 (предмет ID 48685, предмет ID 42949 и прочие подобные)
5% от ID 71354 (предмет ID 50255)
При одетом одном предмете - бонус работает корректно.
При одетых 2 предметах с разными бонусами добавляемое количество опыта = 15,49%
При одетых 2 предметах с одинаковыми бонусами добавляемое количество опыта = 20,92%
При одетых 3 предметах (2 одинаковых, и 1 отличающийся) добавляемое количество опыта = 27%

**Как должно работать?**

10%+5% = 15%
10%+10% = 20%
10%+10%+5% = 25%

**Шаги для воспроизведения ошибки:**

1. Одевать разные предметы
2. Сдавать квесты и вычислять разницу между тултипом в теле квеста и полученным опытом.

**Текущее обновление ядра:**

Virgin: Build 151 2017-04-03 15:25:08 +0400

**Comment by Librariane** [comment]
Бонусы взаимодействуют как сложные проценты, то есть перемножаются, а не складываются. На примере взаимодействия 3х бонусов: 1,1*1,1*1,05 = 1,27
 Непонятно почему вы решили, что не должно такого быть.

**Comment by Riazarre** [comment]
Спасибо за комментарий, запомню на будущее.
