### ISSUE TITLE
[Заклинание] ID 57978 - Нейтрализующий яд, ID 49005 - Кровавая метка

### ISSUE THREAD

**Issue by Gooldark** [VirginTeam/VirginCore#93]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Что работает не так?**

Нейтрализующий яд(ID 57978), Кровавая метка(ID 49005) на игроках висят 15 и 20 секунд соответственно.

**Как должно работать?**

Нейтрализующий яд(ID 57978), Кровавая метка(ID 49005) в пвп должны висеть не более 10 секунд(касается и петов)

**Текущее обновление ядра:**

12.04.2017 птр 21 билд

**Доказательства**

https://www.youtube.com/watch?v=OR-bIxvAzR0 - 6:12 маг получает метку от дк, но она висит 10 секунд
https://www.youtube.com/watch?v=p0OTZMl-uhM - 2:56 - дк дает метку и жмет незыблемость(12 время действия), при этом метка исчезает раньше незыблемости.
http://www.warcraftmovies.com/movieview.php?id=163197 - любой момент время действия яда 10 сек.

**Перенесено**
http://forum.wowcircle.com/showthread.php?t=599206
http://forum.wowcircle.com/showthread.php?t=555298

**Comment by ForesterDev** [comment]
Исправлено

**Comment by Gooldark** [comment]
Кровавая метка(ID 49005) исправлено
Нейтрализующий яд(ID 57978) по прежнему висит 15 секунд нужна доработка

**Comment by Gooldark** [comment]
На 157 билде все работает
