### ISSUE TITLE
[Задание] ID 658 - Новая чума зарождается?

### ISSUE THREAD

**Issue by Riazarre** [VirginTeam/VirginCore#94]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Курьер http://ru.wowhead.com/npc=2714
Телохранители http://ru.wowhead.com/npc=2721

**Что работает не так?**

После убийства Курьера - его труп через секунд 15 стремительно "убегает" в точку `X: -1609.969971 Y: -2755.760010 Z: 37.394299 Ориентация: 1.457340`
Курьер ресается на этом же месте, и после чего (если его найдет игрок) - идет по прямой линии, сквозь текстуры (горы, холмы, прочие препятствия) к стартовой точке маршрута, а затем начинает движение по маршруту. НПЦ гуляет один, телохранители стоят в точке реса Курьера.

**Как должно работать?**

Труп курьера должен лежать все время до спавна, и не должен перемещаться.
Курьер должен спавниться в стартовой точке маршрута (у фермы), вместе с телохранителями (если старые телохранители живы - они должны исчезнуть).

**Текущее обновление ядра:**

PTR: Build 21 2017-04-11 16:24:08 +0400

**Comment by ForesterDev** [comment]
Исправлено, проверьте после обновления
