### ISSUE TITLE
[NPC] ID 9046 - Интендант из легиона Изрубленного Щита 

### ISSUE THREAD

**Issue by Iammelkor** [VirginTeam/VirginCore#95]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Должен стоять моб, при убийстве которого лутается квеститем. Респаун моба 20-30 секунд, согласно комментария вовхеда версии 3.0.9. ID Моба 9046

**Что работает не так?**

Моба или вообще нет, или респаун долго времени.
http://ipic.su/img/img7/fs/WoWScrnShot_041317_114926.1492073451.jpg
Рядом стоящий моб реснулся, как и все другие, а его нет.

**Как должно работать?**

Вообще с заселением проблема, можно увидеть на видео, как должно по идее быть.
https://www.youtube.com/watch?v=diQNCTRvGwA&list=PLaBf2hOTcK8U_RCUdDqRHFzwHVAgqMJGq&index=3

**Шаги для воспроизведения ошибки:**

Зайти ко входу в УБРС, БВЛ и найти нужного моба.

**Текущее обновление ядра:**

Билд 151

**Comment by ForesterDev** [comment]
Исправлено, будет применено после обновления
