### ISSUE TITLE
[NPC] ID 14347 - Верховный лорд Демитриан

### ISSUE THREAD

**Issue by wenaern** [VirginTeam/VirginCore#97]
**Описание:**
Если у игрока (в сумке) имеются легендарные наручи (ID 18564 или 18563), то у данного НПС заменяется диалог на: "дай мне сосуд, верховный лорд" - при нажатии которого выдаётся специальный квест итем "Сосуд Возрождения" (ID 19016).

**Фактический результат — тот, который вы наблюдаете**
Сосуд Возрождения (ID 19016) не выдаётся при соблюдении условий.

**Шаги для воспроизведения ошибки:**
1. Получить одну из частей наручей (ID 18564 или 18563) к себе в сумку.
2. Подойти к Верховный лорд Демитриан (ID 14347) и поговорить с ним.
3. Не обнаружить в своей сумке квест итема "Сосуд Возрождения" (ID 19016).

**Текущее обновление ядра:**
Билд 153

**Перенесено:**
http://forum.wowcircle.com/showthread.php?t=639203

**Comment by ForesterDev** [comment]
Исправлено, будет применено в обновленийй

**Comment by Scoren** [comment]
исправлен
