### ISSUE TITLE
[Предмет] ID 21138- Осколок красного скипетра

### ISSUE THREAD

**Issue by Iammelkor** [VirginTeam/VirginCore#98]
[//]: # (** Ниже предоставлена базовая информация о шаблоне, её не нужно удалять, она не попадёт в сам репорт и предназначена для ознакомления **)
[//]: # (** Этот шаблон предназначен для всех репортов по игровым и серверным проблемам, не редактируйте его и не изменяйте без надобности **)
[//]: # (** Перед созданием репорта прочитайте в Wiki тему - Стандартизация заголовков для репортов **)
[//]: # (** Приоритеты и ярлыки назначаются только сотрудниками проекта или модераторами багтрекера **)
[//]: # (** Ни в коем случае не указывайте название игровой учётной записи или пароль от неё, вы можете оставить имя персонажа для обратной связи с вами **)
[//]: # (** Заполните поля ниже, их можно редактировать, кроме заголовков отмеченных звёздочками **)

**Описание:**

Осколок для создания скипетра зыбучих песков падает с Нефариона, ежели соблюдены два условия, Нефарион убит и взят квест Нефариус, пораженный порчей(ID квеста 8730)

**Что работает не так?**

Хм, взяли квест, убили босса, еще 4 часа до истечения кв. Лут упал, но осколок нет(ID осколка 21138).

**Как должно работать?**

Падать осколок.

**Шаги для воспроизведения ошибки:**

Зайти в инст, взять квест, убить нефариона, получить квеститем.

**Текущее обновление ядра:**

Билд 153

**Comment by ForesterDev** [comment]
Не подтверждаю - падает со 100% шансом в случае активного квеста

https://snag.gy/Xw3RCu.jpg

**Comment by Iammelkor** [comment]
Не вопрос, тогда это как понимать?
Лутал я.
http://ipic.su/img/img7/fs/WoWScrnShot_041417_135954.1492196871.jpg Только основной лут(на 60-й лвл и все)

**Comment by ForesterDev** [comment]
Осколок падает 1 на весь рейд, учитывая что чат замазан - скорее всего кто-то залутал это Осколок. Пруфы: http://ru.wowhead.com/item=21138#comments
